import {readFile,writeFile} from 'node:fs/promises';import {resolve} from 'node:path';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';
const root=resolve(import.meta.dirname,'../..'),out=resolve(root,'output/tsc-step2j-r00'),r=JSON.parse(await readFile(resolve(out,'gravity_coupon_results.json'),'utf8')),sharp=createRequire(import.meta.url)(process.env.PM_SHARP_PATH||'sharp');
const ink='#19313d',muted='#536974',teal='#166a77',orange='#a64a1b',blue='#315fa2';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;'),txt=(x,y,s,size=23,c=ink,w=400)=>`<text x="${x}" y="${y}" font-size="${size}" fill="${c}" font-weight="${w}">${esc(s)}</text>`,line=(x,y,X,Y,c='#d7e0e5',w=1,arr=false)=>`<line x1="${x}" y1="${y}" x2="${X}" y2="${Y}" stroke="${c}" stroke-width="${w}" ${arr?'marker-end="url(#arr)"':''}/>`;
const f=(v,d=4)=>Math.abs(v)<1e-9?'≈0':v.toFixed(d),pct=v=>v>0&&v*100<.001?'<0.001%':f(v*100,3)+'%';
const doc=(title,sub,body)=>`<svg xmlns="http://www.w3.org/2000/svg" width="1800" height="1580"><defs><marker id="arr" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L10 5L0 10z" fill="context-stroke"/></marker></defs><rect width="1800" height="1580" fill="white"/><g font-family="Tahoma,Segoe UI,sans-serif"><rect width="1800" height="12" fill="${teal}"/>${txt(60,68,title,34,ink,700)}${txt(60,113,sub,23,muted)}${line(60,145,1740,145)}${body}${line(60,1475,1740,1475)}${txt(60,1519,'S2J-R00 / EXACT GRAVITY COUPON / NOT FOR DESIGN OR CONSTRUCTION',24,orange,700)}${txt(60,1558,'ผ่านเฉพาะโจทย์อ้างอิงนี้ ไม่รับรองโมดูลโค้ง ขอบYอิสระ ฐานจริง หรือรายละเอียดรอยต่อ TS-C',22,muted)}</g></svg>`;
const g=r.basis.geometry,m=r.basis.material,gamma=m.density_kg_m3*m.gravity_m_s2/1000,q=gamma*g.width_m*g.thickness_m,W=q*g.length_m,rows=r.runs.filter(v=>v.nu===.2),fine=rows.at(-1);
let a=txt(65,205,'ชิ้นตรง 1.50 × 0.25 × 0.175 ม. / น้ำหนักตัวเท่านั้น / Uy=0 ทุก node',26,ink,700);
a+=txt(65,250,`γ = ${f(gamma,5)} kN/m³ / q = ${f(q,6)} kN/m / น้ำหนักรวม ${f(W,6)} kN`,23,muted);
a+=txt(65,290,'ลูกศรลงแสดงแรงกระจายเทียบเท่าน้ำหนักตัว q=γwt ไม่ใช่แรงกดผิวหลังคา',21,muted);
const X=x=>870+x*800,Z=z=>465-z*800;
a+=`<rect x="270" y="395" width="1200" height="140" fill="#e6eff2" stroke="${teal}" stroke-width="3"/>`;
for(const x of [-.65,-.45,-.25,0,.25,.45,.65])a+=line(X(x),330,X(x),408,teal,2,true);
for(const x of [-.75,.75])a+=line(X(x),610,X(x),520,blue,3,true)+txt(X(x)-70,650,`${f(W/2)} kN ↑`,24,blue,700);
for(const x of [-.375,0,.375])a+=line(X(x),375,X(x),555,orange,2)+txt(X(x)-70,585,`X=${f(x,3)} m`,22,orange);
a+=line(1570,530,1670,530,ink,2,true)+txt(1680,538,'+X',22)+line(1570,530,1570,440,ink,2,true)+txt(1544,428,'+Z',22);
a+=txt(65,725,'ลูกศรปลายคือแรงรวมของ prescribed end traction ไม่ใช่จุดรองรับจริง',24,orange,700);
a+=txt(65,772,'แรงเฉือนปลายเป็นพาราโบลา และมี normal traction แบบ self-equilibrated รวมแรง/โมเมนต์เป็นศูนย์',23,muted);
a+=txt(65,816,'datum: Ux=0 กลางช่วง และ Uz=0 กึ่งกลางหน้าปลายทั้งสอง; ใช้ตัด rigid modes ไม่ได้จำลอง bearing',22,muted);
a+=txt(65,882,'คำตอบอ้างอิงจากสมดุล + compatibility + Hooke law',27,ink,700);
['a=L/2, c=t/2, K=3γ/(2c²), q=γwt','σxx = Kz [x²−a² + 2c²/5 − 2z²/3]','τxz = Kx(c²−z²)    /    σzz = K(z³−c²z)/3','σyy = ν(σxx+σzz); σxy=τyz=0','Fz = qx    /    My = q(x²−a²)/2    /    Fx=Fy=Mx=Mz=0'].forEach((s,i)=>a+=txt(75,938+i*50,s,25,i===4?teal:ink));
a+=txt(65,1238,'แรงหน้าตัดบนฝั่งซ้าย (+X normal); โมเมนต์รอบ [Xcut, w/2, 0]',23,muted);
a+=txt(65,1285,'ที่กึ่งกลาง: Fz=0; ที่ผิวบน/ล่าง: τxz=σzz=0; div(σ)+(0,0,−γ)=0',24,teal,700);
a+=txt(65,1342,'สูตรพหุนามอนุมานและตรวจในโครงการ ไม่ใช่สูตรออกแบบ วสท. หรือ Euler–Bernoulli approximation',22,muted);
a+=txt(65,1390,'ใช้ฟังก์ชันรวม traction เดิมของ Step 2I โดยไม่แก้ เพื่อทดสอบกับคำตอบที่ตรวจได้',23,ink,700);
const first=doc('TS-C / โจทย์อ้างอิงแรงเฉือนจากน้ำหนักตัว','ทดสอบวิธีอ่านความเค้นก่อนขยาย full-bay mesh — ไม่มี roof LL หรือการเลือกจุดต่อผลิต',a);
let b=txt(65,205,'ν=.20 / แยกความละเอียดตามความยาว nx และความหนา nz',27,ink,700);
b+=txt(65,250,'ny=2 คงเดิม; J1–J4 เพิ่ม nx ที่ nz=2, J3/J5/J6 เพิ่ม nz ที่ nx=32, J7เพิ่มทั้งสอง',23,muted);
const xx=[75,240,435,700,990,1240,1520];['Mesh nx×nz','Elements','Δu error','τxz RMS error','Max cut error','Center Fz (kN)','ครบทุกเกณฑ์'].forEach((s,i)=>b+=txt(xx[i],311,s,21,muted));
rows.forEach((v,i)=>[`${v.mesh} ${v.nx}×${v.nz}`,v.elements,pct(v.displacement_error_relative),pct(v.stress_rms_relative[5]),pct(Math.max(...v.cuts.flatMap(c=>Object.values(c.traces).flatMap(t=>t.relative_vs_exact_6)))),f(v.cuts[1].traces.lower.order6.resultant_6[2],7),v.accuracy_targets_met?'เฉพาะ coupon':'ยังไม่ครบ'].forEach((s,j)=>b+=txt(xx[j],361+i*49,s,22,j===6?(v.accuracy_targets_met?teal:orange):ink)));
b+=txt(65,745,'สองผลที่ต้องตรวจแยกกัน',27,ink,700);
b+=txt(75,797,`J3→J4 (nz=2): center |Fz| ${f(Math.abs(rows[2].cuts[1].traces.lower.order6.resultant_6[2]),7)} → ${f(Math.abs(rows[3].cuts[1].traces.lower.order6.resultant_6[2]),7)} kN`,24,teal);
b+=txt(75,841,`แต่ τxz RMS ยัง ${pct(rows[2].stress_rms_relative[5])} → ${pct(rows[3].stress_rms_relative[5])}; เพิ่มความยาวอย่างเดียวยังไม่พอ`,23,orange);
b+=txt(75,902,`J3→J5→J6 (nx=32): τxz RMS ${[rows[2],rows[4],rows[5]].map(v=>pct(v.stress_rms_relative[5])).join(' → ')}`,24,teal);
b+=txt(75,947,'ต้องตรวจทั้งแรงรวมหน้าตัดและความเค้นภายใน ไม่ใช้การโก่งตัวน้อยเป็นตัวแทนทุกค่า',23,ink);
b+=txt(65,1024,'ผลครบทั้งชุด 9 runs / 27 cuts × 2 traces',27,ink,700);
const met=r.runs.filter(v=>v.accuracy_targets_met),cuts=r.runs.flatMap(v=>v.cuts);
b+=txt(75,1074,`Coupon accuracy ครบ ${met.length}/9 runs; cut criteria ครบ ${cuts.filter(c=>c.targets_met).length}/27 cuts`,24,teal,700);
b+=txt(75,1120,'ν=0 control: J3 ยังไม่ครบ / J7 ครบ — ไม่ใช่การเลือกค่า Poisson ของคอนกรีตจริง',23,muted);
b+=txt(75,1166,`J7 ν=.20: τxz RMS ${pct(fine.stress_rms_relative[5])}; max cut error ${pct(Math.max(...fine.cuts.flatMap(c=>Object.values(c.traces).flatMap(t=>t.relative_vs_exact_6))))}`,23,ink);
b+=txt(65,1241,'เกณฑ์เดิม: u/energy≤2%, stress RMS6องค์ประกอบ≤5%, cut/referenceและpair≤5%',23,muted);
b+=txt(65,1287,'ตัวหารอ้างอิง: stressอย่างน้อย10kPa; force .1kN / moment .1kN·m — ไม่ใช่อัตราใช้กำลัง',22,muted);
b+=txt(65,1350,'ข้อสรุปจำกัด: วิธี traction เดิมให้ผลดีขึ้นได้เมื่อ mesh เหมาะกับโจทย์นี้ ไม่ได้แก้ TS-C โดยอัตโนมัติ',23,orange);
b+=txt(65,1400,'ถัดไปนำหลักฐานไปแยก profile/thickness refinement ในโมดูลเดิม โดยคงโหลดและBCไว้',23,ink,700);
const second=doc('TS-C / ผล benchmark: ความยาวกับความหนาคุมคนละค่า','แสดงผลที่ผ่านและยังไม่ผ่านทั้งหมด — ไม่ใช้ผล coupon ยกระดับสถานะวิศวกรรมของอาคาร',b);
const boards=[['TS-C-GRAVITY-FBD-S2J-R00','โจทย์อ้างอิงน้ำหนักตัวและสูตรแรงหน้าตัด',first],['TS-C-GRAVITY-QA-S2J-R00','ผลตรวจแรงเฉือนกับความละเอียดสองทิศ',second]];
for(const [id,,svg] of boards){await writeFile(resolve(out,id+'.svg'),svg);await sharp(Buffer.from(svg)).png().toFile(resolve(out,id+'.png'));}
const deps={...r.dependency_hashes};for(const p of ['output/tsc-step2j-r00/gravity_coupon_results.json','tools/tsc-study/render_gravity_coupon.mjs'])deps[p]=createHash('sha256').update(await readFile(resolve(root,p))).digest('hex');
const runs=r.runs.map(v=>({...v,cuts:v.cuts.map(c=>({...c,traces:Object.fromEntries(Object.entries(c.traces).map(([side,t])=>[side,{...t,order4:{resultant_6:t.order4.resultant_6,area_m2:t.order4.area_m2},order6:{resultant_6:t.order6.resultant_6,area_m2:t.order6.area_m2}}]))}))}));
await writeFile(resolve(out,'web_summary.json'),JSON.stringify({...r,runs,dependency_hashes:deps,drawings:boards.map(([id,title])=>({id,title,file:id+'.png'}))},null,2));console.log(boards.map(b=>b[0]).join('\n'));
