import {readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
const root=resolve(import.meta.dirname,'../..'),out=resolve(root,'output/tsc-step2i-r00');
const r=JSON.parse(await readFile(resolve(out,'local_mesh_results.json'),'utf8')),a=JSON.parse(await readFile(resolve(out,'traction_results.json'),'utf8'));
const sharp=createRequire(import.meta.url)(process.env.PM_SHARP_PATH||'sharp');
const ink='#19313d',muted='#536974',teal='#166a77',orange='#a64a1b',blue='#315fa2',colors=['#96a8b0',blue,orange,teal];
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;');
const txt=(x,y,s,size=23,c=ink,w=400)=>`<text x="${x}" y="${y}" font-size="${size}" fill="${c}" font-weight="${w}">${esc(s)}</text>`;
const line=(x,y,X,Y,c='#d7e0e5',w=1,arr=false)=>`<line x1="${x}" y1="${y}" x2="${X}" y2="${Y}" stroke="${c}" stroke-width="${w}" ${arr?'marker-end="url(#arr)"':''}/>`;
const f=(v,d=3)=>Math.abs(v)<1e-8?'≈0':v.toFixed(d),pct=v=>f(v*100)+'%';
const doc=(title,sub,body)=>`<svg xmlns="http://www.w3.org/2000/svg" width="1800" height="1700"><defs><marker id="arr" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L10 5L0 10z" fill="context-stroke"/></marker></defs><rect width="1800" height="1700" fill="white"/><g font-family="Tahoma,Segoe UI,sans-serif"><rect width="1800" height="12" fill="${teal}"/>${txt(60,68,title,34,ink,700)}${txt(60,113,sub,23,muted)}${line(60,145,1740,145)}${body}${line(60,1595,1740,1595)}${txt(60,1637,'S2I-R00 / DIRECTIONAL DIAGNOSTIC / NOT FOR DESIGN OR CONSTRUCTION',24,orange,700)}${txt(60,1676,'คงแบบจำลองคอนกรีตไม่ร้าว ฐานและ crown อุดมคติ ไม่ใช่การรับรองความหนา เหล็ก หรือจุดต่อ',22,muted)}</g></svg>`;
const runs=[r.reference_run,...r.runs];
let b=txt(65,205,'เพิ่มความละเอียดเฉพาะทิศทาง / โหลด FULL เท่านั้น / t175 / 20-node',27,ink,700);
b+=txt(65,249,'H4 เป็นฐานเปรียบเทียบเดิม; เพิ่ม 3 runs โดยไม่เปลี่ยนวัสดุ โหลด ฐาน หรือ crown',23,muted);
const tx=[75,255,780,1090,1400];['Mesh','สิ่งที่เพิ่มจาก H4','Elements','Nodes','|u|max (mm)'].forEach((s,i)=>b+=txt(tx[i],311,s,23,muted));
const labels=['ฐานอ้างอิงเดิม','แบ่ง 3 ช่องแรกเหนือฐาน ช่องละ 4','แบ่ง Y ใกล้ขอบทั้งสองด้าน','รวม IB + IY'];
runs.forEach((s,i)=>[s.mesh,labels[i],s.elements.toLocaleString(),s.nodes.toLocaleString(),f(s.max_displacement_mm,6)].forEach((v,j)=>b+=txt(tx[j],362+i*53,v,23,j===0?colors[i]:ink)));
b+=txt(65,584,'มุมโค้งยัง 24 ช่อง / ความหนายัง 6 ชั้น / ไม่มี hanging nodes; ไม่ใช่การเพิ่ม mesh ทุกทิศ',23,orange);
b+=txt(65,641,'Profile LH / เหนือฐาน 50 มม. / Y=.75 ม. / ความเค้นภายในเนื้อ',26,ink,700);
for(const [j,k] of [2,4].entries()){
  const X=135+j*845,Y=713,W=650,H=255,all=r.profiles.flatMap(p=>p.points.map(s=>s.mean_kPa[k]));
  const lo=Math.floor(Math.min(0,...all)/5)*5,hi=Math.max(lo+5,Math.ceil(Math.max(0,...all)/5)*5),xx=v=>X+v*W,yy=v=>Y+H-(v-lo)/(hi-lo)*H;
  b+=txt(X,Y-22,j?'τsn (kPa)':'σnn (kPa)',23,ink,700);
  for(let i=0;i<=4;i++){const v=lo+(hi-lo)*i/4;b+=line(X,yy(v),X+W,yy(v))+txt(X-80,yy(v)+7,f(v,1),19,muted);}
  for(const v of [0,.25,.5,.75,1])b+=txt(xx(v)-12,Y+H+32,v.toFixed(2),19,muted);
  b+=txt(X+165,Y+H+68,'f = ระยะจากผิวใน / t',21,muted);
  r.profiles.forEach((p,i)=>{b+=`<polyline points="${p.points.map(s=>[xx(s.fraction),yy(s.mean_kPa[k])].join(',')).join(' ')}" fill="none" stroke="${colors[i]}" stroke-width="3"/>`;for(const s of p.points)b+=`<circle cx="${xx(s.fraction)}" cy="${yy(s.mean_kPa[k])}" r="4" fill="${colors[i]}"/>`;});
}
r.profiles.forEach((p,i)=>b+=line(200+i*375,1070,247+i*375,1070,colors[i],3)+txt(267+i*375,1077,p.mesh,23));
b+=txt(65,1140,'ความไวที่จุดตรวจ: max point change / เปรียบเทียบแต่ละคู่',26,ink,700);
const xs=[75,430,720,1060,1400];['คู่เปรียบเทียบ','ภายในทั่วไป','ขอบด้านข้าง','ใกล้ฐาน','ใกล้ crown'].forEach((s,i)=>b+=txt(xs[i],1194,s,23,muted));
r.local_comparisons.forEach((c,i)=>[c.pair.join(' → '),...c.groups.map(g=>pct(Math.max(...g.fields.map(v=>v.max_point_change))))].forEach((v,j)=>b+=txt(xs[j],1245+i*51,v,23)));
b+=txt(65,1476,'เกณฑ์ครบ: point/RMS/one-sided spread ≤5% ทุกองค์ประกอบ; ตัวหารอย่างน้อย10kPa',23,muted);
b+=txt(65,1528,'เปอร์เซ็นต์ไม่ใช่อัตราใช้กำลัง · คู่เปรียบเทียบทิศทางไม่ยืนยัน convergence ทั้งโมดูลหรือโหลด LEFT',23,orange);
const first=doc('TS-C / เพิ่ม mesh ใกล้ฐานและขอบด้านข้าง','แยกผลของความละเอียด โดยรักษาสมมติฐานเดิมเพื่อไม่ปะปนกับการเปลี่ยนสภาพรองรับ',b);
const selected=a.runs.find(v=>v.mesh==='IBY'),h4=a.runs.find(v=>v.mesh==='H4'&&v.pattern==='FULL'),c=selected.cuts.find(v=>v.id==='CROWN');
let d=txt(65,205,'รวม traction σ·n และโมเมนต์ r×(σ·n) ผ่านหน้าตัดเดียวกัน',27,ink,700);
d+=txt(65,250,'เก็บความเค้นจาก element ทั้งสองฝั่งแยกกัน ไม่ smooth หรือบังคับเฉลี่ยให้สมดุล',23,muted);
d+=`<rect x="110" y="330" width="360" height="210" fill="#e6eff2" stroke="${teal}" stroke-width="2"/><rect x="640" y="330" width="360" height="210" fill="#edf1f8" stroke="${blue}" stroke-width="2"/>`;
d+=txt(143,388,'ส่วนล่าง LH',27,teal,700)+txt(666,388,'ส่วนบน / ฝั่งตรงข้าม',26,blue,700);
d+=line(470,435,584,435,teal,3,true)+txt(485,411,'+n',23,teal)+line(640,478,526,478,blue,3,true)+txt(565,517,'−n',23,blue);
d+=txt(145,494,'lower trace',23,teal)+txt(681,494,'upper trace',23,blue);
['F = ∫ σ·n dA','M = ∫ (x−origin) × (σ·n) dA','origin: กึ่งกลางแต่ละ cut, Y=.75 m','6 components / kN และ kN·m','ตรวจ quadrature 4×4 เทียบ 6×6'].forEach((s,i)=>d+=txt(1080,338+i*50,s,23,i===0?ink:muted));
d+=txt(65,607,'ภาพแผนผังทิศ normal ของคู่หน้าตัด ไม่ใช่ทิศแรงจริงทุกองค์ประกอบ; ใช้ local orientation ตาม cut',22,muted);
d+=txt(65,672,'ตัวอย่าง IBY / FULL: แรงบนฝั่งล่าง LH เทียบ nodal cut',27,ink,700);
const cx=[75,280,500,725,975,1200,1450];['Cut','Fx nodal','Fx traction','Fz nodal','Fz traction','My nodal','My traction'].forEach((s,i)=>d+=txt(cx[i],728,s,22,muted));
selected.cuts.forEach((s,i)=>[s.id,f(s.nodal_lower_6[0]),f(s.traces.lower.order6.resultant_6[0]),f(s.nodal_lower_6[2]),f(s.traces.lower.order6.resultant_6[2]),f(s.nodal_lower_6[4]),f(s.traces.lower.order6.resultant_6[4])].forEach((v,j)=>d+=txt(cx[j],780+i*48,v,23)));
d+=txt(65,1093,'ทั้งชุด: 8 runs เดิม FULL/LEFT + 3 runs ใหม่ FULL / รวม 66 cuts × 2 traces',24,ink,700);
const count=a.runs.flatMap(v=>v.cuts).filter(v=>v.targets_met).length;
d+=txt(65,1139,`ครบเกณฑ์ทั้ง6องค์ประกอบ: ${count}/66 cuts; ไม่ใช้สมดุล nodal อย่างเดียวรับรองความเค้น`,24,orange);
const oldc=h4.cuts.find(v=>v.id==='CROWN');
d+=txt(65,1200,'ตัวอย่าง crown Fz ซึ่ง nodal ≈0: ต้องดูค่าแรงจริงควบคู่เปอร์เซ็นต์',25,ink,700);
d+=txt(65,1246,`H4 FULL: lower ${f(oldc.traces.lower.order6.resultant_6[2],6)} / upper ${f(oldc.traces.upper.order6.resultant_6[2],6)} kN`,23);
d+=txt(65,1292,`IBY FULL: lower ${f(c.traces.lower.order6.resultant_6[2],6)} / upper ${f(c.traces.upper.order6.resultant_6[2],6)} kN`,23);
d+=txt(65,1338,`IBY ผลรวมสอง trace Fz = ${f(c.trace_pair_sum_6[2],6)} kN; normalized = ${pct(c.trace_pair_relative_6[2])}`,23,orange);
d+=txt(65,1397,'ตัวหารอย่างน้อย 0.1 kN หรือ 0.1 kN·m; เกณฑ์ trace/reference และ trace-pair ≤5%',23,muted);
d+=txt(65,1443,'ความต่างนี้เป็นประเด็น numerical stress recovery ไม่ใช่แรงภายนอกเพิ่ม หรืออัตราการใช้กำลัง',23,muted);
d+=txt(65,1495,'Affine stress patch ตรวจ normal/area/units/origin แล้ว; ไม่ใช่ exact solution ของโมดูลรับแรงโน้มถ่วง',22,muted);
d+=txt(65,1540,'ยังต้องตรวจทิศตาม profile/ความหนาและผลของฐานจริง ก่อนนำ local stress ไปออกแบบ',23,orange);
const second=doc('TS-C / ตรวจแรงจากความเค้นผ่านแนวตัด','เปรียบเทียบ continuum traction กับแรงหน้าตัดจาก nodal equilibrium โดยเก็บความไม่ตรงกันไว้',d);
const boards=[['TS-C-LOCAL-MESH-S2I-R00','ความไวของ mesh ใกล้ฐานและขอบด้านข้าง',first],['TS-C-TRACTION-S2I-R00','แรงผ่านหน้าตัดจากความเค้นสองด้าน',second]];
for(const [id,,svg] of boards){await writeFile(resolve(out,id+'.svg'),svg);await sharp(Buffer.from(svg)).png().toFile(resolve(out,id+'.png'));}
const deps={...r.dependency_hashes,...a.dependency_hashes};for(const p of ['output/tsc-step2i-r00/local_mesh_results.json','output/tsc-step2i-r00/traction_results.json','tools/tsc-study/render_local_mesh.mjs'])deps[p]=createHash('sha256').update(await readFile(resolve(root,p))).digest('hex');
const traction={affine_traction_patch:a.affine_traction_patch,runs:a.runs.map(v=>({...v,cuts:v.cuts.map(c=>({...c,traces:Object.fromEntries(Object.entries(c.traces).map(([side,t])=>[side,{...t,order4:{resultant_6:t.order4.resultant_6,area_m2:t.order4.area_m2},order6:{resultant_6:t.order6.resultant_6,area_m2:t.order6.area_m2}}]))}))}))};
await writeFile(resolve(out,'web_summary.json'),JSON.stringify({...r,traction,dependency_hashes:deps,raw_output_hashes:{...r.raw_output_hashes,...a.raw_output_hashes},drawings:boards.map(([id,title])=>({id,title,file:id+'.png'}))},null,2));
console.log(boards.map(v=>v[0]).join('\n'));
