import {readFile,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),sharp=require(process.env.PM_SHARP_PATH||'sharp');
const root=resolve(import.meta.dirname,'../..'),out=resolve(root,'output/tsc-step2k-r00');
const r=JSON.parse(await readFile(resolve(out,'profile_thickness_verified.json'),'utf8'));
const rows=[r.reference_run,...r.runs],esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;');
const text=(x,y,s,size=23,color='#263c4d')=>`<text x="${x}" y="${y}" font-size="${size}" fill="${color}">${esc(s)}</text>`;
const pct=v=>Math.abs(v)<.00001?'&lt;0.001%':(100*v).toFixed(3)+'%';
const labelPct=v=>Math.abs(v)<.00001?'<0.001%':(100*v).toFixed(3)+'%';
const doc=(title,body)=>`<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1280"><rect width="1600" height="1280" fill="#f4f6f8"/><g font-family="Tahoma,Arial,sans-serif">${text(60,70,title,34)}${text(60,115,'TS-C / S2K-R00 / FULL · t175 · NC320 trial · F-R · bonded crown',24)}<rect x="45" y="145" width="1510" height="62" rx="10" fill="#fff0dc"/>${text(65,185,'NUMERICAL STUDY ONLY — ไม่ใช่การอนุมัติความหนา เหล็ก จุดต่อ หรือแบบผลิต',24,'#9c4f0c')}${body}${text(60,1235,'Internal study / 2 new solves + H4 control / Geometry, loads and support assumptions unchanged',20)}</g></svg>`;
let a=text(60,270,'แยกสองทิศทาง — ไม่เพิ่มความหนาคอนกรีต',29);
const xs=[70,280,525,760,1060,1300];
['Mesh','Wall / arc / roof*','Y / thickness','Elements / nodes','|u|max (mm)','LH Rx (kN)'].forEach((v,i)=>a+=text(xs[i],330,v,21));
rows.forEach((v,i)=>{const cells=v.mesh==='KP'?'27 / 32 / 22':'25 / 24 / 11';[v.mesh,cells,`16 / ${v.mesh==='KT'?8:6}`,`${v.elements} / ${v.nodes}`,v.max_displacement_mm.toFixed(7),v.base.LH[0].toFixed(6)].forEach((s,k)=>a+=text(xs[k],390+i*60,s,23));});
a+=text(70,575,'* จำนวนช่องตามแนวหน้าตัดต่อซีก; thickness = จำนวนชั้น mesh ไม่ใช่ขนาดคอนกรีต',22);
a+=text(70,640,'KP: แบ่ง 2 ช่องบนสุดของผนัง, 4 ช่องแรก/ท้ายของส่วนโค้ง และทุกช่องหลังคาตรง เป็นสอง',23);
a+=text(70,685,'KT: คงแนวหน้าตัดเดิม เพิ่มชั้นตามความหนา 6 → 8; ความหนาจริงคง 175 มม.',23);
a+=text(70,750,'ความไวของ global results เทียบ H4 (ไม่ใช่ code acceptance)',27);
const global=r.runs.map(v=>({mesh:v.mesh,displacement_change:Math.abs(v.max_displacement_mm/r.reference_run.max_displacement_mm-1),energy_change:Math.abs(v.strain_energy_kNm/r.reference_run.strain_energy_kNm-1)}));
global.forEach((v,i)=>a+=text(80,810+i*55,`${v.mesh}: Δ|u|max ${labelPct(v.displacement_change)} / Δenergy ${labelPct(v.energy_change)}`,25));
a+=text(70,960,'ฐาน H4 คง Y16: รอบนี้ไม่ได้เพิ่มความละเอียดใกล้ฐาน/ขอบแบบ IBY',24,'#9c4f0c');
a+=text(70,1010,'490 จุดกายภาพเดิม / local s-y-n / 6 cuts × 2 traces / ไม่ smooth ความเค้นข้ามหน้า',24);
a+=text(70,1070,'KP+KT รวมกัน และการนำกลับไปใช้ร่วมกับ IBY ยังไม่ได้คำนวณ',24,'#9c4f0c');
a+=text(70,1120,'ผลรอบนี้ใช้แยกผลของ mesh เท่านั้น ไม่ใช้การโก่งตัวน้อยยืนยันความปลอดภัย',24);
let b=text(60,270,'Local stress: เกณฑ์ point / RMS / one-sided spread ≤5% ทุกองค์ประกอบ',26);
const local=r.local_comparisons.map(c=>({pair:c.pair,groups:c.groups.map(g=>({group:g.group,point:Math.max(...g.fields.map(f=>f.max_point_change)),spread:Math.max(...g.fields.map(f=>f.max_spread_relative)),met:g.all_six_targets_met}))}));
let y=325;
for(const c of local){b+=text(65,y,c.pair.join(' → '),26,'#087c7c');y+=45;for(const g of c.groups){b+=text(85,y,`${g.group}: point ${labelPct(g.point)} / spread ${labelPct(g.spread)} / ${g.met?'ครบเฉพาะคู่ที่ตรวจ':'ยังไม่ครบ'}`,23);y+=43;}y+=20;}
b+=text(60,800,'CROWN / แรงเฉือน Fz จากแต่ละ trace (kN)',27);
['Mesh','Nodal lower','Traction lower','Traction upper','ผลรวมสอง trace'].forEach((s,i)=>b+=text([70,260,565,880,1190][i],846,s,22));
r.traction_runs.forEach((v,i)=>{const c=v.cuts.find(x=>x.id==='CROWN');[v.mesh,c.nodal_lower_6[2].toFixed(7),c.traces.lower.order6.resultant_6[2].toFixed(7),c.traces.upper.order6.resultant_6[2].toFixed(7),c.trace_pair_sum_6[2].toFixed(7)].forEach((s,j)=>b+=text([70,260,565,880,1190][j],895+i*45,s,24));});
b+=text(65,1070,`Cuts ครบทุกเกณฑ์: ${r.traction_runs.map(v=>`${v.mesh} ${v.cuts.filter(c=>c.targets_met).length}/6`).join(' · ')}`,24);
b+=text(65,1120,'Force/moment denominator floor .1 kN / .1 kN·m; stress floor10 kPa — ไม่ใช่อัตราการใช้กำลัง',22);
b+=text(65,1160,'ไม่มี exact full-bay reference; whole-model local convergence ยังไม่ยืนยัน',23,'#9c4f0c');
const boards=[['TS-C-PROFILE-MESH-S2K-R00','เปรียบเทียบ mesh แนวหน้าตัดกับความหนา',doc('TS-C / แยก profile และ thickness refinement',a)],['TS-C-PROFILE-QA-S2K-R00','ผลตรวจความเค้นและแรงหน้าตัดสองด้าน',doc('TS-C / local stress และ cut traction',b)]];
for(const [id,,svg] of boards){await writeFile(resolve(out,id+'.svg'),svg);await sharp(Buffer.from(svg)).png().toFile(resolve(out,id+'.png'));}
const deps={...r.dependency_hashes};for(const p of ['output/tsc-step2k-r00/profile_thickness_verified.json','tools/tsc-study/render_profile_thickness.mjs'])deps[p]=createHash('sha256').update(await readFile(resolve(root,p))).digest('hex');
const traction=r.traction_runs.map(v=>({...v,cuts:v.cuts.map(c=>({...c,traces:Object.fromEntries(Object.entries(c.traces).map(([s,t])=>[s,{...t,order4:{resultant_6:t.order4.resultant_6},order6:{resultant_6:t.order6.resultant_6}}]))}))}));
await writeFile(resolve(out,'web_summary.json'),JSON.stringify({id:r.id,revision:r.revision,status:r.status,runs:rows,local,global,traction,dependency_hashes:deps,raw_output_hashes:r.raw_output_hashes,engineering_approval:false,manufacturing_release:false,drawings:boards.map(([id,title])=>({id,title,file:id+'.png'}))},null,2));
console.log(boards.map(v=>v[0]).join('\n'));
