import {readFile,writeFile} from 'node:fs/promises';import {resolve} from 'node:path';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),sharp=require(process.env.PM_SHARP_PATH||'sharp'),root=resolve(import.meta.dirname,'../..'),out=resolve(root,'output/tsc-step2m-r00');
const r=JSON.parse(await readFile(resolve(out,'arc_crown_results.json'),'utf8')),runs=[...r.reference_runs,...r.runs],tr=r.traction_runs.at(-1);
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;'),txt=(x,y,s,n=23,c='#243e50')=>`<text x="${x}" y="${y}" font-size="${n}" fill="${c}">${esc(s)}</text>`,pct=v=>v<.00001?'<0.001%':(100*v).toFixed(3)+'%';
const local=r.local_comparisons.map(c=>({pair:c.pair,groups:c.groups.map(g=>({group:g.group,point:Math.max(...g.fields.map(v=>v.max_point_change)),spread:Math.max(...g.fields.map(v=>v.max_spread_relative)),met:g.all_six_targets_met}))}));
let b=txt(60,65,'TS-C / เจาะส่วนโค้งและกลางหลังคา',34)+txt(60,110,'Step 2M · KPT → M1 · FULL / t175 / NC320 trial / F-R / bonded crown',23);
b+=`<rect x="45" y="140" width="1510" height="60" rx="9" fill="#fff0db"/>`+txt(65,180,'NUMERICAL STUDY — ไม่ใช่การอนุมัติความหนา เหล็ก จุดต่อ หรือผลิต',24,'#9c4f0c');
b+=txt(70,255,'เปลี่ยนเฉพาะ profile: ส่วนโค้ง 32→48 ช่อง / หลังคาตรง22→24 ช่องต่อซีก',25);
b+=txt(70,300,'คงผนัง27ช่อง / Y16 / thickness8ชั้น / คอนกรีต175มม. ไม่เพิ่มฐานหรือแนวยาว',23);
['Mesh','Elements / nodes','|u|max mm','Crown lower Fz kN','Crown pair kN'].forEach((s,i)=>b+=txt([70,260,620,900,1240][i],365,s,22));
runs.forEach((v,i)=>{const c=r.traction_runs.find(t=>t.mesh===v.mesh).cuts.find(c=>c.id==='CROWN');[v.mesh,`${v.elements} / ${v.nodes}`,v.max_displacement_mm.toFixed(7),c.traces.lower.order6.resultant_6[2].toFixed(7),c.trace_pair_sum_6[2].toFixed(7)].forEach((s,j)=>b+=txt([70,260,620,900,1240][j],420+i*50,s,23));});
b+=txt(70,555,'M1: แรงหน้าตัดทั้งสองด้านเทียบ nodal reference / เกณฑ์ทุกคอลัมน์≤5%',26);
['Cut','Lower/reference','Upper/reference','Trace-pair','ครบทุกเกณฑ์'].forEach((s,i)=>b+=txt([70,330,650,980,1280][i],610,s,22));
tr.cuts.forEach((c,i)=>[c.id,pct(Math.max(...c.traces.lower.relative_vs_nodal_6)),pct(Math.max(...c.traces.upper.relative_vs_nodal_6)),pct(Math.max(...c.trace_pair_relative_6)),c.targets_met?'เฉพาะcutนี้':'ยังไม่ครบ'].forEach((s,j)=>b+=txt([70,330,650,980,1280][j],660+i*48,s,23)));
b+=txt(70,1000,'KPT → M1 / ความเค้นที่490พิกัดเดิม / point-RMS-spread ≤5%',26);
local[0].groups.forEach((g,i)=>b+=txt(85,1050+i*43,`${g.group}: point ${pct(g.point)} / spread ${pct(g.spread)} / ${g.met?'ครบเฉพาะคู่':'ยังไม่ครบ'}`,23));
b+=txt(70,1285,'แรง kN / โมเมนต์ kN·m รอบoriginของcut; ไม่smoothหรือเฉลี่ยความเค้นข้ามหน้า',23);
b+=txt(70,1330,'ตัวหารอย่างน้อย .1kN/.1kN·m และ10kPa — เปอร์เซ็นต์ไม่ใช่อัตราการใช้กำลัง',23);
b+=txt(70,1390,'การผ่านcutsที่ตรวจ ไม่ใช่การยืนยันความเค้นทุกจุดหรือความปลอดภัยทั้งอาคาร',24,'#9c4f0c');
b+=txt(70,1440,'ยังไม่ตรวจ base/Y refinement, real joints, cracking, openings, wind/uplift หรือhandling',22);
const id='TS-C-ARC-CROWN-QA-S2M-R00',svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1500"><rect width="1600" height="1500" fill="#f4f6f8"/><g font-family="Tahoma,Arial,sans-serif">${b}</g></svg>`;
await writeFile(resolve(out,id+'.svg'),svg);await sharp(Buffer.from(svg)).png().toFile(resolve(out,id+'.png'));
const deps={...r.dependency_hashes};for(const p of ['output/tsc-step2m-r00/arc_crown_results.json','tools/tsc-study/render_arc_crown.mjs'])deps[p]=createHash('sha256').update(await readFile(resolve(root,p))).digest('hex');
const traction=r.traction_runs.map(v=>({...v,cuts:v.cuts.map(c=>({...c,traces:Object.fromEntries(Object.entries(c.traces).map(([s,t])=>[s,{...t,order4:{resultant_6:t.order4.resultant_6},order6:{resultant_6:t.order6.resultant_6}}]))}))}));
await writeFile(resolve(out,'web_summary.json'),JSON.stringify({id:r.id,revision:r.revision,status:r.status,runs,local,traction,dependency_hashes:deps,raw_output_hashes:r.raw_output_hashes,engineering_approval:false,manufacturing_release:false,drawings:[{id,title:'ผลเพิ่มความละเอียดส่วนโค้งและกลางหลังคา',file:id+'.png'}]},null,2));console.log(id);
