import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),sharp=require(process.env.PM_SHARP_PATH||'sharp'),out='output/tsc-step2n-r00';
const r=JSON.parse(await readFile(out+'/directional_results.json','utf8'));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;');
const text=(x,y,s,n=24,color='#263d50')=>`<text x="${x}" y="${y}" font-size="${n}" fill="${color}">${esc(s)}</text>`;
const pct=v=>(100*v).toFixed(3)+'%';
const base=r.groups.find(g=>g.group==='base_probe');
const t=base.directions.find(d=>d.direction==='thickness').worst;
const y=base.directions.find(d=>d.direction==='Y').worst;
const findings=[`ฐาน: ความต่างข้ามชั้นความหนา ${t.jump_kPa.toFixed(4)} kPa (${pct(t.value)}) ในองค์ประกอบ ${t.component}`,`ฐาน: ความต่างข้ามหน้า Y สูงสุด ${y.jump_kPa.toFixed(4)} kPa (${pct(y.value)}) ในองค์ประกอบ ${y.component}`,'บริเวณขอบและภายในไม่ผ่านเฉพาะ point change ของ ss; RMS และ spread ผ่านในสองกลุ่มนี้','ไม่มีคู่ข้ามหน้า profile ที่พิกัดฐาน และไม่มีคู่ข้ามหน้า Y ที่พิกัดกลุ่ม side_edge — ไม่ใช่ค่าศูนย์'];
let s=text(60,70,'TS-C / แยกทิศความต่างของความเค้น',36)+text(60,115,'Step 2N · วิเคราะห์ผลเดิม M1 / KPT · ไม่มี FEM run ใหม่',25);
s+='<rect x="45" y="145" width="1510" height="65" rx="10" fill="#fff0db"/>'+text(65,188,'DIAGNOSTIC ONLY — คงเกณฑ์เดิม ไม่อนุมัติความหนา เหล็ก หรือจุดต่อ',25,'#9c4f0c');
s+=text(65,270,'4 รายการที่ยังไม่ผ่าน จาก 24 รายการกลุ่ม–องค์ประกอบ',28);
['กลุ่ม / องค์ประกอบ','เกณฑ์ไม่ผ่าน','ค่า normalized','ความต่าง kPa'].forEach((v,i)=>s+=text([65,600,940,1250][i],325,v,23));
let row=0;for(const g of r.groups)for(const f of g.fields.filter(f=>f.failed_metrics.length)){s+=text(65,380+row*52,g.group+' / '+f.component)+text(600,380+row*52,f.failed_metrics.join('/'))+text(940,380+row*52,pct(f.failed_metrics.includes('point')?f.point_change:f.spread))+text(1250,380+row*52,(f.failed_metrics.includes('point')?f.difference_kPa:f.spread_kPa).toFixed(6));row++;}
s+=text(65,630,'ฐาน / จุด RH·BASE50·Y0.75·F0.5',28);
s+='<rect x="80" y="680" width="260" height="140" fill="#deebef" stroke="#547d91"/><rect x="340" y="680" width="260" height="140" fill="#bcd8e2" stroke="#547d91"/><circle cx="340" cy="750" r="8" fill="#b55724"/>';
s+=text(110,735,'ชั้น k=3',25)+text(380,735,'ชั้น k=4',25)+text(105,785,'element '+t.elements[0],20)+text(375,785,'element '+t.elements[1],20);
s+=text(665,725,`Δσnn = ${t.jump_kPa.toFixed(6)} kPa`,28)+text(665,770,`เทียบตัวหารอย่างน้อย10kPa = ${pct(t.value)}`,24)+text(80,865,'ภาพขยายเชิงสัญลักษณ์ ไม่ใช่รอยต่อคอนกรีตจริง / ไม่ใช่มาตราส่วน',23);
s+=text(65,930,'ข้อค้นพบและสิ่งที่ยังสรุปไม่ได้',28);
findings.forEach((v,i)=>s+=text(65,980+45*i,v,22));
s+=text(65,1210,'ทิศของความต่างไม่พิสูจน์สาเหตุ: ต้องแยกทดสอบ wall-profile / Y / thickness',24);
s+=text(65,1260,'คงพิกัด490จุดและเกณฑ์5%เดิม ไม่ตัดจุดที่ไม่ผ่าน ไม่smoothข้ามหน้า',24);
s+=text(65,1330,'ผ่านครบยัง1/4กลุ่ม · whole-model local convergence: NOT_ESTABLISHED',25,'#9c4f0c');
s+=text(65,1380,'FULL gravity / NC320 trial / t175 / F-R / bonded crown; ไม่ใช่แบบผลิต',23);
const id='TS-C-DIRECTIONAL-QA-S2N-R00';const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1430"><rect width="1600" height="1430" fill="#f4f6f8"/><g font-family="Tahoma,Arial,sans-serif">${s}</g></svg>`;
await writeFile(`${out}/${id}.svg`,svg);await sharp(Buffer.from(svg)).png().toFile(`${out}/${id}.png`);
const deps={...r.dependency_hashes};for(const p of [out+'/directional_results.json','tools/tsc-study/render_directional.mjs'])deps[p]=createHash('sha256').update(await readFile(p)).digest('hex');
await writeFile(out+'/web_summary.json',JSON.stringify({id:r.id,revision:r.revision,status:r.status,findings,dependency_hashes:deps,raw_output_hashes:r.raw_output_hashes,drawings:[{id,title:'Step 2N · แยกทิศความต่างของความเค้น',file:id+'.png'}],engineering_approval:false,manufacturing_release:false}));
