const fs=require('fs'),path=require('path'),http=require('http'),{spawn}=require('child_process');
const {chromium}=require('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const ROOT=path.resolve(__dirname,'../..'),OUT=path.join(ROOT,'deliverables/PPE_Senior_Home/video');
const ffmpeg=path.join(__dirname,'video-python/imageio_ffmpeg/binaries/ffmpeg-win-x86_64-v7.1.exe');
const worker=Number(process.argv[3]||0),port=8767+worker;
const server=http.createServer((req,res)=>{let p=path.join(ROOT,decodeURIComponent(req.url.split('?')[0]));if(!p.startsWith(ROOT)){res.writeHead(403);res.end();return;}fs.readFile(p,(err,b)=>{if(err){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.html')?'text/html; charset=utf-8':'application/json');res.end(b);});});
(async()=>{await new Promise(r=>server.listen(port,'127.0.0.1',r));let browser=await chromium.launch({headless:true,args:['--enable-unsafe-swiftshader','--disable-dev-shm-usage']});let page=await browser.newPage({viewport:{width:1280,height:720},deviceScaleFactor:1.5});page.on('pageerror',e=>console.error(e));await page.goto('http://127.0.0.1:'+port+'/tools/senior-home/video-render.html');await page.waitForFunction(()=>window.ready,{timeout:60000});
let mode=process.argv[2]||'preview';if(mode==='preview'){for(let t of [5,14,23,32,40,48,55,61,66,70,76,83,96,111,119,125,134,140,149]){let meta=await page.evaluate(t=>window.frame(t),t);await page.screenshot({path:path.join(OUT,'preview-'+t+'.png')});console.log(t,meta);}fs.writeFileSync(path.join(OUT,'shots.json'),JSON.stringify(await page.evaluate(()=>window.shots),null,2));}
else{const fps=24,total=mode==='bench'?48:154*fps,start=mode==='worker'?worker*924:0,end=mode==='worker'?(worker+1)*924:total;let enc=spawn(ffmpeg,['-y','-hide_banner','-loglevel','warning','-f','image2pipe','-vcodec','mjpeg','-framerate',String(fps),'-i','pipe:0','-an','-c:v','libx264','-threads','2','-preset','fast','-crf','19','-pix_fmt','yuv420p','-movflags','+faststart',path.join(OUT,mode==='worker'?(process.argv[4]||'part-'+worker+'.mp4'):'PPE_Senior_Home_Tour_and_Construction.mp4')],{windowsHide:true});enc.stderr.on('data',b=>process.stderr.write(b));let done=new Promise((r,j)=>enc.on('close',c=>c===0?r():j(Error('ffmpeg '+c))));for(let i=start;i<end;i++){let b=Buffer.from(await page.evaluate(t=>window.capture(t),i/fps),'base64');if(!enc.stdin.write(b))await new Promise(r=>enc.stdin.once('drain',r));if(i%120===0){console.log('FRAME',i,'/',total);fs.writeFileSync(path.join(OUT,'render-progress-'+worker+'.json'),JSON.stringify({frame:i,total,timeSeconds:i/fps}));}}enc.stdin.end();await done;console.log('DONE');}
await browser.close();server.close();})().catch(e=>{console.error(e);process.exit(1)});
