import {useState} from 'react';
import {DownloadButton} from './Downloads';
import type {CurvedStudy} from './model';
const fmt=(n:number|undefined,d=3)=>n===undefined?'—':Math.abs(n)<1e-7?'≈0':Math.abs(n)<.001?n.toExponential(2):n.toFixed(d),pct=(n:number|undefined)=>n===undefined?'—':fmt(n*100)+'%';
const fields=['σtt','σrr','σyy','τrt','τry','τty'];
export function CurvedStudyView({study}:{study:CurvedStudy}){
  const [t,setT]=useState(.175),[model,setModel]=useState('H20-CURVED');
  const runs=study.runs.filter(r=>r.t_m===t&&r.nu===.2),selected=runs.find(r=>r.model===model&&r.mesh==='G3');
  const profile=study.profiles.find(p=>p.t_m===t&&p.model===model&&p.nu===.2);
  return <section className="cat-detail">
    <div className="cat-detail-heading"><div><span className="cat-eyebrow">STEP 2G / CURVED COUPON</span><h1>ตรวจ 20-node กับมุมโค้ง</h1><p>R ภายนอก 0.40 ม. / มุม 90° / กว้าง 1.50 ม. · {study.revision}</p></div><span className="cat-badge">ผ่านเฉพาะ coupon ที่ตรวจ</span></div>
    {study.status==='STALE'&&<p role="alert" className="cat-notice legacy">ข้อมูลต้นทางเปลี่ยน — ผล Step 2G เป็น STALE ต้องสร้างใหม่</p>}
    <p className="cat-notice legacy">ยังไม่ใช่ TS-C เต็มโมดูล: ไม่มีน้ำหนักตัว ช่องเปิด รอยต่อจริง หรือร้าว; Uy=0 เป็น plane strain ไม่ใช่ขอบข้างอิสระ และยังไม่เลือกความหนาผลิต</p>
    <div className="cat-tools"><label>ความหนาศึกษา<select aria-label="ความหนาชิ้นโค้ง" value={t} onChange={e=>setT(Number(e.target.value))}>{[.15,.175,.2].map(v=><option key={v} value={v}>{v*1000} มม.</option>)}</select></label><label>รายละเอียด G3<select aria-label="แบบจำลองชิ้นโค้ง" value={model} onChange={e=>setModel(e.target.value)}>{['H8-CHORD','H20-CHORD','H20-CURVED'].map(v=><option key={v}>{v}</option>)}</select></label></div>
    <p className="cat-note">H8-CHORD: 8-node/คอร์ดตรง · H20-CHORD: 20-node/geometryคอร์ดเดิม · H20-CURVED: 20-node/midsideบนวงกลม เป็น quadratic approximation ไม่ใช่วงกลม exact · จำนวน DOF ต่างกัน</p>
    <p>โมเมนต์ทดสอบ m=1 kNm/m → My ปลาย −1.50 kNm / reaction +1.50 kNm; θ=0 มี Uz=0 และ Ux datum หนึ่งจุด ไม่ใช่ rigid clamp · กรณีหลัก ν=.20 และมี ν=0 control เพิ่ม 3 กรณี รวม 30 กรณี</p>
    <div className="cat-table-scroll"><table className="cat-table"><caption>t{t*1000} / ν=.20 · ค่าความคลาดเคลื่อนเทียบ exact elasticity</caption><thead><tr><th>Model / mesh</th><th>Elements / nodes</th><th>Energy error</th><th>Displacement error</th><th>Max point error*</th><th>One-sided spread*</th><th>เกณฑ์ครบ</th></tr></thead><tbody>{runs.map(r=><tr key={r.id}><th>{r.model} / {r.mesh}</th><td>{r.elements} / {r.nodes}</td><td>{pct(r.energy_error_relative)}</td><td>{pct(r.sample_displacement_error_relative)}</td><td>{pct(Math.max(...r.fixed_max_point_relative))}</td><td>{pct(Math.max(...r.fixed_spread_relative))}</td><td>{r.accuracy_targets_met?'เฉพาะ coupon นี้':'ยังไม่ครบ'}</td></tr>)}</tbody></table></div>
    <p className="cat-note">*มากสุดใน6องค์ประกอบ/45พิกัด; point/spread หาร max(|exact|,10kPa) · displacement ใช้ max vector error / max exact vector ที่จุดตรวจ · ไม่ใช่ capacity ratio หรือ peak ทั้งโมเดล</p>
    {selected&&<><h2>{model} / t{t*1000} / G3 · 6 องค์ประกอบ</h2><div className="cat-table-scroll"><table className="cat-table"><caption>Gauss RMS และพิกัดร่วมต้องตรวจพร้อมกัน ไม่สรุปจากค่าพลังงานอย่างเดียว</caption><thead><tr><th>Stress</th><th>RMS error (kPa)</th><th>Gauss RMS %</th><th>Fixed RMS %</th><th>Max point %</th><th>Spread %</th></tr></thead><tbody>{fields.map((f,i)=><tr key={f}><th>{f}</th><td>{fmt(selected.gauss_rms_error_kPa[i])}</td><td>{pct(selected.gauss_rms_relative[i])}</td><td>{pct(selected.fixed_rms_relative[i])}</td><td>{pct(selected.fixed_max_point_relative[i])}</td><td>{pct(selected.fixed_spread_relative[i])}</td></tr>)}</tbody></table></div><p className="cat-note">ปริมาตร error {pct(selected.volume_error_relative)} · radial geometry error ที่สุ่มตรวจ {fmt(selected.sampled_radial_geometry_error_mm,6)} มม. ไม่ใช่ tolerance ที่กำหนดให้โรงงาน</p></>}
    {profile&&<><h2>Profile G3 / θ45° / Y=.75 ม. / {model}</h2><div className="cat-table-scroll"><table className="cat-table"><caption>หน่วย kPa · f วัดจากผิวใน/t · ไม่มี surface extrapolation</caption><thead><tr><th>f</th><th>σtt / exact</th><th>σrr / exact</th><th>τrt mean</th><th>τrt ช่วงด้านติดกัน</th></tr></thead><tbody>{profile.points.map(p=><tr key={p.fraction}><th>{p.fraction.toFixed(2)}</th><td>{fmt(p.mean_kPa[0])} / {fmt(p.exact_kPa[0])}</td><td>{fmt(p.mean_kPa[1])} / {fmt(p.exact_kPa[1])}</td><td>{fmt(p.mean_kPa[3])}</td><td>{fmt(p.min_kPa[3])} ถึง {fmt(p.max_kPa[3])}</td></tr>)}</tbody></table></div></>}
    <details><summary>G2 → G3 และ ν=0 control</summary>{study.comparisons.map(c=><p key={`${c.model}/${c.t_m}/${c.nu}`}>{c.model} / t{c.t_m*1000} / ν={c.nu} · Δ energy {pct(c.energy_change)} · {c.all_targets_met?'ครบเฉพาะ coupon ที่ตรวจ':'ยังไม่ครบ'}</p>)}</details>
    <p className="cat-notice legacy">ขั้นถัดไป: TS-C quadratic-solid bay revision ใหม่ พร้อม gravity/free-side/support/crown checks สถานะโมดูลเดิมยัง NOT_ESTABLISHED ด้าน local-stress convergence ไม่เปิดการออกแบบผลิตอัตโนมัติ</p>
    <details><summary>แหล่งอ้างอิง</summary>{study.basis.sources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a></p>)}</details>
    <h2>ภาพดาวน์โหลด · ตัวอย่างคงที่ t175 / ν=.20</h2>{study.drawings.map(d=><section className="cat-study-drawing" key={d.id}><div className="cat-status-heading"><h3>{d.title}</h3><DownloadButton artifact={d.artifact}/></div><a className="cat-full-board" href={d.artifact.url} target="_blank" rel="noreferrer"><img src={d.artifact.url} alt={d.title} loading="lazy"/></a></section>)}
  </section>;
}
