import { useState } from 'react';
import { families, uses, type CatalogueData, type Product, type Recipe, type Typical } from './model';

export function Warning({ legacy = false }: { legacy?: boolean }) {
  return <aside className={`cat-notice ${legacy ? 'legacy' : ''}`}>
    <strong>{legacy ? 'LEGACY20 / NOT STD15 GEOMETRY' : 'CONCEPT / ยังไม่ใช่แบบก่อสร้าง'}</strong>
    <p>{legacy ? 'ภาพ Type I เดิมแบ่งช่วง 2.00 ม. เก็บไว้เป็นประวัติ เป้าหมายใหม่ช่วง 1.50 ม. ยังไม่มีภาพหรือ CAD มาตรฐาน ห้ามใช้จำนวนชิ้นในภาพนี้เป็นบัญชี STD15' : 'ภาพแนวคิด R00 อาจมีความคลาดเคลื่อนของมิติ รูปตัด และแนวรอยต่อ ต้องจัดทำ CAD ให้สอดคล้องก่อนนำไปวิเคราะห์หรือผลิต'}</p>
  </aside>;
}

export function RecipeTable({ recipe }: { recipe: Recipe }) {
  const rows = [['ช่วงตรง 1.50 ม.', recipe.straight_bays], ['ซีกผนัง–หลังคา H15', recipe.half_shells], ['พื้น F15 รวมพื้นโหนด', recipe.floors_total], ['N90 (ชุดมุม ไม่ใช่ชิ้นหล่อ)', recipe.N90_kits], ['หลังคาโหนด NR15', recipe.NR15], ['ผนังโหนด NW15', recipe.NW15], ['ชุดเปลี่ยนหน้าตัด TR', recipe.TR_kits]];
  return <><table className="cat-table"><caption>สูตรแบ่งแผงตั้งต้น STD15 · ไม่ใช่ BOM ผลิตครบชุด</caption><thead><tr><th scope="col">รายการ</th><th scope="col">จำนวน</th></tr></thead><tbody>{rows.map(([name, count]) => <tr key={name}><th scope="row">{name}</th><td>{count}</td></tr>)}</tbody></table><p className="cat-note">พื้นโหนดรวมใน F15 แล้ว ไม่บวกซ้ำ จำนวนนี้ยังไม่รวมกรอบ/คานขอบ ฐาน อุปกรณ์ยึด และชิ้นปิดปลายที่ยังต้องออกแบบ</p></>;
}

export function SegmentTable({ typical }: { typical: Typical }) {
  return <><div className="cat-table-scroll"><table className="cat-table"><caption>ทะเบียนชนิดชิ้นส่วน {typical.id} + ชิ้นร่วม X / R00</caption><thead><tr><th scope="col">Segment tag</th><th scope="col">ช่องเปิด</th><th scope="col">แม่แบบที่เสนอ</th></tr></thead><tbody>{typical.segments.map(s => <tr key={s.tag}><th scope="row"><code>{s.tag}</code><small>{s.kind}{s.hand ? ` · ${s.hand}` : ''}</small></th><td>{typical.openings.find(o => o.code === s.opening)?.name_th ?? '—'}</td><td><code>{s.mold_candidate ?? 'ยังไม่กำหนด'}</code></td></tr>)}</tbody></table></div><p className="cat-note">Tag เป็นข้อเสนอจัดหมวด R00 แม่แบบเดียวกันไม่ได้หมายความว่าใช้เหล็กหรือผลอนุมัติเดียวกัน ความหนา น้ำหนัก และแบบผลิตยังไม่กำหนด</p></>;
}

const tabs = [{ id: 'overview', title: 'ภาพรวม' }, { id: 'drawings', title: 'ภาพ / รูปแบบ' }, { id: 'segments', title: 'Segments' }, { id: 'engineering', title: 'วิศวกรรม' }, { id: 'fabrication', title: 'แบบผลิต' }, { id: 'bim', title: 'BIM' }, { id: 'history', title: 'ประวัติ' }];

export function ProductDetail({ product: p, data, onCompare, onTypical }: { product: Product; data: CatalogueData; onCompare: () => void; onTypical: () => void }) {
  const [tab, setTab] = useState('overview');
  return <section className="cat-detail">
    <div className="cat-detail-heading"><div><span className="cat-eyebrow">{p.product_id} / CONCEPT R00</span><h1>{p.display_code} <span>{uses.find(u => u.id === p.use)?.th}</span></h1><p>{families[p.family].th} · แปลน {p.type} · พื้นที่ตามกรอบ {p.nominal_grid_area_m2} ตร.ม.</p></div><button className="cat-primary" onClick={onCompare}>เปรียบเทียบ I / L / U</button></div>
    <Warning legacy={p.type === 'I'}/>
    <nav className="cat-tabs" aria-label="ข้อมูลแบบ">{tabs.map(t => <button key={t.id} aria-pressed={tab === t.id} onClick={() => setTab(t.id)}>{t.title}</button>)}</nav>
    {tab === 'overview' && <div className="cat-overview"><div><a href={p.artifact.url} target="_blank" rel="noreferrer" className="cat-full-board"><img src={p.artifact.url} alt={`ภาพแนวคิดรวม ${p.display_code}`}/></a><a className="cat-text-link" href={p.artifact.url} target="_blank" rel="noreferrer">ดูภาพเต็มความละเอียด ↗</a></div><div className="cat-facts"><h2>ข้อมูลที่ยืนยันในแผน</h2><dl><dt>ช่วงผลิตเป้าหมาย</dt><dd>1.50 ม. / STD15</dd><dt>Typical อ้างอิง</dt><dd><button className="cat-text-button" onClick={onTypical}>{p.typical_family} →</button></dd><dt>ความหนาเป้าหมาย</dt><dd>150–200 มม. <small>ยังไม่เลือก / ปรับรายชิ้นได้ตามผลคำนวณ</small></dd><dt>พื้นที่ตามกรอบโมดูล</dt><dd>{p.nominal_grid_area_m2} ตร.ม. <small>ไม่ใช่พื้นที่สุทธิ และไม่รวมคอร์ต</small></dd><dt>สถานะทางวิศวกรรม</dt><dd>NOT_ANALYSED</dd><dt>อนุมัติผลิต</dt><dd>ยังไม่อนุมัติ</dd></dl></div></div>}
    {tab === 'drawings' && <section><h2>บอร์ดแนวคิด R00</h2><p>รวมภาพ 3D แปลน รูปด้าน รูปตัด และการประกอบในบอร์ดเดิม แสดงครบทั้งแผ่นโดยไม่ตัดขอบ</p><a href={p.artifact.url} target="_blank" rel="noreferrer" className="cat-full-board"><img src={p.artifact.url} alt={`บอร์ดภาพแนวคิด แปลน รูปด้าน รูปตัด ${p.display_code}`}/></a><p className="cat-note">แบบ CAD แยกแผ่น: NOT_CREATED · ภาพนี้ไม่ใช่แหล่งมิติหรือผลการวิเคราะห์</p></section>}
    {tab === 'segments' && <div className="cat-two-column"><section><h2>การแบ่งชิ้นส่วนเป้าหมาย</h2><RecipeTable recipe={p.recipe}/></section><section className="cat-facts"><h2>{p.typical_family} / คลังร่วม</h2><p>ซีกผนัง–หลังคาซ้าย/ขวา ต่อที่แนวกึ่งกลาง พื้นเป็นโมดูลแยก ช่องเปิดและจุดต่อยังต้องตรวจทางวิศวกรรม</p><button className="cat-primary" onClick={onTypical}>ดู Typical และทะเบียน Tag</button><p className="cat-note">N90 เป็นชุดหลายชิ้น ไม่ใช่ซีก H15 หนึ่งชิ้น ยังไม่รับรองการสลับใช้ระหว่างแบบ</p></section></div>}
    {tab === 'engineering' && <section><div className="cat-status-heading"><h2>ผล FEM และการออกแบบ</h2><span className="cat-badge">NOT_STARTED</span></div><p>ยังไม่มีผลแรงภายใน shell ความหนาที่คำนวณแล้ว หรือแบบจุดต่ออนุมัติ</p><div className="cat-two-column"><div className="cat-facts"><h3>ข้อมูลตั้งต้นที่รอทบทวน</h3><dl><dt>Roof LL ที่ผู้ใช้ขอ</dt><dd>{data.engineering.loads.roof_LL.user_value} kgf/m² ≈ {data.engineering.loads.roof_LL.si_kN_m2.toFixed(4)} kN/m²</dd><dt>Floor LL ที่ผู้ใช้ขอ</dt><dd>{data.engineering.loads.floor_LL.user_value} kgf/m² ≈ {data.engineering.loads.floor_LL.si_kN_m2.toFixed(4)} kN/m²</dd><dt>มาตรฐานที่เลือก</dt><dd>{data.engineering.code}</dd><dt>คอนกรีต</dt><dd>ยังไม่เลือก</dd><dt>กำลัง cylinder ที่เสนอ</dt><dd>{data.engineering.materials.fc_cylinder_candidates_ksc.join(' / ')} ksc</dd><dt>เหล็ก / ลวดที่เสนอ</dt><dd>{data.engineering.materials.reinforcement_candidates.join(' / ')} · ยังไม่เลือก</dd><dt>Prestress</dt><dd>{data.engineering.materials.prestress_decision}</dd></dl></div><div><h3>ต้องมีข้อมูลก่อนเริ่มคำนวณ</h3><ol className="cat-checklist"><li>Geometry, ช่องเปิด และระดับที่แน่นอน</li><li>วัสดุ ความหนาแน่น และ stiffness</li><li>Joint, support และเงื่อนไขการยึดรั้ง</li><li>โหลด พื้นที่รับแรง และ load combinations</li><li>FBD / reactions → shell forces → ตรวจสมดุลและ mesh</li></ol><p className="cat-note">ตีความหน่วยแรงเดิม kg/m² เป็น kgf/m² เพื่อบันทึกเท่านั้น ยังต้องทบทวนตามการใช้งานและมาตรฐาน ไม่ใช่การรับรองว่าโหลดนี้ใช้ได้ทุกกลุ่มหรือโมดูลปลอดภัย</p></div></div></section>}
    {tab === 'fabrication' && <section className="cat-pending"><span className="cat-eyebrow">STEP 4 / NOT_STARTED</span><h2>แบบหล่อและแบบประกอบยังไม่เริ่ม</h2><p>รอ geometry, ความหนา เหล็ก และจุดต่อฉบับตรวจแล้ว ก่อนจัดทำ Mould / Shop / Erection drawings</p><p>ไม่มีไฟล์อนุมัติผลิตหรือจุดยกที่รับรองในคลังนี้</p></section>}
    {tab === 'bim' && <section className="cat-pending"><span className="cat-eyebrow">STEP 5 / NOT_STARTED</span><h2>Revit สำหรับรายการนี้ยังไม่จัดทำ</h2><p>จะเชื่อม Family / Assembly / Schedule ตาม Tag และ revision ที่ตรวจแล้ว ไม่ดึงโมเดลโครงการอื่นมาอ้างว่าเป็นแบบนี้</p></section>}
    {tab === 'history' && <section><h2>ประวัติและแหล่งอ้างอิง</h2><ol className="cat-history"><li><strong>R00 / ภาพต้นฉบับ</strong><p>{p.type === 'I' ? 'LEGACY20 · ช่วง 2.00 ม. · 6 H20 + 3 F20 คงภาพและข้อมูลเดิม' : 'แนวคิด L/U บนฐานช่วง 1.50 ม. ต้องตรวจความสอดคล้องกับ CAD'}</p></li><li><strong>R01 / แผนที่ผู้ใช้เห็นชอบ</strong><p>มาตรฐานเป้าหมาย 1.50 ม. ร่วมกันทั้ง I/L/U โดยไม่แก้ภาพ R00 ย้อนหลัง</p></li><li><strong>{data.revision} / คลังแบบอ่านอย่างเดียว</strong><p>นำทะเบียนมาแสดงโดยไม่เปลี่ยนสถานะทางวิศวกรรมหรืออนุมัติผลิต</p></li></ol><dl className="cat-source"><dt>Artifact</dt><dd>{p.artifact.id}</dd><dt>SHA-256 ของภาพ</dt><dd><code>{p.artifact.source_hash}</code></dd><dt>SHA-256 ของทะเบียน R01</dt><dd><code>{data.source_hash}</code></dd><dt>แหล่งข้อมูล</dt><dd>product_matrix.json / baseline.json (R01), catalog.json / IMAGE_QA.md (R00)</dd></dl></section>}
  </section>;
}

export function TypicalDetail({ typical: t }: { typical: Typical }) {
  return <section className="cat-detail"><div className="cat-detail-heading"><div><span className="cat-eyebrow">STANDARD SEGMENT LIBRARY</span><h1>{t.id} <span>{families[t.family].th}</span></h1><p>คลังอ้างอิงร่วมสำหรับออฟฟิศ บ้านพัก ร้านกาแฟ และรีสอร์ต</p></div>{t.pilot && <span className="cat-badge">PILOT / ชุดนำร่องที่เห็นชอบ</span>}</div><Warning/><div className="cat-overview"><a href={t.artifact.url} target="_blank" rel="noreferrer" className="cat-full-board"><img src={t.artifact.url} alt={`บอร์ด Typical segment ${t.id}`}/><span>เปิดภาพเต็มความละเอียด ↗</span></a><div className="cat-facts"><h2>หลักการมาตรฐาน</h2><dl><dt>Profile tag</dt><dd>{t.profile.tag}</dd><dt>ความกว้าง / สูงภายนอกแนวคิด</dt><dd>{t.profile.base_width_mm / 1000} / {t.profile.total_external_height_mm / 1000} ม.</dd><dt>ช่วงเป้าหมาย</dt><dd>1.50 ม.</dd><dt>การแบ่งซีก</dt><dd>LH / RH · รอยต่อกลางหลังคา</dd><dt>พื้น</dt><dd>F15 · แยกจากซีกผนัง–หลังคา</dd><dt>ความหนา / จุดต่อ / เหล็ก</dt><dd>ยังไม่ออกแบบ</dd></dl><p className="cat-note">ขนาดเป็นข้อเสนอจาก R00 ไม่ใช่ geometry ที่ตรวจทางวิศวกรรมแล้ว</p></div></div><h2>Typical Segment register</h2><SegmentTable typical={t}/></section>;
}

export function Compare({ selected, data, onSelect }: { selected: Product; data: CatalogueData; onSelect: (p: Product) => void }) {
  const list = data.products.filter(p => p.family === selected.family && p.use === selected.use).sort((a, b) => a.type.localeCompare(b.type));
  return <section className="cat-detail"><div className="cat-detail-heading"><div><span className="cat-eyebrow">SAME FAMILY / THREE PLANS</span><h1>เปรียบเทียบ I / L / U</h1><p>{uses.find(u => u.id === selected.use)?.th} · {families[selected.family].th} · อ้างอิง {selected.typical_family} ร่วมกัน</p></div></div><div className="cat-compare-grid">{list.map(p => <article key={p.product_id}><h2>{p.display_code} <small>{p.nominal_grid_area_m2} ตร.ม.</small></h2><a href={p.artifact.url} target="_blank" rel="noreferrer" className="cat-full-board"><img src={p.artifact.url} alt={`เปรียบเทียบ ${p.display_code}`}/></a><Warning legacy={p.type === 'I'}/><RecipeTable recipe={p.recipe}/><button className="cat-primary" onClick={() => onSelect(p)}>รายละเอียด {p.display_code}</button></article>)}</div><p className="cat-note">พื้นที่ทั้งหมดเป็นพื้นที่ตามกรอบประสานภายนอก ไม่ใช่พื้นที่สุทธิ น้ำหนัก ราคา และความสามารถรับแรงยังไม่มีผลคำนวณสำหรับเปรียบเทียบ</p></section>;
}
