import {useState} from 'react';import {DownloadButton} from './Downloads';import type {GravityCouponStudy} from './model';
const f=(v:number|undefined,d=5)=>v===undefined?'—':Math.abs(v)<1e-9?'≈0':v.toFixed(d),pct=(v:number|undefined)=>v===undefined?'—':f(v*100,3)+'%';
export function GravityCouponStudyView({study}:{study:GravityCouponStudy}){
  const [nu,setNu]=useState(.2),[mesh,setMesh]=useState('J7'),[cutId,setCutId]=useState('X+0.00L');
  const runs=study.runs.filter(r=>r.nu===nu),run=runs.find(r=>r.mesh===mesh)??runs.at(-1),cuts=study.runs.flatMap(r=>r.cuts),cut=run?.cuts.find(c=>c.id===cutId);
  return <section className="cat-detail">
    <div className="cat-detail-heading"><div><span className="cat-eyebrow">STEP 2J / EXACT GRAVITY COUPON</span><h1>โจทย์อ้างอิงแรงเฉือนจากน้ำหนักตัว</h1><p>ชิ้นตรง 1.50 × 0.25 × 0.175 ม. / 20-node / {study.revision}</p></div><span className="cat-badge">ตรวจวิธีคำนวณ ไม่ใช่แบบอาคาร</span></div>
    {study.status==='STALE'&&<p className="cat-notice legacy" role="alert">ข้อมูลต้นทางเปลี่ยน — ผล Step 2J เป็น STALE ต้องสร้างใหม่</p>}
    <p className="cat-notice legacy">เป็น plane-strain coupon: Uy=0 ทุก node ไม่ใช่โมดูล TS-C ที่ขอบ Y อิสระ ผลที่ผ่านใช้ได้เฉพาะโจทย์อ้างอิงนี้ ไม่เปลี่ยนผลที่ยังไม่ผ่านใน Step 2I และยังไม่อนุมัติความหนา เหล็ก หรือจุดต่อผลิต</p>
    <p>ใช้ body force จากน้ำหนักตัวและ exact end traction ที่คำนวณจากสูตรพหุนาม ไม่มี Roof LL · ปลายมีแรงเฉือนพาราโบลาและแรงตั้งฉากแบบ self-equilibrated ไม่ใช่รายละเอียด bearing จริง จุดยึด datum ใช้ตัด rigid modes เท่านั้น</p>
    <p className="cat-note">ตรวจสูตรด้วย displacement gradient, Hooke law, div(σ)+b=0, ผิวบน/ล่างปลอด traction และแรงหน้าตัดเชิงวิเคราะห์ แล้วใช้ฟังก์ชันรวม traction เดิมของ Step 2I โดยไม่แก้ ไม่ใช่สูตรออกแบบตาม วสท.</p>
    <div className="cat-tools"><label>Poisson ratio<select aria-label="ค่า nu ของ gravity coupon" value={nu} onChange={e=>{setNu(Number(e.target.value));setMesh('J7');}}><option value="0.2">ν=.20 · วัสดุทดลองเดิม</option><option value="0">ν=0 · ชุดควบคุม ไม่ใช่การเลือกวัสดุ</option></select></label></div>
    <div className="cat-table-scroll"><table className="cat-table"><caption>Gravity coupon / ν={nu.toFixed(2)} / error เทียบคำตอบอ้างอิง</caption><thead><tr><th>Mesh nx×ny×nz</th><th>Elements</th><th>Δu error</th><th>Energy error</th><th>τxz RMS</th><th>Cut ครบเกณฑ์</th><th>ครบทั้งชุด</th></tr></thead><tbody>{runs.map(r=><tr key={r.id}><th>{r.mesh} · {r.nx}×{r.ny}×{r.nz}</th><td>{r.elements.toLocaleString()}</td><td>{pct(r.displacement_error_relative)}</td><td>{pct(r.energy_error_relative)}</td><td>{pct(r.stress_rms_relative[5])}</td><td>{r.cuts.filter(c=>c.targets_met).length}/3</td><td>{r.accuracy_targets_met?'เฉพาะ coupon นี้':'ยังไม่ครบ'}</td></tr>)}</tbody></table></div>
    <p>รวม {study.runs.length} runs: coupon accuracy ครบ {study.runs.filter(r=>r.accuracy_targets_met).length}/{study.runs.length}; แรงหน้าตัดครบ {cuts.filter(c=>c.targets_met).length}/{cuts.length} cuts × 2 traces</p>
    <p className="cat-note">เกณฑ์: displacement/energy ≤2%, stress RMS ทั้ง6องค์ประกอบ ≤5%, traction/exact, traction/nodal และคู่ trace ≤5%, quadrature 4×4→6×6 ≤10⁻⁶ relative · stress floor10kPa / force floor.1kN / moment floor.1kN·m ไม่ใช่อัตราการใช้กำลัง</p>
    {run&&<><h2>รายละเอียดที่คำนวณจริง</h2><div className="cat-tools"><label>Mesh<select aria-label="mesh gravity coupon" value={run.mesh} onChange={e=>setMesh(e.target.value)}>{runs.map(r=><option key={r.id}>{r.mesh}</option>)}</select></label><label>แนวตัด<select aria-label="แนวตัด gravity coupon" value={cutId} onChange={e=>setCutId(e.target.value)}>{run.cuts.map(c=><option key={c.id}>{c.id}</option>)}</select></label></div>
      <p>กึ่งกลาง Uz = {f(run.mid_uz_mm,7)} มม.; exact = {f(run.exact_mid_uz_mm,7)} มม. · ไม่ใช่การตรวจ serviceability อาคาร</p>
      <div className="cat-table-scroll"><table className="cat-table"><caption>ความเค้นทุก Gauss point / {run.id} · tension positive</caption><thead><tr><th>Stress</th><th>RMS error (kPa)</th><th>Normalized RMS</th></tr></thead><tbody>{['xx','yy','zz','xy','yz','zx'].map((s,k)=><tr key={s}><th>σ/τ {s}</th><td>{f(run.stress_rms_error_kPa[k])}</td><td>{pct(run.stress_rms_relative[k])}</td></tr>)}</tbody></table></div>
    </>}
    {run&&cut&&<><h3>Cut · {run.id} / {cut.id}</h3><p>Origin XYZ [{cut.origin_m.map(v=>f(v)).join(', ')}] ม. · {cut.targets_met?'ครบเฉพาะเกณฑ์แนวตัดนี้':'ยังไม่ครบเกณฑ์แนวตัดนี้'}</p>
      <div className="cat-table-scroll"><table className="cat-table"><caption>แรง kN / โมเมนต์ kN·m; lower=ฝั่งซ้าย +X normal, upper=ฝั่งขวา −X normal</caption><thead><tr><th>Component</th><th>Exact lower</th><th>Nodal lower</th><th>Traction lower</th><th>Traction upper</th><th>ผลรวม2traces</th><th>Pair error</th></tr></thead><tbody>{['Fx','Fy','Fz','Mx','My','Mz'].map((s,k)=><tr key={s}><th>{s}</th><td>{f(cut.exact_lower_6[k],7)}</td><td>{f(cut.nodal_lower_6[k],7)}</td><td>{f(cut.traces.lower.order6.resultant_6[k],7)}</td><td>{f(cut.traces.upper.order6.resultant_6[k],7)}</td><td>{f(cut.trace_pair_sum_6[k],7)}</td><td>{pct(cut.trace_pair_relative_6[k])}</td></tr>)}</tbody></table></div>
      <p className="cat-note">ที่ X=0 คำตอบแรงเฉือนรวมคือศูนย์ ต้องอ่าน absolute kN คู่กับเปอร์เซ็นต์ ไม่เฉลี่ยสองฝั่งให้ได้ศูนย์แล้วอ้างว่าผ่าน</p>
    </>}
    <p className="cat-notice legacy">หลักฐานเฉพาะ coupon: เพิ่ม nx ช่วยแรงผ่านหน้าตัด แต่เพิ่ม nx อย่างเดียวที่ nz=2 ยังไม่ทำให้ความเค้นเฉือนครบเกณฑ์ ต้องตรวจความหนาด้วย ยังไม่พิสูจน์ว่าความคลาดเคลื่อนทุกจุดของ TS-C มาจากสาเหตุเดียวกัน</p>
    <h2>ภาพดาวน์โหลด · บอร์ดหลัก ν=.20 คงที่ ไม่เปลี่ยนตามตัวเลือก</h2>{study.drawings.map(d=><section className="cat-study-drawing" key={d.id}><div className="cat-status-heading"><h3>{d.title}</h3><DownloadButton artifact={d.artifact}/></div><a className="cat-full-board" href={d.artifact.url} target="_blank" rel="noreferrer"><img src={d.artifact.url} alt={d.title} loading="lazy"/></a></section>)}
    <details><summary>แหล่งอ้างอิงวิธีอ่านผล</summary>{study.basis.sources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a></p>)}</details>
  </section>;
}
