import {useState} from 'react';
import {DownloadButton} from './Downloads';
import type {LocalMeshStudy} from './model';
const f=(v:number|undefined,d=4)=>v===undefined?'—':Math.abs(v)<1e-8?'≈0':v.toFixed(d),pct=(v:number|undefined)=>v===undefined?'—':f(v*100,3)+'%';
const zones:Record<string,string>={regular_interior:'ภายในทั่วไป',side_edge:'ใกล้ขอบด้านข้าง',base_probe:'ใกล้ฐาน 50 มม.',crown_probe:'ใกล้กลางหลังคา 50 มม.'};
const components=['Fx','Fy','Fz','Mx','My','Mz'];
export function LocalMeshStudyView({study}:{study:LocalMeshStudy}){
  const [pair,setPair]=useState('H4/IB'),[zone,setZone]=useState('base_probe'),[auditId,setAuditId]=useState('LOCAL-T175-FR-FULL-IBY'),[cutId,setCutId]=useState('CROWN');
  const local=study.local_comparisons.find(c=>c.pair.join('/')===pair),group=local?.groups.find(g=>g.group===zone),qa=study.global_comparisons.find(c=>c.pair.join('/')===pair);
  const audit=study.traction.runs.find(r=>r.id===auditId)??study.traction.runs[0],cut=audit?.cuts.find(c=>c.id===cutId),cuts=study.traction.runs.flatMap(r=>r.cuts);
  if(!audit)return <p className="cat-state">ยังไม่มีข้อมูลตรวจ traction</p>;
  return <section className="cat-detail">
    <div className="cat-detail-heading"><div><span className="cat-eyebrow">STEP 2I / LOCAL MESH &amp; TRACTION</span><h1>TS-C ความไวของ mesh และแรงผ่านหน้าตัด</h1><p>175 มม. / NC320 trial / 3×3×1.50 ม. / F-R limit · {study.revision}</p></div><span className="cat-badge">ยังไม่ใช้เลือกความหนาหรือจุดต่อ</span></div>
    {study.status==='STALE'&&<p className="cat-notice legacy" role="alert">ข้อมูลต้นทางเปลี่ยน — ผล Step 2I เป็น STALE ต้องสร้างใหม่</p>}
    <p className="cat-notice legacy">เพิ่ม mesh 3 ชุดสำหรับ FULL เท่านั้น ไม่ใช่ลำดับการลู่เข้าครบทุกทิศ และไม่ใช้แทนผล LEFT · ยังไม่รับรอง local-stress convergence ทั้งโมดูล</p>
    <p>คงน้ำหนักตัวทั้งสองซีก + Roof LL 50 kgf/m² ไม่คูณ load factors; พื้นแยก LP-A · ฐาน Ux=Uz=0 ทั้งหน้า และ Uy datum หนึ่งจุดต่อด้าน; crown ต่อเนื่อง ขอบ Y อิสระ ไม่มีการเปลี่ยนสภาพรองรับในรอบนี้</p>
    <div className="cat-table-scroll"><table className="cat-table"><caption>FULL / เพิ่ม mesh เฉพาะทิศทางจาก H4</caption><thead><tr><th>Mesh</th><th>การเพิ่มความละเอียด</th><th>Elements / nodes</th><th>|u|max (มม.)</th><th>Energy (kN·m)</th></tr></thead><tbody>{[study.reference_run,...study.runs].map(r=><tr key={r.id}><th>{r.mesh}</th><td>{{H4:'ฐานอ้างอิงเดิม',IB:'แบ่ง 3 ช่องแรกเหนือฐาน ช่องละ 4',IY:'เพิ่มช่อง Y ใกล้ขอบทั้งสองด้าน',IBY:'รวม IB + IY'}[r.mesh]}</td><td>{r.elements.toLocaleString()} / {r.nodes.toLocaleString()}</td><td>{f(r.max_displacement_mm,6)}</td><td>{f(r.strain_energy_kNm,7)}</td></tr>)}</tbody></table></div>
    <p className="cat-note">ยังแบ่งมุมโค้ง 24 ช่อง และความหนา 6 ชั้นเหมือน H4; structured mesh ไม่มี hanging nodes การแบ่งแนวหนึ่งต่อเนื่องผ่านแถวที่เชื่อมกัน ไม่ใช่ adaptive mesh เฉพาะจุดอิสระ</p>
    <h2>ความไวที่ 490 พิกัดร่วมต่อชุด</h2><div className="cat-tools"><label>คู่เปรียบเทียบ<select aria-label="คู่เปรียบเทียบ mesh เฉพาะบริเวณ" value={pair} onChange={e=>setPair(e.target.value)}>{study.local_comparisons.map(c=><option key={c.pair.join('/')} value={c.pair.join('/')}>{c.pair.join(' → ')}</option>)}</select></label><label>บริเวณ<select aria-label="บริเวณ mesh เฉพาะที่" value={zone} onChange={e=>setZone(e.target.value)}>{Object.entries(zones).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>
    {qa&&<p>ผลรวมในคู่นี้: การเคลื่อนตัวเปลี่ยน {pct(qa.displacement_change)} / แรงฐาน {pct(qa.reaction_change)} / พลังงาน {pct(qa.energy_change)} — ไม่ใช่การตรวจความปลอดภัยตามโค้ด</p>}
    {group&&<><p>{zones[group.group]}: {group.points} จุด · {local?.pair.join(' → ')} · {group.all_six_targets_met?'ครบเฉพาะเกณฑ์ของคู่นี้':'ยังไม่ครบทั้ง 6 องค์ประกอบ'}</p><div className="cat-table-scroll"><table className="cat-table"><caption>point / RMS / one-sided spread ≤5% ทุกช่อง; ตัวหารอย่างน้อย 10 kPa</caption><thead><tr><th>Stress</th><th>Max point</th><th>RMS</th><th>Spread</th><th>Δ จุดคุม (kPa)</th><th>ผล</th></tr></thead><tbody>{group.fields.map(v=><tr key={v.component}><th>σ/τ {v.component}<small>{v.worst_point}</small></th><td>{pct(v.max_point_change)}</td><td>{pct(v.rms_change)}</td><td>{pct(v.max_spread_relative)}</td><td>{f(v.difference_kPa)}</td><td>{v.targets_met?'เฉพาะที่ตรวจ':'ยังไม่ครบ'}</td></tr>)}</tbody></table></div></>}
    <h2>แรงจากความเค้นสองด้านของแนวตัด</h2><p>ตรวจย้อนหลัง 8 runs ของ Step 2H และ 3 runs ใหม่ รวม {cuts.length} cuts × 2 traces · ครบเกณฑ์ทั้งหมด {cuts.filter(c=>c.targets_met).length}/{cuts.length} cuts</p>
    <p className="cat-note">F = ∫σ·n dA, M = ∫(x−origin)×(σ·n) dA · รวมจาก displacement gradient ของ element แต่ละด้าน ไม่เฉลี่ยความเค้นข้ามหน้า และใช้ origin เดียวกับ nodal cut</p>
    <div className="cat-tools"><label>ผลวิเคราะห์<select aria-label="ชุดตรวจ traction" value={audit.id} onChange={e=>setAuditId(e.target.value)}>{study.traction.runs.map(r=><option key={r.id} value={r.id}>{r.pattern} / {r.mesh}{r.mesh.startsWith('I')?' · mesh ใหม่':' · S2H เดิม'}</option>)}</select></label><label>แนวตัด<select aria-label="แนวตัด traction" value={cutId} onChange={e=>setCutId(e.target.value)}>{audit.cuts.map(c=><option key={c.id}>{c.id}</option>)}</select></label></div>
    {cut&&<><h3>Traction · {audit.pattern} / {audit.mesh} / {cut.id}</h3><p>Origin XYZ = [{cut.origin_m.map(v=>f(v)).join(', ')}] ม. · {cut.targets_met?'ครบเฉพาะเกณฑ์แนวตัดนี้':'ยังไม่ครบเกณฑ์แนวตัดนี้'}</p><div className="cat-table-scroll"><table className="cat-table"><caption>ผลรวม 6×6 quadrature; แรง kN / โมเมนต์ kN·m · ไม่ใช่แรงต่อเมตรหรือแรงต่อ bolt</caption><thead><tr><th>Component</th><th>Nodal lower</th><th>Traction lower</th><th>Nodal upper</th><th>Traction upper</th><th>ผลรวม 2 traces</th><th>Pair normalized</th></tr></thead><tbody>{components.map((v,k)=><tr key={v}><th>{v}</th><td>{f(cut.nodal_lower_6[k],6)}</td><td>{f(cut.traces.lower.order6.resultant_6[k],6)}</td><td>{f(cut.nodal_upper_6[k],6)}</td><td>{f(cut.traces.upper.order6.resultant_6[k],6)}</td><td>{f(cut.trace_pair_sum_6[k],6)}</td><td>{pct(cut.trace_pair_relative_6[k])}</td></tr>)}</tbody></table></div>
    <details><summary>ความต่างกับ nodal reference และผล quadrature</summary><div className="cat-table-scroll"><table className="cat-table"><caption>เทียบทั้ง6องค์ประกอบ ไม่ตัดค่าที่ไม่ผ่านออก</caption><thead><tr><th>Component</th><th>Lower vs nodal</th><th>Upper vs nodal</th><th>Lower 4→6</th><th>Upper 4→6</th></tr></thead><tbody>{components.map((v,k)=><tr key={v}><th>{v}</th><td>{pct(cut.traces.lower.relative_vs_nodal_6[k])}</td><td>{pct(cut.traces.upper.relative_vs_nodal_6[k])}</td><td>{cut.traces.lower.quadrature_change_6[k]?.toExponential(2)??'—'}</td><td>{cut.traces.upper.quadrature_change_6[k]?.toExponential(2)??'—'}</td></tr>)}</tbody></table></div></details></>}
    <p className="cat-notice legacy">ตัวหารอย่างน้อย 0.1 kN หรือ 0.1 kN·m — เปอร์เซ็นต์สูงเมื่อแรงใกล้ศูนย์ไม่ใช่อัตราการใช้กำลัง ต้องอ่านค่าแรงจริงด้วย เกณฑ์ trace/reference และคู่ trace ≤5%; quadrature change ≤10⁻⁶ relative</p>
    <p>Affine constant-stress patch ตรวจ normal/area/units/origin แล้ว (ความต่างสูงสุด {study.traction.affine_traction_patch.max_resultant_error.toExponential(2)}) แต่ไม่ใช่คำตอบ exact ของโมดูลรับน้ำหนักตัว การผ่านสมดุล nodal ไม่ยืนยันความเค้นที่ผิวหน้าตัด</p>
    <p className="cat-note">ยังไม่มีการตรวจร้าว รอยต่อ/ฐานจริง ช่องเปิด ลม แรงยก สภาวะประกอบ หรือกำลังตามมาตรฐาน ต้องแยกการเพิ่ม mesh ตาม profile/ความหนากับ support sensitivity ต่อไป ไม่เพิ่มความแข็งสปริงหรือจำนวน bolt โดยสมมติ</p>
    <h2>ภาพดาวน์โหลด · ภาพคงที่ FULL / ไม่เปลี่ยนตามตัวเลือก</h2>{study.drawings.map(d=><section className="cat-study-drawing" key={d.id}><div className="cat-status-heading"><h3>{d.title}</h3><DownloadButton artifact={d.artifact}/></div><a className="cat-full-board" href={d.artifact.url} target="_blank" rel="noreferrer"><img src={d.artifact.url} alt={d.title} loading="lazy"/></a></section>)}
    <details><summary>แหล่งอ้างอิง</summary>{study.basis.sources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a></p>)}</details>
  </section>;
}
