import {useEffect,useState} from 'react';
import {Download,Board,type Artifact} from './CurrentCatalogue';
import {CastingLiftPanel} from './CastingLiftPanel';
import {TableWeldPanel} from './TableWeldPanel';
import {TableBackerPanel} from './TableBackerPanel';
import {TableBasePanel} from './TableBasePanel';
import {CoordinatedMouldPanel} from './CoordinatedMouldPanel';
import {TableSealPanel} from './TableSealPanel';
import {TableChannelPanel} from './TableChannelPanel';
type Setup={id:string;typicalId:string;kind:string;concreteKg:number;dimensionsMm:number[];usedBy:{productId:string;quantity:number}[];files:Artifact[];presentation?:Artifact|null;liftingFiles?:Artifact[];currentLiftingFiles?:Artifact[];tableWeldFiles?:Artifact[];tableChannelFiles?:Artifact[];tableSealFiles?:Artifact[];tableBackerFiles?:Artifact[];tableBaseFiles?:Artifact[];coordinatedFiles?:Artifact[];developmentFiles?:Artifact[];historicalDevelopmentFiles?:Artifact[];closureFile?:Artifact|null;closureReview?:{revision:string;completeP40Design:boolean;next:string;liftingCoordinateReview:string;openDeliverables:number}|null;hardwareStatus?:string;sourceRevision?:string;supplementGroups?:{revision:string;label:string;role:string;files:Artifact[]}[]};
type DeferredWorkstream={id:string;title:string;ownerStage:string};
type Data={status:string;setups:Setup[];archive:Artifact|null;developmentRevision?:string;supplementRevision?:string;scopeClosureRevision?:string;stageCompletionPercent?:number|null;stageComplete?:boolean;stageClosure?:Artifact|null;deferredWorkstreams?:DeferredWorkstream[]};
export function MouldLibrary(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[reload,setReload]=useState(0);
 useEffect(()=>{let alive=true;async function load(){try{const r=await fetch('/api/catalogue/moulds');if(!r.ok)throw Error(r.status===401||r.status===403?'ไม่มีสิทธิ์อ่านแบบแม่แบบ หรือเซสชันหมดอายุ':'โหลดชุดแม่แบบไม่ได้');const d=await r.json() as Data;if(alive){setData(d);setError('');}}catch(e){if(alive){setData(null);setSelected('');setError(e instanceof Error?e.message:'โหลดไม่สำเร็จ');}}}void load();const timer=setInterval(()=>void load(),60000);return()=>{alive=false;clearInterval(timer);};},[reload]);
 const current=data?.setups.find(s=>s.id===selected),rows=data?.setups.filter(s=>`${s.id} ${s.typicalId} ${s.kind} ${s.usedBy.map(p=>p.productId).join(' ')}`.toLowerCase().includes(query.toLowerCase().trim()))??[];
 return <section><div className="cat-eyebrow">STAGE 5 / 8 · {data?.scopeClosureRevision??'P100'} · {data?.stageComplete?'100% PLANNING SCOPE COMPLETE':'IN REVIEW'}</div><h1>แม่แบบฉบับวางแผน</h1><div className="cat-notice legacy"><strong>44 setup ไม่ใช่จำนวนแม่แบบที่สั่งผลิต</strong><p>ภาพนำเสนอ P43 คงเดิมเพื่ออ้างอิงรูปแบบ ส่วนโมเดลและผลตรวจรุ่นใหม่อยู่ด้านล่างในข้อมูลพัฒนา ภาพ AI ไม่ใช่แบบผลิต มิติและรายละเอียดให้ยึดโมเดลต้นทางที่ระบุ revision ไม่ใช้ภาพนี้สั่งผลิต เท หรือยก</p></div>{error?<div role="alert">{error} <button onClick={()=>setReload(n=>n+1)}>ลองใหม่</button></div>:!data?<p>กำลังโหลดแม่แบบ…</p>:data.status==='STALE'?<p role="alert">ต้นทางเปลี่ยน ระงับชุดแม่แบบจนตรวจ revision ใหม่</p>:<>
 {data.stageComplete&&<div className="cat-notice"><strong>ขั้นที่ 5 = {data.stageCompletionPercent}% ตามขอบเขตแม่แบบฉบับวางแผน P100</strong><p>ผู้ใช้อนุมัติให้ปิดขั้นที่ชุด P99 การปิดขั้นนี้ไม่ใช่อนุมัติวิศวกรรมหรือปล่อยผลิต งานต่อไปนี้ถูกโอนไป Production Engineering ภายหลัง:</p><ul>{(data.deferredWorkstreams??[]).map(w=><li key={w.id}><strong>{w.id}</strong> — {w.title}</li>)}</ul><Download artifact={data.stageClosure??null} label="ดาวน์โหลดทะเบียนปิดขอบเขต P100 JSON"/></div>}
 <p>ทะเบียนฐาน {data.developmentRevision} (ประวัติ): มีอุปกรณ์ระดับพัฒนา {data.setups.filter(s=>s.hardwareStatus==='PARTIAL_DEVELOPMENT').length} ชุด · ผิวแบบและแรงเท่านั้น {data.setups.filter(s=>s.hardwareStatus==='CONTACT_SKINS_AND_LOADS_ONLY').length} ชุด — จำนวนชุดไม่ใช่เปอร์เซ็นต์สำเร็จของขั้นที่ 5</p>
 {data.setups.some(s=>s.coordinatedFiles?.length)&&<p className="cat-notice">แบบรวม P99 มีแล้ว {data.setups.filter(s=>s.coordinatedFiles?.length).length} setup · ภาพประกอบ / 3D ชุดย่อย / บัญชี Tag / ลำดับถอด {current?.coordinatedFiles?.length?<a href="#mould-p99">ไปที่แบบรวมปัจจุบัน ↓</a>:null}</p>}
 {current?<><button className="cat-text-button" onClick={()=>setSelected('')}>← กลับชุดแม่แบบ</button><h2 className="p37-tag">{current.id}</h2><p>Typical {current.typicalId} · คอนกรีต {current.concreteKg.toFixed(2)} กก. · ช่องหล่อ XYZ {current.dimensionsMm.map(x=>x.toFixed(2)).join(' × ')} มม.</p>{current.presentation&&<section className="p37-sheet"><h3>ภาพนำเสนอ P43 — AI / ไม่ใช่แบบผลิต</h3><Board artifact={current.presentation} alt={current.typicalId+' ภาพนำเสนอ P43'}/><Download artifact={current.presentation} label="ดาวน์โหลดภาพนำเสนอ PNG"/></section>}{['03-GEOMETRY-REVIEW','01-CAVITY','00-TYPICAL'].filter(n=>current.files.some(a=>a.filename===n+'.png')).map(n=><section className="p37-sheet" key={n}><h3>{n==='03-GEOMETRY-REVIEW'?'ภาพตรวจรูปทรงจากโมเดล — ยังไม่ใช่กลไกถอดแบบ':n==='01-CAVITY'?'ช่องหล่อและท่าหล่อเสนอ':n==='02-TOOLING'?'แบ่งผิวแบบและลำดับประกอบ':'Typical ต้นทาง: มิติ / น้ำหนัก / แนวศึกษาหูยก'}</h3><Board artifact={current.files.find(a=>a.filename===n+'.png')??null} alt={current.typicalId+' '+n}/><div className="p37-actions">{current.files.filter(a=>a.filename.startsWith(n)).map(a=><Download key={a.id} artifact={a} label={a.filename}/>)}</div></section>)}<Download artifact={current.files.find(a=>a.filename==='setup.json')??null} label="ดาวน์โหลดพิกัดและบัญชี setup.json"/><h3>แบบอาคารที่ใช้ setup นี้</h3><div className="cat-table-scroll"><table className="cat-table"><thead><tr><th>สินค้า</th><th>จำนวนชิ้น/หลัง</th></tr></thead><tbody>{current.usedBy.map(p=><tr key={p.productId}><td>{p.productId}</td><td>{p.quantity}</td></tr>)}</tbody></table></div></>:<><Download artifact={data.archive} label="ดาวน์โหลดชุดตรวจรูปทรง P38-R1 (ZIP)"/><div className="cat-tools"><label className="cat-search">ค้นหา<input aria-label="ค้นหาแม่แบบ" placeholder="เช่น TS-C, N90, U-C3, FLOOR" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><p>พบ {rows.length} setup</p><div className="cat-grid">{rows.map(s=><article className="cat-card" key={s.id}><button className="cat-board" aria-label={'เปิดแม่แบบ '+s.typicalId} onClick={()=>{setSelected(s.id);window.scrollTo(0,0);}}>{(s.presentation??s.files.find(a=>a.filename==='03-GEOMETRY-REVIEW.png')??s.files.find(a=>a.filename==='01-CAVITY.png'))&&<img loading="lazy" src={(s.presentation??s.files.find(a=>a.filename==='03-GEOMETRY-REVIEW.png')??s.files.find(a=>a.filename==='01-CAVITY.png'))!.href} alt={s.typicalId+' ผิวแบบ3D'}/>}</button><div className="cat-card-body"><h2 className="p37-tag">{s.typicalId}</h2><p>{s.kind} · {s.concreteKg.toFixed(2)} กก. คอนกรีต</p><button className="cat-text-button" onClick={()=>{setSelected(s.id);window.scrollTo(0,0);}}>ดูช่องหล่อ / แบ่งแบบ / ดาวน์โหลด →</button></div></article>)}</div></>}
 {!!data.setups.some(s=>s.supplementGroups?.length)&&(!current||!!current.supplementGroups?.length)&&<p className="cat-notice">สถานะจำนวนชุดด้านบนเป็นฐานทะเบียน P61; มีรายละเอียดโครง/ฐาน/ค้ำผนังเพิ่มแล้ว {data.setups.filter(s=>s.supplementGroups?.length).length} ชุด A/B/D ดูหัวข้อ {data.supplementRevision} ด้านล่าง รายละเอียดเหล่านี้ยังไม่ปิด Production Engineering และไม่ใช่งานค้างของขั้นที่ 5 หลัง P100</p>}
 {current&&<CoordinatedMouldPanel files={current.coordinatedFiles??[]} typicalId={current.typicalId}/>}
 {current?.closureFile&&current.closureReview&&<section className="p37-sheet"><h3>P90 — บัญชีประวัติก่อนแก้ขอบเขต P100</h3><p>P90 เคยบันทึกงาน P40 ที่ยังไม่ปิด {current.closureReview.openDeliverables} หมวด ก่อนผู้ใช้อนุมัติแยกงานผลิต/กำลัง/ยกแม่แบบไป Production Engineering งานเหล่านี้ไม่ถูกนับเป็นงานค้างของขั้นที่ 5 หลัง P100 แต่ยังห้ามปล่อยผลิตจนกว่าจะตรวจครบ</p><p>{current.currentLiftingFiles?.length?'บันทึก ณ P90 (ก่อนเพิ่มแผนยก P91): ':''}{current.closureReview.next}</p>{current.closureReview.liftingCoordinateReview==='REMAP_REQUIRED_P52_TO_P56'&&(current.currentLiftingFiles?.length?<p className="cat-notice">P91 ปรับพิกัดยกให้ตรงท่าหล่อ P56 แล้ว ดูผลด้านล่าง; การรับรองอุปกรณ์ยกและการพลิกอยู่ใน Production Engineering</p>:<p className="cat-notice legacy">ต้องปรับพิกัดยกจากP52ให้ตรงท่าหล่อP56ก่อนใช้แผนยกร่วมกัน</p>)}<Download artifact={current.closureFile} label="ดาวน์โหลดบัญชีประวัติ P90 JSON"/></section>}
 {current&&<CastingLiftPanel files={current.currentLiftingFiles??[]} typicalId={current.typicalId}/>}
 {current&&<TableWeldPanel files={current.tableWeldFiles??[]} typicalId={current.typicalId}/>}
 {current&&<TableBasePanel files={current.tableBaseFiles??[]} typicalId={current.typicalId}/>}
 {current&&<TableBackerPanel files={current.tableBackerFiles??[]} typicalId={current.typicalId}/>}
 {current&&<TableSealPanel files={current.tableSealFiles??[]} typicalId={current.typicalId}/>}
 {current&&<TableChannelPanel files={current.tableChannelFiles??[]} typicalId={current.typicalId}/>}
 {current?.liftingFiles?.length?<section className="p37-sheet"><h3>P52 — โซนยกและแนวเหล็กคอนกรีต{current.sourceRevision==='P56'?' (ประวัติท่าหล่อเดิม)':''}</h3><p>สมมติกำลังคอนกรีตเพียงพอเพื่อพัฒนาแบบตามผู้ใช้ แนวเหล็กไม่ระบุขนาด เป็นกรณียกอิสระแนวดิ่งในท่าหล่อหลังปลดแบบแล้ว ไม่ใช่พิกัดเจาะหรือแบบยกจริง และไม่ครอบคลุมการพลิกชิ้น</p><Board artifact={current.liftingFiles.find(a=>a.filename.endsWith('.png'))??null} alt={current.typicalId+' โซนยกและแนวเหล็ก P52'}/><div className="p37-actions">{current.liftingFiles.map(a=><Download key={a.id} artifact={a} label={'ดาวน์โหลด P52 '+a.filename.split('.').at(-1)?.toUpperCase()}/>)}</div></section>:null}
 {current&&<section className="p37-sheet"><h3>{data.developmentRevision} — รวมแบบแม่แบบเหล็กและผลตรวจที่จัดทำแล้ว</h3>{current.developmentFiles?.length?<><p>แหล่งข้อมูล {current.sourceRevision??'P53'} · {current.hardwareStatus==='CONTACT_SKINS_AND_LOADS_ONLY'?'ผิวแบบและแรงดันเท่านั้น — ยังไม่มีโครงหลัง จุดล็อก หรือระบบยึดบล็อกช่องเปิด':'มีอุปกรณ์แม่แบบระดับพัฒนา — ยังไม่ปิดข้อกำหนดทั้งหมด'} ไม่ใช่แบบอนุมัติผลิต</p>{current.sourceRevision==='P56'&&<p className="cat-notice legacy">{current.currentLiftingFiles?.length?'ใช้แผนยก P91 สำหรับพิกัดท่าหล่อ P56; P52 เก็บไว้เป็นประวัติ ไม่ใช่พิกัดปัจจุบัน':'ท่าหล่อ P56 เปลี่ยนจาก P52: ต้องแปลงและตรวจตำแหน่งยกใหม่ ห้ามนำพิกัดยก P52 ไปใช้ตรง ๆ'}</p>}{current.developmentFiles.filter(a=>a.filename.endsWith('.png')).map(a=><div key={a.id}><h4>{a.filename}</h4><Board artifact={a} alt={current.typicalId+' '+a.filename}/><Download artifact={a} label={'ดาวน์โหลด '+a.filename}/></div>)}<div className="p37-actions">{current.developmentFiles.filter(a=>!a.filename.endsWith('.png')).map(a=><Download key={a.id} artifact={a} label={a.filename+' · '+a.id.split('-').slice(-1)}/>)}</div></>:<p>ยังไม่มีโมเดลโครงเหล็ก/จุดล็อกรายชิ้นที่ตรวจแล้วสำหรับ setup นี้ ภาพนำเสนอและโซนยกไม่ถือว่าปิดงานนี้</p>}{!!current.historicalDevelopmentFiles?.length&&<details><summary>ประวัติข้อมูลพัฒนาเดิม — ไม่ใช่ผลตรวจรุ่นปัจจุบัน</summary><p>คงไฟล์เดิมเพื่อสอบย้อนกลับ ไม่สืบทอดผลกำลังหรือการยกไปยังโมเดลใหม่</p><div className="p37-actions">{current.historicalDevelopmentFiles.map(a=><Download key={a.id} artifact={a} label={a.filename+' · '+a.id}/>)}</div></details>}</section>}
 {current?.supplementGroups?.length?<section className="p37-sheet">
  <h3>{data.supplementRevision} — รายละเอียดแม่แบบและผลตรวจล่าสุด</h3>
  {['P87','P88','P89','P90','P92'].includes(data.supplementRevision??'')?<>
   <p>เรขาคณิตปัจจุบัน: ฐาน/ตัวแบบ P85 + ค้ำ P71 + จุดล็อกรอยต่อ P74 + ซี่ขอบ P80 อย่างละหนึ่งชุด ใช้ลำดับถอด P85 ไม่รวมฐาน P66 หรือค้ำ P67 ซ้ำ ภาพและข้อมูลเก่าด้านบนเก็บไว้เป็นประวัติ</p>
   <p>P86 เป็นการศึกษาแรงขาฐานรุ่นมีหน้าต่างเท่านั้น รวมการดัดแผ่นและสัมผัสฝ่ายเดียว ไม่ใช่กำลังรับได้ และไม่ครอบคลุมรุ่นทึบหรือแม่แบบทั้งระบบ ยังต้องตรวจจุดต่อ ระบบพยุง/ยก/พลิก และรายละเอียดผลิตให้ครบ</p>
  </>:<p>ข้อมูล P66 ร่วมกับค้ำ P67 เป็นฐานประวัติ ส่วนการปิดกำลังและรายละเอียดผลิตอยู่ใน Production Engineering</p>}
  {current.supplementGroups.some(g=>g.revision==='P88')&&<p className="cat-notice legacy">P88 ตรวจตัวโบลต์และแรงกดรูแผ่นขาแบบมีเงื่อนไข ไม่ใช่ผลผ่านของจุดยึดทั้งชุด ยังต้องตรวจเกลียวในฐาน แหวนรอง ความล้า/การคลายตัว และรอยเชื่อม ตัวคูณแรงดันเป็นกรณีศึกษา ไม่ใช่ชุดรวมแรงที่อนุมัติ</p>}
  {current.supplementGroups.some(g=>g.revision==='P89')&&<p className="cat-notice legacy">P89 เป็นแบบทางเลือกโบลต์และแหวน ยังไม่แทน geometry P85 ที่ใช้วิเคราะห์ แหวนเปลี่ยนรัศมี20เป็น18.5มม. จึงไม่สืบทอดแรงและผลตรวจ P86/P88 อัตโนมัติ แก้ข้อความระยะรูเดิม: ขา M01=250มม. แต่ M03=240มม. ภาพต้นฉบับคงเดิม</p>}
  {current.supplementGroups.some(g=>g.revision==='P90')&&<p className="cat-notice">P90 วิเคราะห์แรงขาฐาน W01 ใหม่สำหรับแหวนรัศมี18.5มม.ของทางเลือกP89 ใช้ผลนี้เฉพาะกรณีที่ระบุ ไม่ใช่การอนุมัติP89ทั้งชุดหรือการตรวจแหวน/เกลียวจริง และไม่สืบทอดผลกำลังP88โดยอัตโนมัติ</p>}
  {current.supplementGroups.some(g=>g.revision==='P92')&&<p className="cat-notice">P92 จับคู่แรงดึง P90 กับแรงเฉือน P85 ที่ตำแหน่งและกรณีเดียวกันแล้ว พร้อมรายละเอียดแหวน/ระยะฝังและใบตรวจรับเสนอ ตรวจตัวโบลต์สถิตแบบมีเงื่อนไข ไม่ใช่การรับรองใช้แม่แบบซ้ำ ค่าแรงขันและ preload ยังไม่กำหนด และไม่ปิดงานจุดต่อทั้งระบบ</p>}
  <p>ห้ามใช้แรงหรือน้ำหนักของ P62 รับรองชุดใหม่ที่เพิ่มเหล็กแล้ว</p>
  {[...current.supplementGroups].reverse().map(g=><details key={g.revision} open={g.role==='LATEST_OVERLAY'||g.role==='OVERLAY_BASE'||g.role==='CURRENT_BASE'||g.role==='UNADOPTED_CANDIDATE'}>
   <summary>{g.revision} — {g.label} · {g.role==='HISTORICAL_SUBSYSTEM'?'ประวัติระบบย่อย':g.role==='ANALYSIS_STUDY'?'กรณีศึกษาแรง ไม่ใช่กำลังรับได้':g.role==='CONDITIONAL_COMPONENT_CHECK'?'ตรวจองค์ประกอบเฉพาะกรณี ยังไม่ผ่านทั้งจุดต่อ':g.role==='UNADOPTED_CANDIDATE'?'แบบทางเลือก ยังไม่เป็นรุ่นวิเคราะห์ที่ยืนยันแล้ว':'ข้อมูลรูปทรงที่ต้องใช้ร่วมกัน'}</summary>
   {g.files.filter(a=>a.filename.endsWith('.png')).map(a=><Board key={a.id} artifact={a} alt={current.typicalId+' '+g.revision+' '+g.label}/>)}
   <div className="p37-actions">{g.files.map(a=><Download key={a.id} artifact={a} label={g.revision+' · '+a.filename}/>)}</div>
  </details>)}
 </section>:null}
 </>}</section>;
}
