import {DownloadButton} from './Downloads';
import type {ProfileThicknessStudy} from './model';
const pct=(v:number)=>v<.00001?'<0.001%':(100*v).toFixed(3)+'%';
export function ProfileThicknessStudyView({study,combined=false,focusArc=false,focusBase=false}:{study:ProfileThicknessStudy;combined?:boolean;focusArc?:boolean;focusBase?:boolean}){
  return <section className="cat-detail"><span className="cat-eyebrow">{focusBase?'STEP 2O / BASE PROFILE':focusArc?'STEP 2M / ARC + CROWN':combined?'STEP 2L / COMBINED MESH':'STEP 2K / FULL-BAY DIRECTIONAL MESH'}</span><h1>{focusBase?'ตรวจผนังใกล้ฐาน':focusArc?'ตรวจส่วนโค้งและกลางหลังคา':combined?'ผลร่วมแนวหน้าตัดและความหนา':'แยกความละเอียดแนวหน้าตัดกับความหนา'}</h1>
    {study.status==='STALE'&&<p role="alert" className="cat-notice legacy">Step {focusBase?'2O':focusArc?'2M':combined?'2L':'2K'} ข้อมูลต้นทางเปลี่ยน — STALE ต้องคำนวณใหม่</p>}
    <p className="cat-notice legacy">TS-C เต็มโมดูล / FULL / t175 / NC320 trial / F-R / bonded crown — ยังไม่อนุมัติผลิต และยังไม่ยืนยันความเค้นลู่เข้าทั้งโมเดล</p>
    {focusBase?<p>NB แบ่ง3ช่องผนังแรกเหนือฐานต่อซีกเป็น4ช่องย่อย ได้ผนัง36ช่อง โดยคงarc48/roof24/Y16/ความหนา8ชั้นและคอนกรีต175มม. เทียบM1หนึ่งคู่ ไม่เพิ่มYหรือชั้นความหนา และไม่เปลี่ยนฐานรองรับ</p>:focusArc?<p>M1 เพิ่ม interior arc เป็น48ช่องและแบ่งสองช่องหลังคาใกล้crownให้เล็กลง รวมหลังคา24ช่องต่อซีก โดยคงผนัง27/Y16/ความหนา8ชั้นและคอนกรีต175มม. เทียบKPTหนึ่งคู่ ยังไม่เพิ่มฐานหรือแนวยาว และไม่ใช่การลู่เข้าทั้งโมเดล</p>:combined?<p>KPT คือ mesh แนวหน้าตัดของ KP ร่วมกับชั้นตามความหนา8ชั้นของ KT; เพิ่มหนึ่ง run เทียบ KP/KT โดยคง Y16 และความหนาคอนกรีต175มม. ไม่ได้เพิ่ม interior-arc/base/Y refinement พร้อมกัน ไม่ใช่การลู่เข้าทั้งโมเดล</p>:<p>KP เพิ่ม mesh ตามแนวหน้าตัดใกล้ผนัง–โค้ง–หลังคาและกลางหลังคา; KT เพิ่มชั้นตามความหนา 6→8 โดยความหนาคอนกรีตคง 175 มม. ทั้งสองชุดเทียบ H4 เดิมและคง Y16 ไม่ใช่ mesh IBY และยังไม่ได้รัน KP+KT รวมกัน</p>}
    <div className="cat-table-scroll"><table className="cat-table"><caption>{focusBase?'M1 เดิม / NB ใหม่':focusArc?'KPT เดิม / M1 ใหม่':combined?'H4 / KP / KT เดิม และ KPT ใหม่':'H4 control และสองชุดใหม่'}</caption><thead><tr><th>Mesh</th><th>Elements</th><th>Nodes</th><th>|u|max (mm)</th><th>LH Rx (kN)</th><th>LH Rz (kN)</th></tr></thead><tbody>{study.runs.map(r=><tr key={r.id}><th>{r.mesh}</th><td>{r.elements}</td><td>{r.nodes}</td><td>{r.max_displacement_mm.toFixed(7)}</td><td>{r.base.LH[0]!.toFixed(6)}</td><td>{r.base.LH[2]!.toFixed(6)}</td></tr>)}</tbody></table></div>
    <h2>ความเค้นที่ 490 พิกัดเดิม</h2><p>Local s/y/n; ไม่ smooth หรือเฉลี่ยความเค้นข้ามหน้า เกณฑ์ point/RMS/spread ≤5% ครบ6องค์ประกอบ ตัวหารอย่างน้อย10kPa ไม่ใช่การใช้กำลังวัสดุ</p>
    {focusBase&&<p className="cat-notice legacy">กลุ่มที่ผ่านในคู่ M1→NB ไม่ปิดประเด็น arc convergence จากรอบก่อน เพราะคู่นี้ไม่ได้เพิ่ม mesh ส่วนโค้ง</p>}
    {study.local.map(c=><div key={c.pair.join('/')} className="cat-table-scroll"><table className="cat-table"><caption>{c.pair.join(' → ')} / เกณฑ์เฉพาะคู่ที่ตรวจ</caption><thead><tr><th>กลุ่ม</th><th>Max point</th><th>Spread</th><th>ครบ point/RMS/spread</th></tr></thead><tbody>{c.groups.map(g=><tr key={g.group}><th>{g.group}</th><td>{pct(g.point)}</td><td>{pct(g.spread)}</td><td>{g.met?'เฉพาะคู่ที่ตรวจ':'ยังไม่ครบ'}</td></tr>)}</tbody></table></div>)}
    <h2>แรงหน้าตัดจากความเค้น</h2><p>แรง kN / โมเมนต์ kN·m รอบ origin ของแต่ละ cut; lower และ upper มี normal ตรงข้าม ต้องเทียบแรงครบ6องค์ประกอบ ตัวหารอย่างน้อย .1 kN / .1 kN·m ไม่ใช่เปอร์เซ็นต์น้ำหนักอาคาร</p>
    {(focusArc||focusBase)&&<div className="cat-table-scroll"><table className="cat-table"><caption>{focusBase?'NB':'M1'} / เกณฑ์ traction ทั้งสามส่วน</caption><thead><tr><th>Cut</th><th>Lower / nodal</th><th>Upper / nodal</th><th>Trace-pair</th><th>ครบทุกเกณฑ์</th></tr></thead><tbody>{study.traction.find(r=>r.mesh===(focusBase?'NB':'M1'))?.cuts.map(c=><tr key={c.id}><th>{c.id}</th><td>{pct(Math.max(...c.traces.lower.relative_vs_nodal_6))}</td><td>{pct(Math.max(...c.traces.upper.relative_vs_nodal_6))}</td><td>{pct(Math.max(...c.trace_pair_relative_6))}</td><td>{c.targets_met?'เฉพาะcutนี้':'ยังไม่ครบ'}</td></tr>)}</tbody></table></div>}
    {study.traction.map(r=><details key={r.id}><summary>{r.mesh} · cuts ครบเกณฑ์ {r.cuts.filter(c=>c.targets_met).length}/6</summary>{r.cuts.map(c=><div key={c.id} className="cat-table-scroll"><table className="cat-table"><caption>{r.mesh} / {c.id} / XYZ [{c.origin_m.join(', ')}] m</caption><thead><tr><th>แรง</th><th>Nodal lower</th><th>Traction lower</th><th>Traction upper</th><th>ผลรวม 2 traces</th><th>Pair error</th></tr></thead><tbody>{['Fx','Fy','Fz','Mx','My','Mz'].map((v,k)=><tr key={v}><th>{v}</th><td>{c.nodal_lower_6[k]!.toFixed(7)}</td><td>{c.traces.lower.order6.resultant_6[k]!.toFixed(7)}</td><td>{c.traces.upper.order6.resultant_6[k]!.toFixed(7)}</td><td>{c.trace_pair_sum_6[k]!.toFixed(7)}</td><td>{pct(c.trace_pair_relative_6[k]!)}</td></tr>)}</tbody></table></div>)}</details>)}
    <p className="cat-notice legacy">ไม่มีคำตอบ exact ของ full bay และยังไม่ตรวจร้าว ช่องเปิด รอยต่อจริง ลม แรงยก หรือยกขนส่ง ไม่ใช้การผ่านสมดุลหรือการโก่งตัวน้อยรับรองอาคาร</p>
    <h2>ภาพดาวน์โหลด</h2>{study.drawings.map(d=><section key={d.id} className="cat-study-drawing"><h3>{d.title}</h3><DownloadButton artifact={d.artifact}/><a className="cat-full-board" href={d.artifact.url} target="_blank" rel="noreferrer"><img src={d.artifact.url} alt={d.title} loading="lazy"/></a></section>)}
  </section>;
}
