import {useState} from 'react';
import {DownloadButton} from './Downloads';
import type {QuadraticBayStudy} from './model';
const f=(v:number|undefined,d=3)=>v===undefined?'—':Math.abs(v)<.0000001?'≈0':v.toFixed(d),pct=(v:number)=>f(v*100)+'%';
const zones:Record<string,string>={regular_interior:'ภายในทั่วไป',side_edge:'ใกล้ขอบด้านข้าง',base_probe:'ใกล้ฐาน 50 มม.',crown_probe:'ใกล้กลางหลังคา 50 มม.'};
export function QuadraticBayStudyView({study}:{study:QuadraticBayStudy}){
  const [pattern,setPattern]=useState('FULL'),[zone,setZone]=useState('regular_interior');
  const runs=study.runs.filter(r=>r.pattern===pattern).sort((a,b)=>a.mesh.localeCompare(b.mesh)),run=runs.at(-1),qa=study.global_comparisons.find(c=>c.pattern===pattern),local=study.local_comparisons.find(c=>c.pattern===pattern),group=local?.groups.find(g=>g.group===zone),old=study.prior_model_comparisons.find(c=>c.pattern===pattern),profile=study.profiles.find(p=>p.pattern===pattern);
  return <section className="cat-detail">
    <div className="cat-detail-heading"><div><span className="cat-eyebrow">STEP 2H / QUADRATIC FULL BAY</span><h1>TS-C เต็มโมดูลด้วย 20-node</h1><p>175 มม. / NC320 trial / 3×3×1.50 ม. / F-R limit · {study.revision}</p></div><span className="cat-badge">งานศึกษา · ยังไม่ใช้ผลิต</span></div>
    {study.status==='STALE'&&<p className="cat-notice legacy" role="alert">ข้อมูลต้นทางเปลี่ยน — ผล Step 2H เป็น STALE ต้องสร้างใหม่</p>}
    <div className="cat-tools"><label>Roof LL<select aria-label="โหลดโมดูล 20-node" value={pattern} onChange={e=>setPattern(e.target.value)}><option value="FULL">เต็มหลังคา</option><option value="LEFT">ครึ่งซ้าย</option></select></label></div>
    <p className="cat-notice legacy">แรงรวมกับความเค้นเฉพาะที่ต้องตรวจแยกกัน — แม้แรงรวมเริ่มนิ่ง ก็ยังไม่รับรอง local-stress convergence ทั้งโมดูล และไม่ใช่การเลือกความหนาผลิต</p>
    <p>น้ำหนักตัวเต็มสองซีก + Roof LL 50 kgf/m² บนพื้นที่ฉายแนวราบ; ยังไม่คูณตัวประกอบโหลด · พื้นแยกและไม่อยู่ในแบบจำลอง ขอบ Y=0/1.50 ม. อิสระ · ไม่มี prestress เฉพาะกรณีศึกษา</p>
    <p className="cat-note">ฐาน Ux=Uz=0 ทั้งหน้า และ Uy datum หนึ่งจุดต่อด้าน; crown เชื่อมต่อเนื่องทั้งความหนา เป็นขีดจำกัดอุดมคติ ไม่ใช่รายละเอียดสลักเกลียวหรือรอยต่อที่ทดสอบแล้ว ไม่มีช่องเปิด ร้าว ลม แรงยก หรือสภาวะประกอบ</p>
    <div className="cat-table-scroll"><table className="cat-table"><caption>{pattern} / เปรียบเทียบ mesh · ไม่ใช่ผลตรวจ serviceability ตามโค้ด</caption><thead><tr><th>Mesh</th><th>Elements / nodes</th><th>|u|max (มม.)</th><th>Crown Uz (มม.)</th><th>Energy (kN·m)</th></tr></thead><tbody>{runs.map(r=><tr key={r.id}><th>{r.mesh}</th><td>{r.elements.toLocaleString()} / {r.nodes.toLocaleString()}</td><td>{f(r.max_displacement_mm,5)}</td><td>{f(r.crown_mid_uz_mm,5)}</td><td>{f(r.strain_energy_kNm,6)}</td></tr>)}</tbody></table></div>
    {qa&&<p>{qa.pair.join(' → ')}: การเคลื่อนตัวเปลี่ยน {pct(qa.displacement_change)} / แรงฐาน {pct(qa.reaction_change)} / แรงหน้าตัด {pct(qa.cut_change)} / พลังงาน {pct(qa.energy_change)} — {qa.selected_global_targets_met?'เข้าเกณฑ์เฉพาะผลรวมที่ตรวจ':'ยังไม่ครบเกณฑ์ผลรวม'}</p>}
    {run&&<><h2>แรงฐานและแนวตัด · {run.mesh} / {pattern}</h2><div className="cat-table-scroll"><table className="cat-table"><caption>หน่วยแรง kN, โมเมนต์ kN·m; แกน global · ไม่ใช่แรงต่อเมตรหรือแรงต่อ bolt</caption><thead><tr><th>ตำแหน่ง</th><th>Fx</th><th>Fz</th><th>My</th></tr></thead><tbody>{Object.entries(run.base).map(([h,v])=><tr key={h}><th>ฐาน {h}</th><td>{f(v[0])}</td><td>{f(v[2])}</td><td>{f(v[4])}</td></tr>)}{run.cuts.map(c=><tr key={c.id}><th>LH/{c.id}</th><td>{f(c.cut_on_lower_LH_6[0])}</td><td>{f(c.cut_on_lower_LH_6[2])}</td><td>{f(c.cut_on_lower_LH_6[4])}</td></tr>)}</tbody></table></div><p className="cat-note">โมเมนต์ฐานอ้างอิงกึ่งกลางฐานแต่ละด้าน; แนวตัดอ้างอิงกึ่งกลางแนวตัด แรงบนส่วนล่างของ LH · คู่แรงอีกฝั่งตรงข้าม ไม่ใช่ external load ซ้ำ</p></>}
    <h2>ความเค้นที่ 490 พิกัดร่วมต่อกรณี</h2><div className="cat-tools"><label>บริเวณตรวจ<select aria-label="บริเวณความเค้น 20-node" value={zone} onChange={e=>setZone(e.target.value)}>{Object.entries(zones).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label></div>
    {group&&<><p>{zones[group.group]}: {group.points} จุด · {local?.pair.join(' → ')} · {group.all_six_targets_met?'ครบเฉพาะจุด/องค์ประกอบที่ตรวจ':'ยังไม่ครบทั้ง 6 องค์ประกอบ'}</p><div className="cat-table-scroll"><table className="cat-table"><caption>เกณฑ์เดิม 5% ทุกช่อง; ตัวหารอ้างอิงอย่างน้อย 10 kPa ไม่ใช่ capacity ratio</caption><thead><tr><th>Stress</th><th>Max point change</th><th>RMS change</th><th>One-sided spread</th><th>Δ ณ จุดคุม (kPa)</th><th>ผล</th></tr></thead><tbody>{group.fields.map(v=><tr key={v.component}><th>σ/τ {v.component}<small>{v.worst_point}</small></th><td>{pct(v.max_point_change)}</td><td>{pct(v.rms_change)}</td><td>{pct(v.max_spread_relative)}</td><td>{f(v.difference_kPa)}</td><td>{v.targets_met?'เฉพาะค่าที่ตรวจ':'ยังไม่ครบ'}</td></tr>)}</tbody></table></div></>}
    {profile&&<details><summary>Profile LH/C45/Y=.75 / {pattern} / H4</summary><div className="cat-table-scroll"><table className="cat-table"><caption>kPa; f จากผิวใน/t · ค่าภายในเนื้อ ไม่ extrapolate ถึงผิว</caption><thead><tr><th>f</th><th>σss</th><th>σnn</th><th>τsn mean</th><th>τsn ช่วงด้านติดกัน</th></tr></thead><tbody>{profile.points.map(p=><tr key={p.fraction}><th>{p.fraction}</th><td>{f(p.mean_kPa[0])}</td><td>{f(p.mean_kPa[2])}</td><td>{f(p.mean_kPa[4])}</td><td>{f(p.min_kPa[4])} ถึง {f(p.max_kPa[4])}</td></tr>)}</tbody></table></div></details>}
    <details><summary>เก็บผล H2 → H3 เดิมไว้ก่อนเพิ่ม H4</summary>{study.initial_local_comparisons.filter(c=>c.pattern===pattern).flatMap(c=>c.groups.map(g=><p key={g.group}>{zones[g.group]}: max-point {pct(Math.max(...g.fields.map(f=>f.max_point_change)))} / spread {pct(Math.max(...g.fields.map(f=>f.max_spread_relative)))} — {g.all_six_targets_met?'ครบเฉพาะที่ตรวจ':'ยังไม่ครบ'}</p>))}</details>
    {old&&<p className="cat-note">Crown Uz ของ H4 ต่างจาก 8-node เดิม {old.source_id}: {pct(old.crown_uz_relative_difference)} · geometry และการกระจายโหลดต่างกันด้วย จึงไม่ใช่การเทียบ element เพียงอย่างเดียว หรือคำตอบ exact ของโมดูล</p>}
    <p className="cat-notice legacy">ขั้นถัดไปต้องแยกผลขอบอิสระ/ฐาน/รอยต่อ และตรวจความละเอียดเฉพาะบริเวณ ก่อนเลือกเหล็กหรือจำนวนอุปกรณ์ยึด การผ่านชิ้นโค้ง Step 2G ไม่ใช้แทนการตรวจโมดูลนี้</p>
    <h2>ภาพดาวน์โหลด · ตัวอย่างคงที่ FULL / H4 / t175</h2>{study.drawings.map(d=><section className="cat-study-drawing" key={d.id}><div className="cat-status-heading"><h3>{d.title}</h3><DownloadButton artifact={d.artifact}/></div><a className="cat-full-board" href={d.artifact.url} target="_blank" rel="noreferrer"><img src={d.artifact.url} alt={d.title} loading="lazy"/></a></section>)}
    <details><summary>แหล่งอ้างอิง</summary>{study.basis.sources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a></p>)}</details>
  </section>;
}
