import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import {keys} from './abd-base-pattern-p85.mjs';import {properties,rect} from './prism-tools-p54.mjs';import {collide} from './abd-base-lock-p66.mjs';
import {shift} from './prism-tools-p54.mjs';
const near=(a,b,t=1e-5)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`),read=p=>JSON.parse(fs.readFileSync(p)),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
for(const key of keys)test(key+' relocated holes, no stale seats, complete change clearance',()=>{
 const m=read(`output/abd-base-pattern-p85/${key}.json`),old=read(`output/abd-base-lock-p66/${key}.json`);assert.equal(m.relocations.length,8);assert.equal(m.baseLocks.length,40);assert.equal(m.parts.length,old.parts.length);assert.equal(new Set(m.parts.map(p=>p.tag)).size,m.parts.length);assert.deepEqual(m.concrete,old.concrete);assert.deepEqual(m.audit.staticHits,[]);assert.ok(m.audit.toolChecks.every(r=>!r.hits.length));assert.equal(m.audit.toolChecks.length,76);assert.ok(m.audit.changedGeometryContinuousMoves.every(r=>!r.hits.length));assert.deepEqual(m.audit.remainingTags,['M00']);
 for(const p of m.inputSnapshots)assert.equal(hash(p.path),p.sha256);
 const web=read(m.overlayReferences.web),seam=read(m.overlayReferences.seam),edge=read(m.overlayReferences.edge);assert.deepEqual(old.audit.staticHits,[]);assert.ok(old.audit.moves.every(r=>!r.hits.length));assert.deepEqual(web.audit.staticHits,[]);assert.ok(web.audit.additionalIntegratedMoves.every(r=>!r.hits.length));assert.deepEqual(seam.audit.staticHits,[]);assert.ok(seam.audit.moves.every(r=>!r.hits.length));assert.deepEqual(edge.audit.staticHits,[]);assert.ok(edge.audit.supplementaryMoves.every(r=>!r.hits.length));
 for(const r of m.relocations){const foot=m.baseFeet.find(f=>f.tag===r.foot),bed=m.parts.find(p=>p.tag==='M00'),probe=([x,y],z)=>[rect(x-.5,x+.5,y-.5,y+.5,z,z+1)];assert.equal(collide(foot.cells,probe(r.oldAxisMm,10)),true);assert.equal(collide(bed.cells,probe(r.oldAxisMm,-10)),true);assert.equal(collide(foot.cells,probe(r.newAxisMm,10)),false);assert.equal(collide(bed.cells,probe(r.newAxisMm,-10)),false);for(const tag of [r.tag,r.tag+'-W'])assert.deepEqual(m.sequence.find(row=>row[0]===tag)[1],[0,0,250]);}
 for(const f of m.baseFeet)near(properties(f.cells).massKg,properties(old.baseFeet.find(p=>p.tag===f.tag).cells).massKg);near(properties(m.parts.find(p=>p.tag==='M00').cells).massKg,properties(old.parts.find(p=>p.tag==='M00').cells).massKg);assert.equal(m.engineeringApproved,false);assert.equal(m.productionReleased,false);assert.equal(m.stageComplete,false);
});
for(const f of ['A','B','D'])for(const v of ['S00','W01'])test(`${f}-${v} mirrored relocation`,()=>{const a=read(`output/abd-base-pattern-p85/${f}-LH-${v}.json`),b=read(`output/abd-base-pattern-p85/${f}-RH-${v}.json`);a.baseLocks.forEach((p,i)=>{near(p.axisMm[0]+b.baseLocks[i].axisMm[0],1490);near(p.axisMm[1],b.baseLocks[i].axisMm[1]);});});
test('old 100mm lift hits lower waler for relocated near-wall bolt; 250mm clears it',()=>{const m=read('output/abd-base-pattern-p85/A-LH-W01.json'),r=m.relocations.find(r=>r.tag==='M01-F1-B3'),bolt=m.parts.find(p=>p.tag===r.tag),owner=m.parts.find(p=>p.tag==='M01'),delta=m.sequence.find(row=>row[0]===r.tag)[2];assert.equal(collide(bolt.cells.map(c=>shift(c,[0,0,100])),owner.cells,delta),true);assert.equal(collide(bolt.cells.map(c=>shift(c,[0,0,250])),owner.cells,delta),false);});
test('actual pattern W01 bolt demands have current geometry hashes and balanced shear',()=>{const d=read('output/abd-base-pattern-p85/bolt-demand.json');assert.equal(d.records.length,24);for(const r of d.records){for(const p of r.inputs)assert.equal(hash(p.path),p.sha256);assert.equal(r.bolts.length,4);r.shearResidualN.forEach(v=>near(v,0));near(r.shearMomentResidualNmm,0);assert.ok(r.bolts.every(b=>b.verifiedCapacityN===null));assert.equal(r.engineeringApproved,false);}});
