import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {root} from './cap-geometry-p55.mjs';
import {keys,build} from './abd-window-p62.mjs';import {build as skins} from './abd-shell-skins-p60.mjs';import {collide,rect,properties} from './prism-tools-p54.mjs';
const models=new Map(),get=k=>{if(!models.has(k))models.set(k,build(k));return models.get(k);};
for(const key of keys)test(`${key}: exact casting, real screw seats, stock, tools and continuous paths`,()=>{
 const m=get(key),s=skins(key);assert.deepEqual(m.source,s.source);assert.deepEqual(m.concrete.faces,s.concrete.faces);assert.deepEqual(m.castingTransform,s.castingTransform);
 assert.deepEqual(m.audit.staticHits,[]);assert.deepEqual(m.audit.stockIntersections,[]);m.audit.moves.forEach(r=>assert.deepEqual(r.hits,[],r.tag));m.audit.socketChecks.forEach(r=>assert.deepEqual(r.hits,[],r.bolt));
 assert.equal(m.audit.socketChecks.length,8);assert.equal(m.baseScrewSeats.length,8);assert.deepEqual(m.audit.remainingTags,['M00']);assert.equal(m.parts.filter(p=>p.tag.startsWith('WB')).length,8);
 assert.equal(m.stock.length,12);assert.ok(Math.abs(properties(m.stock.flatMap(p=>p.cells)).massKg-m.cassetteProperties.massKg)<1e-7);
 const current=m.parts.find(p=>p.tag==='M01'),old=s.parts.find(p=>p.tag==='M01');assert.ok(properties(current.cells).volumeMm3<properties(old.cells).volumeMm3);
 assert.equal(m.productionReleased,false);assert.equal(m.engineeringApproved,false);
});
for(const family of ['A','B','D'])test(`${family}: cassette handedness mirrors mass and CG`,()=>{const l=get(`${family}-LH-W01`),r=get(`${family}-RH-W01`);assert.ok(Math.abs(l.cassetteProperties.massKg-r.cassetteProperties.massKg)<1e-7);assert.ok(Math.abs(l.cassetteProperties.cgMm[0]+r.cassetteProperties.cgMm[0]-1490)<1e-6);for(const i of [1,2])assert.ok(Math.abs(l.cassetteProperties.cgMm[i]-r.cassetteProperties.cgMm[i])<1e-6);});
test('negative control: uncut P60 outer skin traps the new window cassette',()=>{const m=get('D-LH-W01'),s=skins('D-LH-W01'),wc=m.parts.find(p=>p.tag==='WC');assert.equal(collide(wc.cells,s.parts.find(p=>p.tag==='M01').cells),true);});
test('negative control: solid unbored bed clashes with all eight screws',()=>{const m=get('A-LH-W01'),bed=[rect(-1000,2490,-1000,3900,-30,0)];assert.ok(m.parts.filter(p=>p.tag.startsWith('WB')).every(p=>collide(p.cells,bed)));});
test('no silent whole-mould completion: support, side locks and weld design remain explicit',()=>{const m=get('B-LH-W01');assert.ok(m.limits.some(s=>s.includes('temporary capture')));assert.ok(m.limits.some(s=>s.includes('Side-insert locking')));assert.ok(m.limits.some(s=>s.includes('backframes')));});
test('saved resultants retain weight, sign convention and eccentric moment, not equal bolt forces',()=>{for(const key of keys){const m=get(key),d=JSON.parse(fs.readFileSync(path.join(root,'output/abd-window-p62',key+'-demand.json'),'utf8'));assert.ok(Math.abs(d.steelWeightKN[2]+m.cassetteProperties.massKg*9.80665/1000)<1e-9);for(let i=0;i<3;i++){assert.ok(Math.abs(d.netAppliedForceKN[i]+d.requiredSupportResultantKN[i])<1e-9);assert.ok(Math.abs(d.netAppliedMomentAboutReferenceKNmm[i]+d.requiredSupportMomentKNmm[i])<1e-9);}assert.ok(Math.abs(d.requiredSupportMomentKNmm[1])>1700);assert.equal(d.individualBoltForces,null);assert.equal(d.capacityChecked,false);}});
