import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {root} from './build-r02.mjs';import {piece,model,checklist,ceiling} from './end-infill-p25.mjs';import {innerWallX,panelLeft,roofInnerZ} from './abd-floor-ends-p09.mjs';
const close=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<t,`${a} vs ${b}`);
test('P25 eight unique candidates mirror geometry mass and concrete centroid',()=>{const m=model();assert.equal(new Set(m.records.map(r=>r.id)).size,8);for(const f of ['A','B','C','D']){const a=piece(f,'LH'),b=piece(f,'RH');assert.deepEqual(b.outlineXZ,a.outlineXZ.map(([x,z])=>[3000-x,z]).reverse());close(a.mass.concreteMassKg,b.mass.concreteMassKg);close(a.mass.concreteOnlyCentroidMm[0]+b.mass.concreteOnlyCentroidMm[0],3000);assert.equal(a.bounds.x[1],1490);assert.equal(b.bounds.x[0],1510);}});
test('P25 top follows inner roof minus20 vertical and bottom is20 above panel',()=>{for(const f of ['A','B','C','D']){const r=piece(f,'LH');assert.equal(r.bottomZ-r.interface.endPanelTopZ,20);for(const [x,z] of r.outlineXZ.slice(1,-1))close(ceiling(f,x)-z,20);assert.ok(r.outerEndHeightMm>0);assert.equal(r.gaps.normalRoofClearanceMm,null);}});
test('P25 A independent trapezoid area and D independent tapered trapezoid mass',()=>{const a=piece('A','LH'),d=piece('D','LH');close(a.mass.concreteMassKg,1320*(a.outerEndHeightMm+a.maxHeightMm)/2*150/1e9*2400);close(d.mass.concreteMassKg,(d.bottomWidthMm+d.topProjectedWidthMm)/2*310*150/1e9*2400);close(d.bottomWidthMm-d.topProjectedWidthMm,22);});
test('P25 curved volume convergence and mass formula are stable',()=>{for(const f of ['A','B','C','D']){const a=piece(f,'LH'),b=piece(f,'LH',8192);close(a.mass.concreteMassKg,b.mass.concreteMassKg,.001);close(a.mass.concreteMassKg,a.mass.netVolumeM3*2400);assert.ok(a.mass.concreteOnlyCentroidMm[2]>2520);assert.ok(a.mass.concreteOnlyCentroidMm[2]<a.bounds.z[1]);}});
test('P25 D side continues panel slope clear of inner wall',()=>{const r=piece('D','LH');for(const z of [2520,2600,2700,2830])assert.ok(panelLeft('D',z)-innerWallX('D',z)>0);close(r.bounds.x[0],panelLeft('D',2520));});
test('P25 shallow A B ends remain explicit unresolved geometry not a released Typical',()=>{assert.ok(piece('A','LH').outerEndHeightMm<42);assert.ok(piece('B','LH').outerEndHeightMm<67);for(const r of model().records){assert.equal(r.productionReleased,false);assert.equal(r.liftingPlan.releasedForLifting,false);assert.equal(r.liftingPlan.anchorCoordinatesMm,null);assert.equal(r.interface.supportSystem,null);assert.equal(r.interface.placementY,null);}assert.deepEqual(model().selectedCandidateIds,[]);assert.equal(checklist().percent,80);assert.equal(checklist().items.find(i=>i.id==='P2-17').status,'IN_PROGRESS');});
test('P25 saved data and checksum manifest match generated artifacts',()=>{const read=f=>JSON.parse(fs.readFileSync(path.join(root,'output/end-infill-p25',f)));assert.deepEqual(read('register.json'),model());assert.deepEqual(read('stage2-checklist.json'),checklist());const m=read('manifest.json');for(const e of [...m.dependencies,...m.files.map(e=>({path:'output/end-infill-p25/'+e.file,sha256:e.sha256}))])assert.equal(createHash('sha256').update(fs.readFileSync(path.join(root,e.path))).digest('hex'),e.sha256);for(const f of ['A','B','D'])for(const x of [400,1000,1490])close(ceiling(f,x),roofInnerZ(f,x));});
