import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import {moments,cross} from './foot-contact-p84.mjs';
const dir='output/foot-demand-p84',reg=JSON.parse(fs.readFileSync(dir+'/register.json')),hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),near=(a,b,t=.001)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
test('complete scoped register and current solver sources',()=>{assert.equal(reg.records.length,24);assert.equal(reg.records.reduce((a,r)=>a+r.scenarioCount,0),216);for(const [p,h]of Object.entries(reg.sourceHashes))assert.equal(hash(p),h);});
for(const row of reg.records)test(row.key+' '+row.tag+' complete wrench and unilateral contact',()=>{
 const m=JSON.parse(fs.readFileSync(dir+'/'+row.file));for(const p of m.inputs)assert.equal(hash(p.path),p.sha256);
 const expectedArea=350*200-4*32/2*11**2*Math.sin(2*Math.PI/32);near(m.plateAreaMm2,expectedArea,1e-5);near(m.polygons.reduce((a,p)=>a+moments(p).A,0),expectedArea,1e-5);
 const g=m.sourceFootReaction,F=g.forceN.map(v=>-v),offset=g.referenceMm.map((v,i)=>v-m.originMm[i]),dm=cross(offset,F);F.forEach((v,i)=>near(v,m.appliedForceN[i]));g.momentNmm.forEach((v,i)=>near(-v+dm[i],m.appliedMomentNmm[i]));
 for(const s of m.scenarios){assert.ok(s.contactAreaMm2>0&&s.contactAreaMm2<m.plateAreaMm2);assert.ok(s.boltTensionsN.every(v=>v>=0));s.residual.forEach(v=>near(v,0,.002));const [fz,mx,my]=s.bedReaction;near(m.appliedForceN[2]+fz-s.boltTensionsN.reduce((a,v)=>a+v,0),0,.002);near(m.appliedMomentNmm[0]+mx-m.bolts.reduce((a,b,i)=>a+b.positionMm[1]*s.boltTensionsN[i],0),0,.002);near(m.appliedMomentNmm[1]+my+m.bolts.reduce((a,b,i)=>a+b.positionMm[0]*s.boltTensionsN[i],0),0,.002);near(s.compressionPatches.reduce((a,p)=>a+moments(p).A,0),s.contactAreaMm2,.001);}
 m.shearEquilibriumResidual.forceN.forEach(v=>near(v,0));near(m.shearEquilibriumResidual.momentNmm,0);assert.equal(m.engineeringApproved,false);assert.equal(m.productionReleased,false);assert.equal(m.stageComplete,false);assert.ok(m.bolts.every(b=>b.verifiedCapacityN===null));
});
for(const f of ['A','B','D'])for(const owner of ['M01','M03'])for(const foot of [1,2])test(`${f} ${owner}-F${foot} mirror`,()=>{const a=JSON.parse(fs.readFileSync(`${dir}/${f}-LH-W01-${owner}-F${foot}.json`)),b=JSON.parse(fs.readFileSync(`${dir}/${f}-RH-W01-${owner}-F${foot}.json`));a.scenarios.forEach((s,i)=>s.boltTensionsN.forEach((v,j)=>near(v,b.scenarios[i].boltTensionsN[j])));});
test('candidate relocates actual hole pair without silently changing current pattern or copying old demands',()=>{for(const row of reg.records){const m=JSON.parse(fs.readFileSync(dir+'/'+row.file)),o=JSON.parse(fs.readFileSync(`${dir}/${row.key}-${row.tag}-option.json`));assert.equal(hash(o.source.path),o.source.sha256);assert.equal(o.geometryStatus,'CANDIDATE_ONLY_NOT_ASSEMBLY_OR_RELEASE_PATH_VERIFIED');near(o.polygons.reduce((a,p)=>a+moments(p).A,0),m.plateAreaMm2,1e-5);assert.equal(o.bolts.filter((b,i)=>Math.abs(b.positionMm[0]-m.bolts[i].positionMm[0])>1).length,2);assert.ok(o.bolts.every(b=>b.baseCaseTensionN===undefined));for(const s of o.scenarios){s.residual.forEach(v=>near(v,0,.002));near(m.appliedForceN[2]+s.bedReaction[0]-s.boltTensionsN.reduce((a,v)=>a+v,0),0,.002);}assert.ok(o.optionMaximumTensionN<o.currentMaximumTensionN);}});
