import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {createHash} from 'node:crypto';import {root} from './build-r02.mjs';
const out=path.join(root,'output/lifting-concept-l01');fs.mkdirSync(out,{recursive:true});
const req=createRequire(import.meta.url);let sharp;try{sharp=req('sharp');}catch{sharp=req('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');}
const sources=['output/tsc-master-p02/TS-C-MASTER-P02.svg','output/ic1-coordination-p03/I-C1-P03.svg','output/ic1-layout-p04/I-C1-P04.svg'];const records=[];
for(const source of sources){let svg=fs.readFileSync(path.join(root,source),'utf8');const h=Number(svg.match(/height="(\d+)"/)[1]);svg=svg.replace(`height="${h}"`,`height="${h+300}"`).replace(`viewBox="0 0 1600 ${h}"`,`viewBox="0 0 1600 ${h+300}"`);
let footer=`<g font-family="Tahoma,Arial,sans-serif"><rect x="20" y="${h}" width="1560" height="285" fill="#fff0d8"/><text x="45" y="${h+36}" font-size="25" fill="#8e4810">L01 / โซนศึกษาตำแหน่งหูยก — ไม่ใช่พิกัดติดตั้งหรือแผนยก</text>`;
const labels=[['H15 / ซีกผนัง–หลังคา','ศึกษาโซนทึบฝั่งผนังและหลังคา','จัดระบบยกคร่อมCGจริง / ระวังพลิกเอียง'],['F15 / แผ่นพื้น','ศึกษาโซนกระจายรอบCGสองทิศ','จำนวนและแรงต่อหูยังไม่กำหนด'],['EP / แผงปิดปลาย','ศึกษาโซนบนเหนือเนื้อทึบข้างช่อง','เหนือประตู225: ยังไม่ยืนยันฝังanchorได้']];
labels.forEach((v,i)=>{const x=45+i*515;footer+=`<rect x="${x}" y="${h+57}" width="495" height="135" rx="8" fill="#fffaf1" stroke="#c69762"/>`;v.forEach((s,j)=>footer+=`<text x="${x+15}" y="${h+88+j*36}" font-size="${j?18:21}" fill="#694d31">${s}</text>`);});
footer+=`<text x="45" y="${h+227}" font-size="20" fill="#873e16">DEM ถอดแบบ / ROT พลิก / ERECT ติดตั้ง ต้องตรวจแยก — ห้ามถือว่าใช้หูชุดเดียวได้ทุกขั้น</text><text x="45" y="${h+260}" font-size="19" fill="#873e16">ยังไม่เลือกจำนวน พิกัด รุ่น หรือกำลังหูยก • ห้ามยกตามภาพนี้ • ดู LIFTING_CONCEPT_L01.md</text></g>`;
svg=svg.replace('</svg>',footer+'</svg>');const id=path.basename(source,'.svg')+'-L01';fs.writeFileSync(path.join(out,id+'.svg'),svg);await sharp(Buffer.from(svg)).png().toFile(path.join(out,id+'.png'));records.push({id,source,sourceHash:createHash('sha256').update(fs.readFileSync(path.join(root,source))).digest('hex'),file:id+'.png',status:'CONCEPT_ZONES_ONLY',releasedForLifting:false});}
fs.writeFileSync(path.join(out,'register.json'),JSON.stringify({id:'L01',records,liftingPlan:{stage:null,castingOrientation:null,massKg:null,cgMm:null,anchorSystem:null,anchorCoordinatesMm:null,quantity:null,ratedCapacity:null,concreteStrengthAtLift:null,rigging:null,localReinforcement:null,reviewer:null,status:'CONCEPT_ZONES_ONLY',releasedForLifting:false}},null,2));console.log('Three revised L01 review boards; no lifting coordinates/capacity released.');
