import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import {root} from './build-r02.mjs';import {model as walls} from './node-wall-p13.mjs';import {model as roofs} from './node-roof-p14.mjs';
export const mapWing=(face,[x,y,z])=>face==='S'?[x,y-1492.5,z]:[3007.5+y,3000-x,z];
export function model(){const w=walls(),r=roofs(),n=w.nodes[0],reg=JSON.parse(fs.readFileSync(path.join(root,'output/typical-review-p05/register.json')));const boxes=[...n.floors.map((f,i)=>({id:`NF${i+1}`,type:f.typicalId,min:f.localMinMm,size:f.dimensionsMm,role:'FLOOR'})),...n.walls.map(a=>({id:a.tag,type:a.typicalId,min:a.min,size:a.size,role:'WALL'})),...r.nodes[0].roofs.map((a,i)=>({id:`NR${i+1}`,type:a.typicalId,min:a.minMm,size:a.dimensionsMm,role:'ROOF'}))];
 const wings=['S','E'].map(face=>({face,halves:['LH','RH'].map(side=>{const g=reg.records.find(v=>v.id===`TS-C-H15-${side}-S00-P05`).geometry;return {id:`${face}-${side}`,type:g.id,profile:g.profile,lengthMm:g.length,vertices0:g.profile.map(([x,z])=>mapWing(face,[x,0,z])),vertices1:g.profile.map(([x,z])=>mapWing(face,[x,g.length,z])),concreteMassKg:g.mass.concreteMassKg};}),floor:{min:face==='S'?[170,-1492.5,0]:[3007.5,170,0],size:face==='S'?[2660,1485,175]:[1485,2660,175]}}));
 return {revision:'P15',id:'N90-C-SE-P15',visibility:'INTERNAL_TEAM',scope:'LOCAL_NODE_PLUS_ONE_SOLID_BAY_PER_OPEN_FACE_NOT_L_C1_FULL_BUILDING',boxes,wings,ports:[{face:'S',normalAxis:'Y',wingEdge:-7.5,nodeEdge:7.5,floorOverlapCrossRange:[195,2830]},{face:'E',normalAxis:'X',wingEdge:3007.5,nodeEdge:2992.5,floorOverlapCrossRange:[170,2805]}].map(p=>({...p,nominalJointGapMm:Math.abs(p.wingEdge-p.nodeEdge),commonFloorEdgeLengthMm:p.floorOverlapCrossRange[1]-p.floorOverlapCrossRange[0],centreStrip:{crossCoordinateMm:1000,wingRoofTopZ:3000,wingRoofBottomZ:2850,nodeRoofTopZ:2850,nodeRoofBottomZ:2675,topStepMm:150,soffitStepMm:175},finishedOpeningMm:null,structuralJoint:null,weatherJoint:null})),interfaceRequirements:['PORTAL_HEAD_AND_JAMBS','INNER_CORNER_POST_OR_ALTERNATIVE_SUPPORT','THRESHOLD_EDGE_25MM_RETURNS','ROOF_FLASHING_AND_DRAINAGE','CROWN_JOINT_CLOSURE','TEMPORARY_BRACING'],roofLevelSelected:false,fullBuildingMassKg:null,engineeringApproved:false,productionReleased:false};}
const tx=(x,y,s,n=19,c='#29495d')=>`<text x="${x}" y="${y}" font-size="${n}" fill="${c}">${s}</text>`;
const ln=(a,b,c='#718ea0',dash=false)=>`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="${c}" stroke-width="1.3" ${dash?'stroke-dasharray="6 4"':''}/>`;
const pg=(p,c='none',stroke='#718ea0')=>`<polygon points="${p.map(v=>v.join(',')).join(' ')}" fill="${c}" stroke="${stroke}" stroke-width="1.4"/>`;
const start=t=>`<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="1300"><rect width="1600" height="1300" fill="#f5f7fa"/><g font-family="Tahoma,Arial,sans-serif">${tx(45,55,t,29)}`;
const end=()=>tx(60,1250,'ตรวจเรขาคณิตเท่านั้น ไม่อนุมัติผลิต/ยก — กรอบรับ จุดยึด ค้ำยัน และระบบกันน้ำยังไม่ออกแบบ',20,'#995b28')+'</g></svg>';
export function assembly(m){let s=start('N90 + TS-C / LOCAL ASSEMBLY · P15');s+=tx(45,100,'8ชิ้นโหนด + 2ช่วงตรงตัวอย่าง (6ชิ้น) — ไม่ใช่อาคาร L ทั้งหลัง — หน่วย mm',21);
 const iso=([x,y,z])=>[330+x*.12-y*.06,840+x*.035-y*.08-z*.15];
 const drawBox=b=>{const [x,y,z]=b.min,[a,c,h]=b.size,p=[[x,y,z],[x+a,y,z],[x+a,y+c,z],[x,y+c,z]],q=p.map(([u,v])=>[u,v,z+h]),col=b.role==='ROOF'?'#bd8543':b.role==='FLOOR'?'#71946b':'#547b99';let v=pg(p.map(iso),'none',col)+pg(q.map(iso),'none',col);for(let i=0;i<4;i++)v+=ln(iso(p[i]),iso(q[i]),col);return v;};
 for(const b of m.boxes)s+=drawBox(b);for(const w of m.wings){s+=drawBox({...w.floor,role:'FLOOR'});for(const h of w.halves){s+=pg(h.vertices0.map(iso),'none','#829bab')+pg(h.vertices1.map(iso),'none','#829bab');for(const i of [0,1,33,34,35,h.vertices0.length-1])s+=ln(iso(h.vertices0[i]),iso(h.vertices1[i]));}}
 s+=tx(55,150,'N90 / NW + NF + NR',22)+tx(150,1090,'S / TS-C ยาวหล่อ1485',21)+tx(1000,930,'E / TS-C ยาวหล่อ1485',21);
 s+=tx(1020,180,'ขอบเขตภาพประกอบ',25);['สีเขียว: พื้น / น้ำตาล: NR','สีน้ำเงิน: NW / เทา: TS-C','3D wireframe พิกัดติดตั้งจริง','ไม่ลบเส้นซ่อน ไม่ใช่ภาพตกแต่ง','S: ช่วง Y−1492.5..−7.5','E: ช่วง X3007.5..4492.5','โหนดกริด0..3000ทั้งX/Y','เหนือNR2850ยังเป็นกรณีศึกษา'].forEach((v,i)=>s+=tx(1020,225+i*41,v,18));
 s+=tx(60,1150,'S/E เปิดเชื่อมโดยไม่ใส่แผงปิดปลาย; ไม่เพิ่มเสาหรือคานสมมติให้ดูเหมือนมีระบบรองรับแล้ว',20,'#995b28');
 s+=tx(60,1190,'ยังไม่มีบัญชีเหล็ก/ชุดTR/อุปกรณ์ยกหรือมวลอาคารครบ ไม่ใช่ลำดับติดตั้งที่อนุมัติ',20);return s+end();}
export function details(m){let s=start('TS-C / TWO-PORT INTERFACE REGISTER · P15');s+=tx(45,100,'01 / รูปตัดตามแนวปีก ณ พิกัดขวาง1000 — อยู่นอกรอยต่อกลางหลังคา20',21);
 const q=([d,z])=>[410+d*.28,570-(z-2400)*.40];s+=pg([[-650,2850],[-7.5,2850],[-7.5,3000],[-650,3000]].map(q),'#bfd8e5')+pg([[7.5,2675],[650,2675],[650,2850],[7.5,2850]].map(q),'#f1d7b3');
 s+=tx(150,300,'TS-C บน3000',20)+tx(150,425,'ใต้2850',19)+tx(540,365,'NR บน2850',20)+tx(540,495,'ใต้2675',19)+tx(340,575,'ช่องตามแนวปีก15',19);
 const notes=['ระดับบนต่าง150 / ท้องหลังคาต่าง175','S: d=Y / E: d=−(X−3000)','NRกับปีกไม่มีผิวสัมผัสตรงที่ถ่ายแรงได้','ช่อง15ไม่ใช่ความกว้างชุดTRที่ออกแบบ','NRอยู่ต่ำกว่า: ต้องพัฒนาทางน้ำที่รอยต่อ','สีส้ม/ฟ้าเป็นคอนกรีต ไม่ใช่แผ่นflashing'];notes.forEach((v,i)=>s+=tx(880,200+i*52,v,20,i>=2?'#995b28':'#29495d'));
 s+=tx(60,665,'02 / บัญชีช่องพื้นที่ต่อถึงกัน — วัดเฉพาะแนวขอบ ไม่ใช่ความกว้างประตู',22);
 m.ports.forEach((p,i)=>{const y=720+i*110;s+=tx(70,y,`${p.face}: gap${p.nominalJointGapMm} / ช่วงขอบร่วม ${p.floorOverlapCrossRange.join('..')} / ยาว${p.commonFloorEdgeLengthMm}`,22)+tx(70,y+38,'ปลายช่องยังเหลื่อม25; กรอบเปิดและงานปิดขอบยังไม่กำหนด จึงไม่ระบุช่องผ่านสุทธิ',18,'#995b28');});
 s+=tx(60,960,'03 / แยกรายการพัฒนาต่อ ห้ามรวมเป็นแผ่นปิดรอยต่อชิ้นเดียว',22);
 ['TR-C-STR: กรอบรับหัวช่อง/ข้างช่อง/มุมร่วม — geometryและจุดยึดยังnull','TR-C-ENV: ปิดช่องหลังคา/ผนัง กันน้ำ การเคลื่อนตัว และทางน้ำ — ยังไม่เลือกระบบ','TR-C-FLR: ขอบพื้นและปลายเหลื่อม25 — ไม่ใช่อุดด้วยวัสดุยาแนวแล้วเสร็จ','TEMP: ค้ำยันและลำดับติดตั้ง / LIFT: ตรวจแยกต่อชิ้นตามL01 ไม่ยกชุด14ชิ้นทั้งชุด'].forEach((v,i)=>s+=tx(65,1008+i*44,v,19));return s+end();}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const out=path.join(root,'output/node-c-p15');fs.mkdirSync(out,{recursive:true});const m=model(),req=createRequire(import.meta.url);let sharp;try{sharp=req('sharp');}catch{sharp=req('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');}const names=[];for(const [id,svg] of [['N90-C-ASSEMBLY-P15',assembly(m)],['N90-C-INTERFACES-P15',details(m)]]){fs.writeFileSync(path.join(out,id+'.svg'),svg);await sharp(Buffer.from(svg)).png().toFile(path.join(out,id+'.png'));names.push(id+'.svg',id+'.png');}fs.writeFileSync(path.join(out,'register.json'),JSON.stringify(m,null,2));names.push('register.json');fs.writeFileSync(path.join(out,'README.md'),['# N90 + TS-C P15','', '- [3D ประกอบเฉพาะจุดมุม](N90-C-ASSEMBLY-P15.png)','- [รูปตัดและบัญชีสองช่องเชื่อม](N90-C-INTERFACES-P15.png)','','8ชิ้นโหนด +2ช่วงตัวอย่าง6ชิ้น ไม่ใช่อาคารLครบ','ช่องตามแนวปีก15 ระดับบนต่าง150 ท้องหลังคาต่าง175 ณแถบราบนอกcrown joint','ขอบพื้นร่วม2635mmไม่ใช่ช่องผ่านสุทธิ; TR-STR/ENV/FLRยังไม่ออกแบบ','ไม่อนุมัติผลิต ยก หรือก่อสร้าง ไม่มีการรันโครงสร้าง',''].join('\n'));names.push('README.md');const hash=p=>createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex');fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify({dependencies:['tools/modular-program/node-c-p15.mjs','tools/modular-program/node-floor-p12.mjs','tools/modular-program/node-wall-p13.mjs','tools/modular-program/node-roof-p14.mjs','output/typical-review-p05/register.json','knowledge/modular-program-r02/decisions.json'].map(p=>({path:p,sha256:hash(p)})),files:names.map(f=>({file:f,sha256:hash('output/node-c-p15/'+f)}))},null,2));console.log({boxes:m.boxes.length,wings:m.wings.length,ports:m.ports});}
