import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {root} from './build-r02.mjs';import {model,records,prism,collisions,exactCollisions,waterZ,capDrop} from './node-cover-p33.mjs';
const near=(a,b,t=1e-6)=>assert.ok(Math.abs(a-b)<t,`${a} vs ${b}`);
const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
function integral(v,faces){let volume=0,c=[0,0,0];for(const f of faces)for(let j=1;j<f.length-1;j++){const a=v[f[0]],b=v[f[j]],d=v[f[j+1]],dv=dot(a,cross(b,d))/6;volume+=dv;c=c.map((n,i)=>n+dv*(a[i]+b[i]+d[i])/4);}return {volume,centroid:c.map(n=>n/volume)};}
test('P33 closed solid mesh volume and CG independently match analytic integration',()=>{for(const r of records()){const t=integral(r.localVerticesMm,r.faces);near(t.volume/1e9,r.mass.netVolumeM3);for(let i=0;i<3;i++)near(t.centroid[i],r.concreteOnlyCentroidLocalMm[i],1e-5);const edge=new Map();for(const face of r.faces)for(let i=0;i<face.length;i++){const a=face[i],b=face[(i+1)%face.length],key=[a,b].sort().join('-');edge.set(key,(edge.get(key)||0)+1);}assert.ok([...edge.values()].every(n=>n===2));}});
test('P33 caps are normal100 not vertical100; maximum lies below 3000',()=>{near(capDrop/Math.sqrt(1+.02**2),100);near(model().checks.maxConcreteZ,2989.7199980004);for(const r of records().filter(r=>r.kind==='CAP')){near(r.globalLevelsMm.bottomAtStart-waterZ(r.originMm[1]),20);near(r.globalLevelsMm.topAtStart-r.globalLevelsMm.bottomAtStart,capDrop);}});
test('P33 exact sloping prisms remove AABB false positives without suppressing real clashes',()=>{assert.equal(collisions(records()).length,2);assert.equal(exactCollisions(records()).length,0);const a=prism('A','TEST',0,0,10,10,0,0,10,10,10),b=prism('B','TEST',5,5,10,10,0,0,10,10,10);assert.equal(exactCollisions([a,b]).length,1);});
test('P33 node roof is replaced not duplicated and gaps remain20/15',()=>{const rs=records(),s=rs.find(r=>r.id.includes('NR-S')),n=rs.find(r=>r.id.includes('NR-N'));near(s.originMm[1]-107.5,20);near(2892.5-s.originMm[0]-s.dimensionsMm[0],20);near(n.originMm[1]-s.originMm[1]-s.dimensionsMm[1],15);assert.equal(rs.length,11);assert.equal(rs.filter(r=>r.kind==='CAP').length,5);});
test('P33 reflected U node preserves positive oriented volume',()=>{const m=model();for(const n of m.nodes)for(const p of n.placements){const expected=m.records.find(r=>r.id===p.typicalId).mass.netVolumeM3;near(integral(p.verticesNodeMm,p.faces).volume/1e9,expected);}});
test('P33 profile mapping explicitly keeps crown and D shoulder absences',()=>{const m=model();assert.equal(m.interfaces.length,8);for(const r of m.interfaces){assert.equal(r.samples.find(p=>p.q===1500).wingOuterZ,null);if(r.family==='D')assert.equal(r.samples.find(p=>p.q===0).wingOuterZ,null);}assert.equal(m.scopeChanges.mainProfilesChanged,false);assert.equal(m.scopeChanges.capOverlapOntoMainRoofMm,0);});
test('P33 approvals are not inferred from mass or geometry',()=>{for(const p of records()){assert.equal(p.supportGeometry,null);assert.equal(p.liftingPlan.anchorCoordinatesMm,null);assert.equal(p.productionReleased,false);}assert.ok(model().pending.length>0);assert.equal(model().drainage.waterproofingApproved,false);});
test('P33 saved register matches generator',()=>assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,'output/node-cover-p33/register.json'))),model()));
