import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';
import {root} from './build-r02.mjs';import {model,inventory,mirrorBox} from './node-mirror-p19.mjs';import {model as prior,polygonProperties} from './node-notch-p18.mjs';import {intersect} from './portal-space-p16.mjs';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7);
test('P19 reflects polygon with positive winding and invariant volume',()=>{const a=prior().records[0],b=model().records[0];assert.ok(polygonProperties(b.polygonXYMm).areaMm2>0);assert.deepEqual(b.polygonXYMm.map(([x,y])=>[2797.5-x,y]).reverse(),a.polygonXYMm);near(a.mass.concreteMassKg,b.mass.concreteMassKg);near(a.concreteOnlyCentroidMm[0]+b.concreteOnlyCentroidMm[0],2797.5);near(a.concreteOnlyCentroidMm[1],b.concreteOnlyCentroidMm[1]);});
test('P19 node polygon coordinates are exact reflected P18 placement',()=>{const a=prior().records[0],b=model().records[0];assert.deepEqual(b.polygonXYMm.map(([x,y])=>[x+7.5,y+7.5]).reverse(),a.polygonXYMm.map(([x,y])=>[3000-(x+195),y+7.5]));const box=prior().pilot.columnSpace;assert.deepEqual(mirrorBox(mirrorBox(box)),box);});
test('P19 floor clears column walls and NF02 and retains20mm proposed clearance',()=>{const m=model(),n=m.node;for(const s of n.remainingSolidsInNodeMm){for(const b of [n.columnSpace,n.nf02,...n.walls])assert.equal(intersect(s,b),null);}assert.equal(intersect(...n.remainingSolidsInNodeMm),null);near(n.remainingSolidsInNodeMm[0].min[0]-200,20);near(n.remainingSolidsInNodeMm[1].min[1]-200,20);near(n.remainingSolidsInNodeMm.reduce((s,b)=>s+b.size.reduce((a,v)=>a*v,1),0)/1e9,m.records[0].mass.netVolumeM3);});
test('P19 wall receiving zones stay within reflected walls without added concrete',()=>{const n=model().node;for(const z of n.wallZones){const b=n.walls.find(b=>b.id===z.existing);assert.ok(z.min.every((v,i)=>v>=b.min[i]&&v+z.size[i]<=b.min[i]+b.size[i]));}});
test('P19 inventory resolves all35 unique tags and image files with genuine mass',()=>{const inv=inventory();assert.equal(inv.entries.length,35);assert.equal(new Set(inv.entries.map(e=>e.id)).size,35);assert.equal(inv.entries.filter(e=>e.scope.startsWith('HISTORICAL')).length,1);for(const e of inv.entries){assert.ok(fs.existsSync(path.join(root,e.preview)),e.preview);assert.ok(e.concreteMassKg>0);assert.equal(e.densityKgM3,2400);assert.equal(e.productionReleased,false);}assert.equal(inv.counts.approvedMoulds,0);});
test('P19 saved data matches and does not claim lifting or whole assembly approval',()=>{const m=model();assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,'output/node-mirror-p19/register.json'))),m);assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,'output/node-mirror-p19/typical-index.json'))),inventory());assert.equal(m.sharedMouldApproved,false);assert.equal(m.wholeNodeMassKg,null);assert.equal(m.records[0].liftingPlan.anchorCoordinatesMm,null);assert.equal(m.node.insertOrRebarTransform,null);assert.equal(m.productionReleased,false);});
