import fs from 'node:fs';import path from 'node:path';import {execFileSync} from 'node:child_process';import {root,hash} from './stage5-p38.mjs';
const out=path.join(root,'output/stage5-update-p53');fs.mkdirSync(out,{recursive:true});
fs.cpSync(path.join(root,'output/concrete-lift-p52'),path.join(out,'concrete-lift-p52'),{recursive:true});
const dev=JSON.parse(fs.readFileSync(path.join(root,'output/stage5-library-p53/register.json')));
for(const r of dev.records)for(const f of r.files){const dest=path.join(out,f.path);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(path.join(root,f.path),dest);}
fs.cpSync(path.join(root,'output/stage5-library-p53'),path.join(out,'stage5-library-p53'),{recursive:true,filter:p=>!p.endsWith('.log')});
for(const name of ['decision-lifting-p52.json','STAGE5_CONTINUATION_P53.md'])fs.copyFileSync(path.join(root,'knowledge/modular-program-r02',name),path.join(out,name));
const tests=['tools/modular-program/concrete-lift-p52.test.mjs','tools/modular-program/table-p51.test.mjs','tools/modular-program/elastic-beam-p48.test.mjs','tools/modular-program/continuous-beam-p49.test.mjs','tools/modular-program/floor-demand-p48.test.mjs','tools/modular-program/floor-workpack-p50.test.mjs','tools/catalogue/mould-review.test.mjs'];
const result=execFileSync(process.execPath,['--test',...tests],{cwd:root,encoding:'utf8'});fs.writeFileSync(path.join(out,'test-results.txt'),result);
fs.writeFileSync(path.join(out,'README.md'),'# ขั้น5 — ชุดส่งต่อ P52/P53\n\n[เปิดภาพและดาวน์โหลด44ชิ้น](concrete-lift-p52/index.html) · [ผลทดสอบ](test-results.txt)\n\nสมมติกำลังคอนกรีตเพียงพอเพื่อพัฒนาแบบตามผู้ใช้ แสดงแนวเหล็กไม่ใส่ขนาด ไม่ใช่แบบอนุมัติยกจริง\n\n## แบบแม่แบบที่มีแล้ว\n\n'+dev.records.filter(r=>r.files.length).map(r=>'### '+r.typicalId+'\n\n'+r.files.map(f=>`- [${path.basename(f.path)}](${f.path})`).join('\n')).join('\n\n')+'\n\n## สถานะ\n\nขั้น5/8ยังไม่ครบ100%: ตัวเลข50%เป็นchecklistเดิม ชุดย่อยภาพการแขวนอิสระ44/44ครบแล้ว; hardwareระดับพัฒนา10/44 ยังมี34setupและงานความแข็งแรง/ระบบพลิก/แบบผลิตค้าง ไม่เริ่มขั้น6 ไม่เปิดcloud ไม่เปลี่ยนภาพเดิม\n\nภาพ/รายงานที่คัดลอกเปิดได้; พิกัดJSONอ้างโครงการต้นทางเพื่อtraceability ไม่ใช่standalone build หรือแบบCNC\n');
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
const allFiles=walk(out);if(allFiles.some(p=>p.endsWith('.log')))throw Error('Private server log must never enter delivery');
const files=allFiles.filter(p=>path.relative(out,p)!=='manifest.json').map(p=>({path:path.relative(out,p).replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:hash(p)}));fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify({revision:'P53',stage:5,stageComplete:false,files,engineeringApproved:false,productionReleased:false},null,2));console.log({files:files.length,tests:result.split('\n').filter(l=>/tests |pass |fail /.test(l))});
