import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {deflateRawSync,inflateRawSync,crc32} from 'node:zlib';
import {root,out,hash} from './stage5-p38.mjs';
const walk=(dir,base='')=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(d=>d.isDirectory()?walk(path.join(dir,d.name),base+d.name+'/'):[base+d.name]);
const files=walk(out).filter(f=>!['manifest.json'].includes(f)).sort();
fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify({revision:'P38',status:'PLANNING_ONLY_NOT_TOOL_FABRICATION',files:files.map(p=>({path:p,bytes:fs.statSync(path.join(out,p)).size,sha256:hash(path.join(out,p))}))},null,2));
const names=[...files,'manifest.json'].sort(),local=[],central=[];let offset=0;
for(const name of names){const raw=fs.readFileSync(path.join(out,name)),data=deflateRawSync(raw),n=Buffer.from(name),crc=crc32(raw)>>>0,l=Buffer.alloc(30);l.writeUInt32LE(0x04034b50,0);l.writeUInt16LE(20,4);l.writeUInt16LE(0x800,6);l.writeUInt16LE(8,8);l.writeUInt16LE(0x5d31,12);l.writeUInt32LE(crc,14);l.writeUInt32LE(data.length,18);l.writeUInt32LE(raw.length,22);l.writeUInt16LE(n.length,26);local.push(l,n,data);const h=Buffer.alloc(46);h.writeUInt32LE(0x02014b50,0);h.writeUInt16LE(20,4);h.writeUInt16LE(20,6);h.writeUInt16LE(0x800,8);h.writeUInt16LE(8,10);h.writeUInt16LE(0x5d31,14);h.writeUInt32LE(crc,16);h.writeUInt32LE(data.length,20);h.writeUInt32LE(raw.length,24);h.writeUInt16LE(n.length,28);h.writeUInt32LE(offset,42);central.push(h,n);offset+=l.length+n.length+data.length;}
const cd=Buffer.concat(central),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(names.length,8);end.writeUInt16LE(names.length,10);end.writeUInt32LE(cd.length,12);end.writeUInt32LE(offset,16);
const zip=path.join(root,'output/PM-STAGE5-P38-PLANNING.zip');fs.writeFileSync(zip,Buffer.concat([...local,cd,end]));
// Independent read-back of compressed entries, CRC and exact file content.
const archive=fs.readFileSync(zip);let pos=0,count=0;while(archive.readUInt32LE(pos)===0x04034b50){const n=archive.readUInt16LE(pos+26),extra=archive.readUInt16LE(pos+28),length=archive.readUInt32LE(pos+18),name=archive.subarray(pos+30,pos+30+n).toString(),start=pos+30+n+extra,raw=inflateRawSync(archive.subarray(start,start+length));assert.equal(crc32(raw)>>>0,archive.readUInt32LE(pos+14));assert.deepEqual(raw,fs.readFileSync(path.join(out,name)));count++;pos=start+length;}assert.equal(count,names.length);
const record={revision:'P38',objectKey:'output/PM-STAGE5-P38-PLANNING.zip',bytes:archive.length,sha256:hash(zip),verifiedEntries:count,engineeringApproved:false,productionReleased:false};fs.writeFileSync(path.join(root,'data/modular-program/r02/mould-package-p38.json'),JSON.stringify(record,null,2));console.log(record);
