import fs from 'node:fs';import path from 'node:path';import {execFileSync} from 'node:child_process';import {root,hash} from './stage5-p38.mjs';
const out=path.join(root,'output/stage5-update-p54');fs.mkdirSync(out,{recursive:true});
for(const folder of ['notched-mould-p54','notched-demand-p54'])fs.cpSync(path.join(root,'output',folder),path.join(out,folder),{recursive:true});
const reg=JSON.parse(fs.readFileSync(path.join(root,'output/notched-mould-p54/register.json')));for(const r of reg.records){const dest=path.join(out,'references',r.side+'-source.json');fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(path.join(root,r.source.path),dest);}
fs.writeFileSync(path.join(out,'test-results.txt'),execFileSync(process.execPath,['--test','tools/modular-program/notched-mould-p54.test.mjs','tools/modular-program/notched-demand-p54.test.mjs','tools/modular-program/elastic-beam-p48.test.mjs','tools/modular-program/continuous-beam-p49.test.mjs'],{cwd:root,encoding:'utf8'}));
fs.copyFileSync(path.join(root,'knowledge/modular-program-r02/STAGE5_CONTINUATION_P54.md'),path.join(out,'KNOWLEDGE.md'));
fs.writeFileSync(path.join(out,'README.md'),'# ขั้น5 — P54 แม่แบบพื้นมุมเว้าสองด้าน\n\n[แบบ3D/แปลน/บัญชีชิ้นและลำดับถอด](notched-mould-p54/README.md) · [ผลแรงและแรงฐาน](notched-demand-p54/README.md) · [ผลทดสอบ](test-results.txt)\n\nเพิ่ม2setup เป็นhardwareระดับพัฒนา12/44; ยังไม่ครบ100%ของขั้น5 ไม่เริ่มขั้น6 ไม่ใช่แบบอนุมัติผลิตหรือยก\n\nต่อชุด: ฐาน1+แบบข้าง6, stock73ชิ้นและอุปกรณ์47ชิ้นรวมพิน2, 15จุดล็อก, ตรวจทางถอด54ช่วง. พบว่าดึงM02ตรง300ชนM03 จึงใช้ถอย20แล้วยก250ก่อนถอดM03\n\nสำเนาsource2ชิ้นอยู่references; JSONยังเก็บproject-relative pathsเพื่อtraceability ไม่ใช่standalone build\n');
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]),files=walk(out).filter(p=>path.relative(out,p)!=='manifest.json').map(p=>({path:path.relative(out,p).replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:hash(p)}));
fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify({revision:'P54',stage:5,stageComplete:false,files,engineeringApproved:false,productionReleased:false},null,2));console.log({files:files.length});
