import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';import {root,keys} from './cap-geometry-p55.mjs';
const out=path.join(root,'output/stage5-update-p56');fs.mkdirSync(out,{recursive:true});
for(const dir of ['cap-geometry-p55','cap-hardware-p56'])fs.cpSync(path.join(root,'output',dir),path.join(out,dir),{recursive:true});
fs.mkdirSync(path.join(out,'references'),{recursive:true});for(const key of keys)fs.copyFileSync(path.join(root,`output/stage5-moulds-p38/MF-N90-${key}-P33-P38/setup.json`),path.join(out,'references',`${key}-source.json`));
const scripts=['cap-geometry-p55.mjs','cap-geometry-p55.test.mjs','cap-boards-p55.mjs','cap-hardware-p56.mjs','cap-hardware-p56.test.mjs','cap-hardware-boards-p56.mjs'];fs.mkdirSync(path.join(out,'source-scripts'),{recursive:true});for(const script of scripts)fs.copyFileSync(path.join(root,'tools/modular-program',script),path.join(out,'source-scripts',script));
fs.copyFileSync(path.join(root,'knowledge/modular-program-r02/STAGE5_CONTINUATION_P56.md'),path.join(out,'KNOWLEDGE.md'));
fs.writeFileSync(path.join(out,'test-results.txt'),execFileSync(process.execPath,['--test','tools/modular-program/cap-geometry-p55.test.mjs','tools/modular-program/cap-hardware-p56.test.mjs'],{cwd:root,encoding:'utf8'}));
fs.writeFileSync(path.join(out,'README.md'),'# ขั้น5 — P55/P56 แม่แบบครอบและแผงปิดขอบ9ชุด\n\nเปิด cap-hardware-p56/index.html สำหรับภาพ3Dและดาวน์โหลด PNG/SVG/JSON แต่ละชุด\nเปิด cap-geometry-p55/index.html สำหรับท่าหล่อ/geometry/ผลแรงดัน\n\nขั้น5ยังไม่ครบ100% มีhardware geometryระดับพัฒนา21/44ชุด ไม่ใช่แบบอนุมัติผลิต. ไม่เปลี่ยนภาพเก่าหรือขั้น6\n\nสคริปต์ที่แนบใช้อ้างอิง ต้องใช้dependenciesและไฟล์ร่วมในโครงการเดิม ไม่ใช่standalone executable\n');
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]),files=walk(out).filter(p=>path.relative(out,p)!=='manifest.json').map(p=>({path:path.relative(out,p).replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')}));fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify({revision:'P56',stage:5,stageComplete:false,files,engineeringApproved:false,productionReleased:false},null,2));console.log({files:files.length});
