import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {createRequire} from 'node:module';import {sha} from './base-thread-candidate-p89.mjs';
const out='output/stage5-update-p89',qa='output/stage5-library-p89/qa';fs.mkdirSync(out,{recursive:true});fs.mkdirSync(qa,{recursive:true});
const sharp=createRequire(import.meta.url)('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
for(const f of ['A','B','D']){const keys=['LH','RH'].flatMap(s=>['S00','W01'].map(v=>`${f}-${s}-${v}`)),tiles=await Promise.all(keys.map(async(k,i)=>({input:await sharp(`output/base-thread-candidate-p89/${k}-board.png`).resize(850,735).toBuffer(),left:(i%2)*850,top:Math.floor(i/2)*735})));await sharp({create:{width:1700,height:1470,channels:3,background:'white'}}).composite(tiles).png().toFile(`${qa}/${f}-contact.png`);}
const files=['knowledge/modular-program-current.json','knowledge/modular-program-r02/STAGE5_CONTINUATION_P89.md','knowledge/modular-program-r02/thread-study-p89.json','output/stage5-library-p89/register.json','tools/modular-program/base-thread-candidate-p89.mjs','tools/modular-program/base-thread-candidate-p89.test.mjs','tools/modular-program/base-thread-boards-p89.mjs','tools/modular-program/catalogue-supplement-p89.mjs','tools/modular-program/package-p89.mjs','tools/catalogue/p89-http.test.mjs','tools/catalogue/mould-data.mjs','tools/catalogue/mould-review.test.mjs','apps/web/src/catalogue/MouldLibrary.tsx','apps/web/src/catalogue/mould.test.tsx'];
for(const p of files){const target=path.join(out,p);fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync(p,target);}
fs.cpSync('output/base-thread-candidate-p89',out+'/output/base-thread-candidate-p89',{recursive:true});
fs.cpSync(qa,out+'/qa',{recursive:true});
for(const [name,args] of [
 ['calculation',['--test','tools/modular-program/base-thread-candidate-p89.test.mjs']],
 ['http',['--test','tools/catalogue/p89-http.test.mjs']],
 ['frontend',['node_modules/vitest/vitest.mjs','run','--config','apps/web/vite.config.ts','apps/web/src/catalogue']],
 ['typecheck',['node_modules/typescript/bin/tsc','--noEmit','-p','apps/web/tsconfig.json']]
]){const p=spawnSync(process.execPath,args,{encoding:'utf8'});fs.writeFileSync(`${out}/${name}-tests.txt`,p.stdout+'\n'+p.stderr);if(p.status!==0)throw Error(name+' failed');console.log(name+' passed');}
fs.writeFileSync(out+'/README.md','# P89 - Base hardware candidate\n\nOpen output/base-thread-candidate-p89/index.html:12 model-derived boards,12 candidate models,12 per-setup schedules,source observations and constraints. This is an unadopted candidate,not a complete connection/mould/fabrication release. P85 remains the historical/current analysis geometry; P86/P88 are NOT revalidated for this smaller washer or longer screw.\n\nSource-code and web supplement for the existing project,not a standalone rebuild. P65/P85/P71/P74/P80 input files remain in their earlier project packages and are SHA-256 referenced. Candidate JSON contains modified base assembly and references its separate web/seam/edge overlays; do not omit those from total geometry. The HTML/PNG report is self-contained for viewing. Native-source standards PDFs and private server logs are not included. No Stage6/7,public deployment or purchasing.\n\nManufacturer calculator results are manually transcribed live UI observations,not a downloadable signed report or independent solver verification. Total insertion and effective full-thread length are distinct. Existing P88 files retain their issued values; the general pitch label is corrected here to M01=250/M03=240mm.\n');
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]),entries=walk(out).filter(p=>path.basename(p)!=='manifest.json').map(p=>({path:path.relative(out,p).replaceAll('\\','/'),bytes:fs.statSync(p).size,sha256:sha(p)}));
if(entries.some(f=>/server-private|\.pdf$/.test(f.path)))throw Error('Private/source reference included');
fs.writeFileSync(out+'/manifest.json',JSON.stringify({revision:'P89',stage:5,stageComplete:false,engineeringApproved:false,productionReleased:false,files:entries},null,2));console.log({files:entries.length,bytes:entries.reduce((s,f)=>s+f.bytes,0)});
