import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {root} from './build-r02.mjs';
import {audit as priorAudit} from './stage2-review-p35.mjs';
import {raster} from './drawing-raster-p36.mjs';
import {exactCollisions} from './node-cover-p33.mjs';

export const out=path.join(root,'output/stage3-designs-p36');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
export const sources=['data/modular-program/r02/catalogue.json','knowledge/modular-segments-r00/placement_grid.json','output/stage2-review-p35/typical-index.json','output/typical-review-p05/register.json','output/abd-typicals-p08/register.json','output/epx-normal-p28/register.json','output/node-level-p31/register.json','output/node-cover-p33/register.json','output/weather-joints-p34/register.json','output/node-notch-p18/register.json','output/node-mirror-p19/register.json','output/stage2-review-p35/audit.json'];
const db=Object.fromEntries(sources.map(p=>[p,read(p)]));
const index=db[sources[2]].entries, byId=new Map(index.map(e=>[e.id,e]));
const catalogue=db[sources[0]].products, grid=db[sources[1]];
export const hash=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const round=(n,d=2)=>Number(n.toFixed(d));
const area=p=>Math.abs(p.reduce((s,a,i)=>{const b=p[(i+1)%p.length];return s+a[0]*b[1]-a[1]*b[0];},0))/2;
const add=(a,b)=>a.map((v,i)=>v+(b[i]||0));
const bbox=pts=>({min:[0,1,2].map(i=>Math.min(...pts.map(p=>p[i]))),max:[0,1,2].map(i=>Math.max(...pts.map(p=>p[i])))});
const mapBay=(b,p)=>b.axis==='Y'?[b.origin[0]*1000+p[0],b.origin[1]*1000+p[1]+7.5,p[2]]:[b.origin[0]*1000+p[1]+7.5,b.origin[1]*1000+3000-p[0],p[2]];
// Sutherland-Hodgman half-plane clipping in profile coordinates. Keeps real voids open.
export function clip(poly,axis,value,greater){const r=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],ia=greater?a[axis]>=value:a[axis]<=value,ib=greater?b[axis]>=value:b[axis]<=value;if(ia)r.push(a);if(ia!==ib){const t=(value-a[axis])/(b[axis]-a[axis]);r.push(a.map((n,j)=>n+(b[j]-n)*t));}}return r;}
// Simplify visual tessellation only; mass and authoritative dimensions come from source records.
function simplify(p,eps=.15){if(p.length<4)return p;const a=p[0],b=p.at(-1),dx=b[0]-a[0],dy=b[1]-a[1],den=dx*dx+dy*dy;let max=0,k=0;for(let i=1;i<p.length-1;i++){const t=den?Math.max(0,Math.min(1,((p[i][0]-a[0])*dx+(p[i][1]-a[1])*dy)/den)):0;const d=Math.hypot(p[i][0]-a[0]-t*dx,p[i][1]-a[1]-t*dy);if(d>max){max=d;k=i;}}return max>eps?[...simplify(p.slice(0,k+1),eps).slice(0,-1),...simplify(p.slice(k),eps)]:[a,b];}
const ccw=poly=>poly.reduce((s,a,i)=>{const b=poly[(i+1)%poly.length];return s+a[0]*b[1]-a[1]*b[0];},0)<0?[...poly].reverse():poly;
function xzFaces(poly,y0,y1){if(poly.length<3||area(poly)<1e-5)return [];poly=ccw(poly);const front=poly.map(([x,z])=>[x,y0,z]),back=poly.map(([x,z])=>[x,y1,z]);return [front,[...back].reverse(),...poly.map((_,i)=>[front[i],back[i],back[(i+1)%poly.length],front[(i+1)%poly.length]])];}
function xyFaces(poly,z0,z1){poly=ccw(poly);const low=poly.map(([x,y])=>[x,y,z0]),high=poly.map(([x,y])=>[x,y,z1]);return [[...low].reverse(),high,...poly.map((_,i)=>[low[i],low[(i+1)%poly.length],high[(i+1)%poly.length],high[i]])];}
function boxFaces(min,size){const [x,y,z]=min,[w,l,h]=size;return xyFaces([[x,y],[x+w,y],[x+w,y+l],[x,y+l]],z,z+h);}
const intervals=(poly,z)=>{const xs=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length];if((a[1]<=z&&b[1]>z)||(b[1]<=z&&a[1]>z))xs.push(a[0]+(b[0]-a[0])*(z-a[1])/(b[1]-a[1]));}xs.sort((a,b)=>a-b);return xs.reduce((r,x,i)=>{if(i%2===0)r.push([x,xs[i+1]]);return r;},[]);};
const faceCut=(p,y0,y1,z=1375)=>intervals(p,z).filter(a=>a[1]-a[0]>1e-7).map(([a,b])=>[[a,y0,z],[b,y0,z],[b,y1,z],[a,y1,z]]);
function record(id){const e=byId.get(id);if(!e)throw Error('Not in P35: '+id);return e;}
function half(f,side){if(f==='C')return db[sources[3]].records.find(r=>r.id===`TS-C-H15-${side}-S00-P05`).geometry.profile;return db[sources[4]].records.find(r=>r.id===`TS-${f}-H15-${side}-S00-P08`).profileXZ;}
const uses={1:'ออฟฟิศ',2:'บ้านพัก',3:'ร้านกาแฟ',4:'รีสอร์ต'};
const profiles={A:'จั่ว / slope 1:5',B:'โค้ง / Ro3900 Ri3750',C:'มุมโค้ง / Ro400 Ri250',D:'คางหมู / ผนังเอียง200'};

// Dimensioned architectural proposals, not final occupancy/MEP specifications.
export function fitout(plan,use){const items=[];const put=(label,x,y,w,l,h=750,kind='FURNITURE')=>items.push({id:`F${String(items.length+1).padStart(2,'0')}`,label,minMm:[x,y,175],sizeMm:[w,l,h],kind,material:null});
 if(plan==='I'){
  if(use===1){put('โต๊ะทำงาน',400,1500,650,1400);put('โต๊ะทำงาน',1950,1500,650,1400);put('ตู้เอกสาร',400,3900,500,1500,1800);put('ประชุมย่อย',1550,4100,900,900);}
  if(use===3){put('เคาน์เตอร์',400,3250,650,2200,900);put('โต๊ะลูกค้า',1900,1400,650,650);put('โต๊ะลูกค้า',1900,2550,650,650);put('ตู้เก็บ',2000,4450,550,1000,900);}
  if(use===2||use===4){put('เตียง',400,1950,1400,2000,550);put(use===2?'ครัวเบา':'มินิบาร์',400,4350,600,1250,900);put('ที่นั่ง',400,650,650,900,800);put('ตู้',2200,800,400,900,1800);put('ห้องน้ำสำรอง',1450,4125,1225,1575,2200,'WET_ROOM');}
 }else{
  put('ห้องน้ำสำรอง',350,4250,1450,1400,2200,'WET_ROOM');
  if(use===1){put('โต๊ะทำงาน',400,800,650,1500);put('โต๊ะทำงาน',1950,800,650,1500);put('ประชุม',3800,4200,1450,950);put('ตู้เอกสาร',3850,5450,1450,200,1700);}
  if(use===3){put('เคาน์เตอร์',400,750,650,1950,900);put('โต๊ะลูกค้า',1900,1000,650,650);put('โต๊ะลูกค้า',3650,4500,750,750);put('โต๊ะลูกค้า',4750,4500,750,750);}
  if(use===2||use===4){put('โซฟา',400,750,700,1600,850);put('ครัวเบา',2000,1000,600,1550,900);put('เตียง',3500,4000,2000,1500,550);put('ตู้',3950,5500,1300,200,1600);}
  if(plan==='U'){
   if(use===1){put('โต๊ะทำงาน',6400,850,650,1550);put('โต๊ะทำงาน',7950,850,650,1550);put('พักคอย',7250,4450,1100,650,850);}
   if(use===3){put('โต๊ะลูกค้า',6400,900,700,700);put('โต๊ะลูกค้า',7900,900,700,700);put('โต๊ะลูกค้า',7150,2100,700,700);put('พักคอย',7100,4550,1100,650,850);}
   if(use===2||use===4){put('เตียง',6400,900,1500,2000,550);put('ตู้',8050,4500,500,1100,1800);put(use===2?'ทำงาน':'แต่งตัว',6450,4400,650,1100);}
  }
 }
 const wet=items.filter(i=>i.kind==='WET_ROOM');
 const partitions=wet.flatMap(r=>{const [x,y]=r.minMm,[w,l]=r.sizeMm;return [{id:r.id+'-W',minMm:[x,y,175],sizeMm:[75,l,2200]},{id:r.id+'-E',minMm:[x+w-75,y,175],sizeMm:[75,l,2200]},{id:r.id+'-N',minMm:[x,y+l-75,175],sizeMm:[w,75,2200]},{id:r.id+'-S1',minMm:[x,y,175],sizeMm:[150,75,2200]},{id:r.id+'-S2',minMm:[x+950,y,175],sizeMm:[w-950,75,2200]}].map(p=>({...p,kind:'LIGHT_PARTITION',material:null}));});
 const doors=wet.map(r=>({id:r.id+'-D',roughWidthMm:800,roughHeightMm:2000,fromMm:[r.minMm[0]+150,r.minMm[1],175],toMm:[r.minMm[0]+950,r.minMm[1],175],type:'SLIDING_PROPOSAL',finishedClearMm:null}));
 return {status:'LAYOUT_PROPOSAL_FOR_USER_STAGE_REVIEW',items,partitions,doors,toiletProvision:wet.length?'WET_ROOM_SPACE_AND_PARTITION_PROPOSAL_FIXTURES_MEP_PENDING':'SHARED_EXTERNAL_TOILET_REQUIRED_NOT_INCLUDED',toiletNote:wet.length?'พื้นที่ห้องน้ำสำรอง มีผนังเบา75/ช่องประตู800 ยังไม่จัดสุขภัณฑ์และท่อ':'สำนักงาน/คาเฟ่ I ต้องมีห้องน้ำส่วนกลางภายนอก ขอบเขตนี้ไม่รวม',finishedFloorZ:null,accessibilityCompliance:null,occupantCapacity:null};
}
function windowChoice(b,side,p,fit){const f=p.family,slope=f==='D'?200/2825:0,x=side==='LH'?slope*(1675-175):3000-slope*(1675-175),mid=mapBay(b,[x,742.5,1675]);
 // Wet rooms are private and solid; do not substitute W01 for a high-level bathroom opening.
 if(fit.items.filter(r=>r.kind==='WET_ROOM').some(r=>mid[0]>=r.minMm[0]-400&&mid[0]<=r.minMm[0]+r.sizeMm[0]+400&&mid[1]>=r.minMm[1]-100&&mid[1]<=r.minMm[1]+r.sizeMm[1]+100))return false;
 if(p.use===1)return (side==='LH'?b.instance.endsWith('01')||b.instance.endsWith('03')||b.instance.endsWith('05'):b.instance.endsWith('02')||b.instance.endsWith('04')||b.instance.endsWith('06'));
 if(p.use===3)return side==='RH'||(b.axis==='X'&&side==='LH');
 if(p.use===2)return side==='LH'||b.axis==='X';
 return !(b.axis==='Y'&&side==='RH'&&b.origin[1]===0);
}
export function product(p){const g=grid[p.plan],instances=[],openings=[],fit=fitout(p.plan,p.use);
 const append=(id,typicalId,kind,faces,cut=[],extra={})=>{const ref=record(typicalId);const r={id:`${p.id}-${id}`,label:id,typicalId,kind,source:ref.source,sourceSha256:ref.sourceSha256,concreteMassKg:ref.concreteMassKg,facesMm:faces,planCutPolygonsMm:cut,boundsMm:bbox(faces.flat()),...extra};instances.push(r);return r;};
 for(const b of g.bays){const tf=v=>mapBay(b,v);for(const side of ['LH','RH']){const isW=windowChoice(b,side,p,fit),variant=isW?'W01':'S00',typicalId=`TS-${p.family}-H15-${side}-${variant}-${p.family==='C'?'P05':'P08'}`,prof=simplify(half(p.family,side));const parts=isW?[[prof,0,292.5],[prof,1192.5,1485],[clip(prof,1,1075,false),292.5,1192.5],[clip(prof,1,2275,true),292.5,1192.5]]:[[prof,0,1485]];
  const r=append(`${b.instance}-${side}`,typicalId,'SHELL',parts.flatMap(([poly,y0,y1])=>xzFaces(poly,y0,y1)).map(face=>face.map(tf)),parts.flatMap(([poly,y0,y1])=>faceCut(poly,y0,y1)).map(face=>face.map(tf)),{bayId:b.instance,axis:b.axis,bayOriginMm:b.origin.map(v=>v*1000),side,variant,normalThicknessMm:150,castLengthMm:1485,transform:{kind:'ROTATION_TRANSLATION',rotationZDeg:b.axis==='Y'?0:-90,translationMm:tf([0,0,0])}});
  if(isW){const slope=p.family==='D'?200/2825:0,points=[[292.5,1075],[1192.5,1075],[1192.5,2275],[292.5,2275]].map(([y,z])=>tf([side==='LH'?slope*(z-175):3000-slope*(z-175),y,z]));openings.push({id:`W${String(openings.length+1).padStart(2,'0')}`,instanceId:r.id,type:'W01',roughWidthMm:900,roughHeightVerticalMm:1200,sillAboveSlabMm:900,cornersMm:points,finishedClearMm:null});}
 }
 const fp=[[170,0],[2830,0],[2830,1485],[170,1485]];append(`${b.instance}-F`,`TS-${p.family}-F15-F01-${p.family==='C'?'P05':'P09'}`,'FLOOR',xyFaces(fp,0,175).map(face=>face.map(tf)),[],{planFootprintMm:fp.map(([x,y])=>tf([x,y,0]).slice(0,2)),slabTopZ:175,thicknessMm:175,transform:{rotationZDeg:b.axis==='Y'?0:-90,translationMm:tf([0,0,0])}});
 }
 for(const [i,e] of db[sources[5]].placements.filter(e=>e.plan===p.plan).entries()){const kind=i===0||p.plan==='U'||[1,3].includes(p.use)?'D01':'S01',ref=db[sources[5]].records.find(r=>r.id===`TS-${p.family}-EPX-${kind}-P28`),prof=simplify(ref.grossOutlineXZ),map=v=>e.axis==='Y'?add(v,e.translationMm):[e.translationMm[0]+v[1],e.translationMm[1]-v[0],v[2]];const parts=kind==='D01'?[clip(prof,0,1000,false),clip(prof,0,2000,true),clip(clip(clip(prof,0,1000,true),0,2000,false),1,2285,true)]:[prof];const r=append(`END${i+1}`,ref.id,'END',parts.flatMap(poly=>xzFaces(poly,0,150)).map(face=>face.map(map)),parts.flatMap(poly=>faceCut(poly,0,150)).map(face=>face.map(map)),{transform:{rotationZDeg:e.rotationZDeg,translationMm:e.translationMm},normalThicknessMm:150,endLocation:e.end});
 if(kind==='D01')openings.push({id:`D${i+1}`,instanceId:r.id,type:'D01',roughWidthMm:1000,roughHeightVerticalMm:2100,baseZ:185,thresholdAboveSlabMm:10,cornersMm:[[1000,0,185],[2000,0,185],[2000,0,2285],[1000,0,2285]].map(map),finishedClearMm:null});}
 const nodes=[];for(const cell of g.cells.filter(c=>c.kind==='node')){const nodeId=`${p.plan}-${cell.id}`,nd=db[sources[6]].nodes.find(n=>n.nodeId===nodeId),mir=nd.openFace==='W',origin=nd.originMm,nodeMap=([x,y,z])=>[origin[0]+(mir?3000-x:x),origin[1]+y,z],worldFaces=faces=>faces.map(f=>{const w=f.map(nodeMap);return mir?w.reverse():w;});nodes.push({id:nodeId,originMm:origin,mirrored:mir});
 // Floor geometry derives from the P18 notch; P19 is its reflected physical type.
 const nf=[[195,7.5],[2780,7.5],[2780,220],[2992.5,220],[2992.5,1492.5],[195,1492.5]],nf2=[[195,1507.5],[2992.5,1507.5],[2992.5,2805],[195,2805]];
 for(const [j,poly] of [nf,nf2].entries()){const id=j===1?'TS-N90-NF02-P12':mir?'TS-N90-NF01-N02-P19':'TS-N90-NF01-N01-P18';append(`${cell.id}-F${j+1}`,id,'FLOOR',worldFaces(xyFaces(poly,0,175)),[],{planFootprintMm:poly.map(([x,y])=>nodeMap([x,y,0]).slice(0,2)),slabTopZ:175,thicknessMm:175,nodeId,transform:{kind:mir?'REFLECT_X3000_THEN_TRANSLATE':'TRANSLATE',translationMm:[...origin,0]}});}
 // P31 already supplies mirrored walls; do not reflect twice.
 for(const w of nd.walls){const map=v=>add(v,[...origin,0]),poly=[[w.min[0],w.min[1],1375],[w.min[0]+w.size[0],w.min[1],1375],[w.min[0]+w.size[0],w.min[1]+w.size[1],1375],[w.min[0],w.min[1]+w.size[1],1375]];append(`${cell.id}-${w.tag}`,w.typicalId,'NODE_WALL',boxFaces(w.min,w.size).map(f=>f.map(map)),[poly.map(map)],{nodeId,thicknessMm:175,transform:{kind:'SOURCE_ORIENTED_BOX_PLUS_TRANSLATION',translationMm:[...origin,0]}});}
 for(const r of db[sources[7]].records){const verts=r.localVerticesMm.map(v=>add(v,r.originMm));append(`${cell.id}-${r.id.replace('TS-N90-','').replace('-P33','')}`,r.id,r.kind,worldFaces(r.faces.map(f=>f.map(i=>verts[i]))),[],{nodeId,normalThicknessMm:r.normalThicknessMm,transform:{kind:mir?'REFLECT_X3000_THEN_TRANSLATE':'TRANSLATE',translationMm:[...origin,0]}});}
 }
 const reservations=nodes.flatMap(n=>db[sources[8]].supportSpaces.map(r=>{const mm=[...r.minMm];if(n.mirrored)mm[0]=3000-mm[0]-r.sizeMm[0];return {id:n.id+'-'+r.id,minMm:add(mm,[...n.originMm,0]),sizeMm:r.sizeMm,kind:'SUPPORT_SPACE_NOT_MEMBER',massKg:null};}));
 const bom=[...new Set(instances.map(r=>r.typicalId))].sort().map(id=>{const rs=instances.filter(r=>r.typicalId===id);return {typicalId:id,quantity:rs.length,unitConcreteMassKg:record(id).concreteMassKg,totalConcreteMassKg:rs.reduce((s,r)=>s+r.concreteMassKg,0),instances:rs.map(r=>r.id)};});
 const mass=instances.reduce((s,r)=>s+r.concreteMassKg,0),footprint=g.polygon.map(p=>p.map(v=>v*1000));
 return {...p,revision:'P36',status:'DIMENSIONED_DEVELOPMENT_LAYOUT_FOR_REVIEW',visibility:'INTERNAL_TEAM',units:'mm',useLabel:uses[p.use],profileLabel:profiles[p.family],footprintMm:footprint,externalDimensionsMm:[Math.max(...footprint.map(p=>p[0])),6000,3000],bayGridMm:1500,instances,openings,nodes,reservations,fitout:fit,bom,
  area:{nominalExternalM2:area(footprint)/1e6,concreteFloorTopM2:instances.filter(r=>r.kind==='FLOOR').reduce((s,r)=>s+area(r.planFootprintMm)/1e6,0),usableFinishedM2:null,basis:'CONCRETE_TOP_EXCLUDES_JOINTS_NOT_USABLE_OR_LETTABLE_AREA'},
  mass:{knownConcreteKg:mass,densityKgM3:2400,wholeBuildingKg:null,liftingDesignMassKg:null,excluded:['SUPPORT_MEMBERS','REBAR','INSERTS','SEALS','GLAZING','FITOUT','SERVICES','FOUNDATIONS','WATERPROOFING_BUILDUP']},
  visualGeometry:{tessellationToleranceMm:.15,massFromAuthoritativeSourceNotDisplayMesh:true},
  dimensions:{floorTopZ:175,wallRoofNormalThicknessMm:150,floorThicknessMm:175,nodeRoofTopZ:nodes.length?2800:null,nodeRoofUndersideZ:nodes.length?2625:null,nodeWallTopZ:nodes.length?2605:null,headSpaceUnderZ:nodes.length?2405:null,nodeClearUnderRoofBeforeFinishesMm:nodes.length?2450:null,headSpaceClearAboveSlabMm:nodes.length?2230:null,castLengthMm:1485,bayJointMm:15,crownJointMm:20,endRoofNormalGapMm:20,endBaseGapMm:10,finishedClearHeightMm:null},
  structuralDesign:null,liftingAnchorDesign:null,revitFile:null,staadFile:null,engineeringApproved:false,productionReleased:false,releaseBlocks:db[sources[11]].releaseBlocks};
}
export const products=()=>catalogue.map(product);

const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const tx=(x,y,s,n=20,c='#254255',anchor='start')=>`<text x="${x}" y="${y}" font-size="${n}" fill="${c}" text-anchor="${anchor}">${esc(s)}</text>`;
const line=(a,b,c='#557080',dash=false)=>`<path d="M${a} L${b}" fill="none" stroke="${c}" stroke-width="1.2" ${dash?'stroke-dasharray="6 5"':''}/>`;
const poly=(ps,c='#d4e1e5',stroke='#587482',width=1)=>`<polygon points="${ps.map(p=>p.map(v=>round(v,3)).join(',')).join(' ')}" fill="${c}" stroke="${stroke}" stroke-width="${width}"/>`;
const rect=(x,y,w,h,c='#e7edf0')=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${c}"/>`;
function dh(a,b,label){return line(a,b)+line([a[0],a[1]-5],[a[0],a[1]+5])+line([b[0],b[1]-5],[b[0],b[1]+5])+tx((a[0]+b[0])/2,a[1]-8,label,16,'#3c5969','middle');}
function dv(a,b,label){return line(a,b)+line([a[0]-5,a[1]],[a[0]+5,a[1]])+line([b[0]-5,b[1]],[b[0]+5,b[1]])+`<text transform="translate(${a[0]-9},${(a[1]+b[1])/2}) rotate(-90)" text-anchor="middle" font-size="16" fill="#3c5969">${esc(label)}</text>`;}
function start(p,n,title){return `<svg xmlns="http://www.w3.org/2000/svg" width="2400" height="1700" viewBox="0 0 2400 1700"><rect width="2400" height="1700" fill="#f7f9fa"/><g font-family="Tahoma,Arial,sans-serif">${rect(0,0,2400,130,'#173c50')}${tx(45,58,p.displayCode+' / '+p.useLabel+' / '+p.profileLabel,32,'#ffffff')}${tx(45,102,title,23,'#b8d9dd')}${tx(2340,60,`P36 · 0${n}/03`,26,'#ffffff','end')}${tx(2340,102,'หน่วย mm · ใช้มิติระบุ ไม่วัดสเกลจากภาพ',19,'#b8d9dd','end')}`;}
function end(){return rect(35,1590,2330,80,'#f7ead6')+tx(55,1622,'มาตรฐานเพื่อพัฒนาและประสานงาน — ไม่อนุมัติผลิต ก่อสร้าง หรือยก · Engineering / production release = false',20,'#8b5428')+tx(55,1655,'มิติช่องเปิดคือช่องคอนกรีต • ผิวสำเร็จ/วงกบ/เหล็ก/ฐาน/จุดต่อยังไม่เลือก • ตรวจข้อจำกัด E01–E06 ใน model.json',19,'#8b5428')+'</g></svg>';}
const colors={SHELL:'#ccd9dd',FLOOR:'#a6bcc5',END:'#bacdd5',NODE_WALL:'#b3cbd0',NODE_ROOF:'#b6cfca',CAP:'#8fbbb6',FASCIA:'#90aaa9'};
function iso(p,box,exploded=false){const offset=r=>exploded?(r.kind==='FLOOR'?0:r.kind==='CAP'?3300:r.kind==='FASCIA'?2200:r.kind==='NODE_ROOF'?1800:650):0;
 const proj=([x,y,z])=>[(x-y)*.866,-(x+y)*.34-z];
 const fsx=p.instances.flatMap(r=>r.facesMm.map(face=>({r,face:face.map(v=>[v[0],v[1],v[2]+offset(r)])})));const all=fsx.flatMap(f=>f.face.map(proj)),xs=all.map(v=>v[0]),ys=all.map(v=>v[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),k=Math.min(box.w/(xmax-xmin),box.h/(ymax-ymin));
 const map=v=>{const q=proj(v);return [box.x+(box.w-(xmax-xmin)*k)/2+(q[0]-xmin)*k,box.y+(q[1]-ymin)*k];};
 const faces=fsx.map(f=>({face:f.face,color:colors[f.r.kind]}));
 if(!exploded)for(const o of p.openings)faces.push({face:o.cornersMm,color:o.type==='W01'?'#82bec9':'#bca487'});
 const img=raster(faces,box.w,box.h,v=>{const q=map(v);return [q[0]-box.x,q[1]-box.y];},([x,y,z])=>x+y-z*.68);
 return `<image x="${box.x}" y="${box.y}" width="${box.w}" height="${box.h}" href="${img}"/>`;
}
function planView(p,box,withFit=true){const w=p.externalDimensionsMm[0],k=Math.min((box.w-150)/w,(box.h-150)/6000),ox=box.x+80,oy=box.y+70+6000*k,map=([x,y])=>[ox+x*k,oy-y*k];let s=poly(p.footprintMm.map(map),'#edf1f2','#748d99');
 for(const r of p.instances.filter(r=>r.kind==='FLOOR'))s+=poly(r.planFootprintMm.map(map),'#e5edef','#bac9cf',.7);
 for(const r of p.instances)for(const q of r.planCutPolygonsMm)s+=poly(q.map(map),'#829ba8','#345465');
 for(const o of p.openings){s+=line(map(o.cornersMm[0]),map(o.cornersMm[1]),'#078c95');const c=o.cornersMm[0].map((v,i)=>(v+o.cornersMm[1][i])/2);s+=tx(...map(c),o.id,15,'#00727e');}
 for(const r of p.reservations){const [x,y]=r.minMm,[a,b]=r.sizeMm;s+=poly([[x,y],[x+a,y],[x+a,y+b],[x,y+b]].map(map),'none','#c08b49',1);}
 if(withFit){for(const r of p.fitout.items){const [x,y]=r.minMm,[a,b]=r.sizeMm;s+=poly([[x,y],[x+a,y],[x+a,y+b],[x,y+b]].map(map),r.kind==='WET_ROOM'?'#cfe4e1':'#dccfb9','#a08d75');const c=map([x+a/2,y+b/2]);s+=tx(c[0],c[1],r.id,17,'#5e5044','middle');}for(const r of p.fitout.partitions){const [x,y]=r.minMm,[a,b]=r.sizeMm;s+=poly([[x,y],[x+a,y],[x+a,y+b],[x,y+b]].map(map),'#567e80');}}
 for(const b of grid[p.plan].bays){const c=map([b.origin[0]*1000+(b.axis==='Y'?1500:750),b.origin[1]*1000+(b.axis==='Y'?750:1500)]);if(!withFit)s+=tx(c[0],c[1],b.instance,16,'#375b6d','middle');}
 s+=dh([ox,oy+55],[ox+w*k,oy+55],`${w} overall`)+dv([ox-48,oy],[ox-48,oy-6000*k],'6000 overall');
 for(let y=0;y<6000;y+=1500)s+=dv([ox-20,oy-y*k],[ox-20,oy-(y+1500)*k],'1500');
 for(let x=0;x<w;x+=3000)s+=dh([ox+x*k,oy+27],[ox+(x+3000)*k,oy+27],'3000');
 s+=line(map([0,200]),map([3000,200]),'#c07333',true)+tx(...map([1500,235]),'A–A',16,'#a45e29');s+=line(map([1450,0]),map([1450,6000]),'#8a7f98',true)+tx(...map([1450,5750]),'B–B',16,'#7a5384');
 if(p.plan!=='I')s+=tx(...map([p.plan==='U'?4500:4500,1500]),'คอร์ต / นอกอาคาร',16,'#66878c','middle');s+=tx(ox+w*k+18,box.y+35,'+Y',18)+line([ox+w*k+25,box.y+70],[ox+w*k+25,box.y+40]);
 return s;
}
function profileData(p){const l=simplify(half(p.family,'LH')),r=simplify(half(p.family,'RH'));return [l,r];}
function section(p,box){const k=Math.min((box.w-100)/3000,(box.h-80)/3000),ox=box.x+55,oy=box.y+box.h-35,map=([x,z])=>[ox+x*k,oy-z*k];let s='';for(const q of profileData(p))s+=poly(q.map(map),'#b4cbd5');s+=poly([[170,0],[2830,0],[2830,175],[170,175]].map(map),'#8ba7b4');s+=dh(map([0,-160]),map([3000,-160]),'3000')+dv(map([-180,0]),map([-180,3000]),'3000 limit');s+=line(map([0,175]),map([3000,175]),'#669a90',true);return s;}
function elevation(p,box,dir){let u,depth;if(dir==='S'){u=v=>v[0];depth=v=>v[1];}if(dir==='N'){u=v=>p.externalDimensionsMm[0]-v[0];depth=v=>-v[1];}if(dir==='W'){u=v=>6000-v[1];depth=v=>v[0];}if(dir==='E'){u=v=>v[1];depth=v=>-v[0];}const length=['S','N'].includes(dir)?p.externalDimensionsMm[0]:6000,k=Math.min((box.w-100)/length,(box.h-60)/3000),ox=box.x+65,oy=box.y+3000*k;const faces=p.instances.flatMap(r=>r.facesMm.map(face=>({face,color:colors[r.kind]})));for(const o of p.openings)faces.push({face:o.cornersMm,color:o.type==='W01'?'#82bec9':'#bca487'});const img=raster(faces,box.w-65,box.h-40,v=>[u(v)*k,3000*k-v[2]*k],depth);let s=`<image x="${ox}" y="${box.y}" width="${box.w-65}" height="${box.h-40}" href="${img}"/>`;s+=dh([ox,oy+24],[ox+length*k,oy+24],`${length}`);for(const z of [0,175,3000])s+=tx(ox-8,oy-z*k+5,`${z}`,14,'#496473','end');return s;}
function longitudinal(p,box){const k=Math.min((box.w-100)/6000,(box.h-85)/3000),ox=box.x+65,oy=box.y+3000*k,map=([y,z])=>[ox+y*k,oy-z*k];let s='';
 // Section plane X=1500 lies inside the 20mm crown joint; offset to X=1450 for a concrete section.
 for(const r of p.instances){for(const f of r.facesMm){const hit=[];for(let i=0;i<f.length;i++){const a=f[i],b=f[(i+1)%f.length];if((a[0]<=1450&&b[0]>1450)||(b[0]<=1450&&a[0]>1450)){const t=(1450-a[0])/(b[0]-a[0]);hit.push([a[1]+(b[1]-a[1])*t,a[2]+(b[2]-a[2])*t]);}}if(hit.length>=2)s+=line(map(hit[0]),map(hit[1]),'#35596d');}}
 for(const r of p.reservations)if(r.minMm[0]<=1450&&r.minMm[0]+r.sizeMm[0]>=1450){const [x,y,z]=r.minMm,[a,l,h]=r.sizeMm;s+=poly([[y,z],[y+l,z],[y+l,z+h],[y,z+h]].map(map),'none','#bd8240');}
 s+=dh(map([0,-170]),map([6000,-170]),'6000')+tx(ox,oy+70,'B–B ตัดจริง X=1450 (เยื้องจากสัน50 เพื่อเห็นเนื้อหลังคา)',16);return s;
}
export function sheet1(p){let s=start(p,1,'01 / แปลนมีมิติ + ภาพ3Dประกอบ + ผังใช้งานเสนอ');s+=tx(50,180,'แปลนตัด Z1375 / ช่องเปิด–กริด–เฟอร์นิเจอร์',23)+planView(p,{x:40,y:190,w:1160,h:1020})+tx(1280,180,'3D จากชิ้นส่วนที่อ้างในบัญชี / ไม่ใช่ภาพสุ่ม',23)+iso(p,{x:1240,y:230,w:1090,h:720});
 s+=tx(1250,990,'กระจกสีฟ้า/บานสีน้ำตาลเป็นผิวเสนอ ไม่มีมวลหรือวัสดุที่เลือก',18)+tx(1250,1030,`กรอบ ${p.externalDimensionsMm[0]} × 6000 × ≤3000 / ${p.area.nominalExternalM2} m² nominal`,23)+tx(1250,1070,`พื้นที่หน้าพื้นคอนกรีต ${p.area.concreteFloorTopM2.toFixed(3)} m² — ไม่ใช่พื้นที่สุทธิ`,20)+tx(1250,1110,`${p.instances.length} ชิ้นคอนกรีต / ≈ ${(p.mass.knownConcreteKg/1000).toFixed(3)} ตัน`,24)+tx(1250,1150,`W01 ${p.openings.filter(o=>o.type==='W01').length} ช่อง / D01 ${p.openings.filter(o=>o.type==='D01').length} ช่อง`,21);
 s+=tx(50,1240,'ผังใช้งาน / ตำแหน่งจากกริด (X,Y) และขนาด (กว้าง×ยาว)',23);p.fitout.items.forEach((r,i)=>{const col=i<7?0:1,j=i%7;s+=tx(55+col*1130,1280+j*35,`${r.id} ${r.label}  (${r.minMm[0]}, ${r.minMm[1]})  ${r.sizeMm[0]}×${r.sizeMm[1]} สูง${r.sizeMm[2]}`,19);});s+=tx(1250,1510,p.fitout.toiletNote,18,'#9a652d')+tx(1250,1545,'สีฟ้า=คอนกรีต / น้ำตาล=เฟอร์นิเจอร์ / เขียว=พื้นที่ห้องน้ำเสนอ',18);return s+end();}
export function sheet2(p){let s=start(p,2,'02 / รูปด้าน4ทิศ + รูปตัด + มิติความหนาและช่องเปิด');for(const [i,d] of ['S','W','N','E'].entries()){const x=45+i%2*1165,y=175+Math.floor(i/2)*420;s+=tx(x,y,`${['ด้านหน้า −Y','ด้านข้าง −X','ด้านหลัง +Y','ด้านข้าง +X'][i]} / ${d}`,23)+elevation(p,{x,y:y+25,w:1115,h:350},d);}
 s+=tx(45,1040,'A–A หน้าตัดช่วงทึบ / ไม่ผ่านช่องหน้าต่าง',22)+section(p,{x:40,y:1055,w:550,h:460});s+=tx(640,1040,'B–B ตามยาวปีกหลัก',22)+longitudinal(p,{x:620,y:1080,w:1100,h:360});
 const texts=['ผนัง–หลังคา t150 ตั้งฉากผิว','พื้น t175 / ผิวบน Z175','ชิ้นหล่อยาว1485 / กริด1500','รอยต่อช่วง15 / สันกลาง20','W01 900×1200 แนวดิ่ง','ธรณี W01 Z1075 / หัว Z2275','D01 1000×2100 / ฐาน Z185','EPX t150 / ช่องฐาน10 / บน20',...(p.nodes.length?['โหนด: NRบน2800 / ใต้2625','NWบน2605 / t175','ครอบสูงสุด2989.72 / t100','ช่องใต้หัวสำรอง2230 ก่อนตกแต่ง']:['ไม่มีโหนดใน Type I'])];texts.forEach((t,i)=>s+=tx(1780,1050+i*35,t,18));s+=tx(650,1535,'B–B ไม่ใช่แบบระบบรองรับ: กล่องสีน้ำตาลเป็นพื้นที่สำรอง ไม่ใช่คานที่ออกแบบแล้ว',18,'#9a652d');return s+end();}
export function sheet3(p){let s=start(p,3,'03 / ภาพแยกกลุ่มชิ้นงาน + บัญชี Typical / จำนวน / น้ำหนัก');s+=tx(50,180,'แยกระดับเพื่ออ่านชิ้นงานเท่านั้น — ไม่ใช่ลำดับยก',23)+iso(p,{x:45,y:235,w:1040,h:875},true);s+=tx(1160,180,'Typical revision',20)+tx(1820,180,'จำนวน',20)+tx(1930,180,'kg/ชิ้น',20)+tx(2140,180,'kg/รวม',20);
 p.bom.forEach((r,i)=>{const y=225+i*39;if(i%2===0)s+=rect(1145,y-24,1190,36,'#e9eff2');s+=tx(1160,y,r.typicalId,18)+tx(1830,y,r.quantity,18)+tx(1930,y,r.unitConcreteMassKg.toFixed(2),18)+tx(2140,y,r.totalConcreteMassKg.toFixed(2),18);});const yy=250+p.bom.length*39;s+=tx(1160,yy,`รวม ${p.instances.length} ชิ้น / ${p.mass.knownConcreteKg.toFixed(2)} kg คอนกรีต`,23)+tx(1160,yy+38,'ρ2400 kg/m³ เป็นฐานประมาณ ยังไม่ใช่น้ำหนักอาคารหรือออกแบบยก',18);
 s+=tx(55,1200,'การต่อและรหัสชิ้นงาน',23);const notes=[`กริด1.50ม. / ซีก LH–RH / รอยต่อช่วง15 / สัน20 / ความหนาหลัก150`,`พื้นF15แยกจากผนัง–หลังคา; ผนังถ่ายลงฐานโดยตรง LP-A`,`แผงปลายใช้ EPX-P28 เท่านั้น ไม่ใช้ EP/UI รุ่นเก่ารวมซ้ำ`,p.nodes.length?`โหนด ${p.nodes.map(n=>n.id).join(', ')}: ต่อด้วยขอบผนังร่วม WALL_SHARED`:'I ไม่มีชุดโหนด / ช่องปลายเลือกตามแปลนใช้สอย',p.nodes.length?'ต่อโหนดละ17ชิ้น: พื้น2 ผนัง4 NR2 ครอบ5 แผงปิด4':'หูยก: อ้างโซนศึกษาของTypical ยังไม่มีจุดติดตั้งที่อนุมัติ',p.nodes.length?'U-N02 ใช้NF01-N02 และสะท้อนP33 ไม่สะท้อนซ้ำผนังP31':'หลังคา150 พื้น175 แผงปลาย150 — เป็นขนาดพัฒนา',`บัญชีรายชิ้น/transform/ช่องเปิด ดู model.json และ SCHEDULE.md`];notes.forEach((t,i)=>s+=tx(55,1242+i*43,t,19));s+=tx(1160,1450,'ไม่รวมมวล: เหล็ก โครงรองรับ อุปกรณ์ ซีล กระจก ตกแต่ง และฐาน',19,'#9a652d')+tx(1160,1490,'หูยก DEM / ROT / ERECT ยังต้องออกแบบก่อนใช้จริง',19,'#9a652d')+tx(1160,1530,'รายการค้างไม่ถูกรวมเป็นชิ้นคอนกรีตที่มีมวลศูนย์',19,'#9a652d');return s+end();}

export function meshVolume(faces){return Math.abs(faces.reduce((s,f)=>s+f.slice(1,-1).reduce((t,b,i)=>{const a=f[0],c=f[i+2];return t+(a[0]*(b[1]*c[2]-b[2]*c[1])+a[1]*(b[2]*c[0]-b[0]*c[2])+a[2]*(b[0]*c[1]-b[1]*c[0]))/6;},0),0))/1e9;}
const orient=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);
function polygonsOverlap(a,b){const inside=(p,poly)=>{let c=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const v=poly[i],w=poly[j];if((v[1]>p[1])!==(w[1]>p[1])&&p[0]<(w[0]-v[0])*(p[1]-v[1])/(w[1]-v[1])+v[0])c=!c;}return c;};if(a.some(p=>inside(p,b))||b.some(p=>inside(p,a)))return true;for(let i=0;i<a.length;i++)for(let j=0;j<b.length;j++){const v=a[i],w=a[(i+1)%a.length],x=b[j],y=b[(j+1)%b.length];if(orient(v,w,x)*orient(v,w,y)<-1e-6&&orient(x,y,v)*orient(x,y,w)<-1e-6)return true;}return false;}
export function spatialAudit(p){const candidates=[],errors=[];for(let i=0;i<p.instances.length;i++)for(let j=i+1;j<p.instances.length;j++){const a=p.instances[i],b=p.instances[j];if(![0,1,2].every(k=>Math.min(a.boundsMm.max[k],b.boundsMm.max[k])-Math.max(a.boundsMm.min[k],b.boundsMm.min[k])>1e-6))continue;let method,clash=true;if(a.kind==='SHELL'&&b.kind==='END'){
 const originalShell=simplify(half(p.family,a.side)),end=db[sources[5]].records.find(r=>r.id===b.typicalId);const coord=v=>a.axis==='Y'?[v[0]-a.bayOriginMm[0],v[2]]:[a.bayOriginMm[1]+3000-v[1],v[2]];
 // Use world end vertices to retain placement errors; its gross hull includes the door void conservatively.
 const endWorld=end.grossOutlineXZ.map(([x,z])=>b.transform.rotationZDeg===0?[b.transform.translationMm[0]+x,b.transform.translationMm[1],z]:[b.transform.translationMm[0],b.transform.translationMm[1]-x,z]);
 clash=polygonsOverlap(originalShell,simplify(endWorld.map(coord)));method='PROJECTED_POLYGON_END_GROSS_VS_SHELL_ACTUAL_WORLD_ALIGNMENT';
 }else if(a.kind==='CAP'&&b.kind==='FASCIA'&&a.nodeId===b.nodeId){const aa=db[sources[7]].records.find(r=>r.id===a.typicalId),bb=db[sources[7]].records.find(r=>r.id===b.typicalId);clash=exactCollisions([aa,bb]).length>0;method='EXACT_LINEAR_PRISMS_COMMON_NODE_RIGID_OR_REFLECTED_TRANSFORM';}
 if(clash)errors.push('UNRESOLVED_OR_POSITIVE_INTERSECTION:'+a.label+':'+b.label);candidates.push({a:a.label,b:b.label,method:method||'UNCLASSIFIED',positiveIntersection:clash});}
 return {candidatePairs:candidates,errors,scope:'KNOWN_CONCRETE_ONLY_NOT_FITOUT_MEP_OR_CONNECTIONS'};}
export function auditProduct(p){const errors=[];const expected={I:14,L:31,U:54}[p.plan];if(p.instances.length!==expected)errors.push('PIECE_COUNT');if(new Set(p.instances.map(r=>r.id)).size!==expected)errors.push('DUPLICATE_ID');for(const r of p.instances){if(!byId.has(r.typicalId))errors.push('STALE_TYPICAL');if(Math.abs(r.concreteMassKg-record(r.typicalId).concreteMassKg)>1e-7)errors.push('SOURCE_MASS');if(r.boundsMm.min.some((v,i)=>v<-.001)||r.boundsMm.max.some((v,i)=>v>p.externalDimensionsMm[i]+.001))errors.push('ENVELOPE:'+r.id);if(r.facesMm.flat().some(v=>v.some(n=>!Number.isFinite(n))))errors.push('INVALID_COORDINATE');if(Math.abs(meshVolume(r.facesMm)*2400-r.concreteMassKg)>.5)errors.push('MESH_SOURCE_VOLUME:'+r.id);}
 if(Math.abs(p.bom.reduce((s,r)=>s+r.totalConcreteMassKg,0)-p.mass.knownConcreteKg)>1e-6)errors.push('BOM_MASS');
 for(const o of p.openings){if(!p.instances.some(r=>r.id===o.instanceId))errors.push('OPENING_OWNER');if(Math.abs(Math.hypot(o.cornersMm[1][0]-o.cornersMm[0][0],o.cornersMm[1][1]-o.cornersMm[0][1])-o.roughWidthMm)>1e-5)errors.push('OPENING_WIDTH');if(o.finishedClearMm!==null)errors.push('UNSUPPORTED_FINISHED_CLEAR');}
 if(p.engineeringApproved||p.productionReleased||p.revitFile||p.staadFile)errors.push('UNSUPPORTED_RELEASE_OR_NATIVE_ARTIFACT');
 // Fit-out boxes must remain within the conservative internal floor envelope and away from D's inclined wall at item-top height.
 const inPoly=(x,y,poly)=>{let c=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>y)!==(b[1]>y)&&x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0])c=!c;}return c;};
 for(const r of p.fitout.items){const [x,y]=r.minMm,[w,l,h]=r.sizeMm;for(const [xx,yy] of [[x,y],[x+w,y],[x+w,y+l],[x,y+l]])if(!inPoly(xx,yy,p.footprintMm))errors.push('FITOUT_OUTSIDE:'+r.id);for(const b of grid[p.plan].bays){const bx=b.origin[0]*1000,by=b.origin[1]*1000;const along=b.axis==='Y'?[y-by,y+l-by]:[x-bx,x+w-bx];if(Math.min(along[1],1500)-Math.max(along[0],0)<=0)continue;const transverse=b.axis==='Y'?[x-bx,x+w-bx]:[3000-(y+l-by),3000-(y-by)];if(Math.min(transverse[1],3000)-Math.max(transverse[0],0)<=0)continue;const inner=p.family==='D'?150.37544056+200/2825*h:150;if(transverse[0]<inner-.1||transverse[1]>3000-inner+.1)errors.push('FITOUT_WALL_CLEARANCE:'+r.id);}}
 for(let i=0;i<p.fitout.items.length;i++)for(let j=i+1;j<p.fitout.items.length;j++){const a=p.fitout.items[i],b=p.fitout.items[j];if([0,1].every(k=>Math.min(a.minMm[k]+a.sizeMm[k],b.minMm[k]+b.sizeMm[k])-Math.max(a.minMm[k],b.minMm[k])>0))errors.push('FITOUT_OVERLAP:'+a.id+':'+b.id);}
 const spatial=spatialAudit(p);errors.push(...spatial.errors);return {productId:p.id,errors:[...new Set(errors)],corePieces:p.instances.length,knownConcreteKg:p.mass.knownConcreteKg,nominalAreaM2:p.area.nominalExternalM2,spatial,checks:['44_CURRENT_REFERENCE_MEMBERSHIP','INSTANCE_IDS_COUNTS','SOURCE_MASS_AND_BOM_SUM','INDEPENDENT_ORIENTED_FACE_VOLUME_WITHIN_0_5_KG_PER_PIECE','ENVELOPE_3000_INCLUDING_CAPS','OPENING_WIDTH_AND_OWNER','FITOUT_BOXES_AND_INCLINED_D_WALL_CLEARANCE','NATIVE_FILES_AND_APPROVALS_REMAIN_NULL_FALSE'],limitations:['NOT_STRUCTURAL_OR_CODE_VERIFICATION','SOURCE_NODE_EXACT_COLLISION_AUDIT_REUSED_SEPARATELY','FINISHES_DOOR_FRAMES_MEP_AND_ACTUAL_BEARINGS_UNKNOWN','DISPLAY_TESSELLATION_NOT_EXACT_SOLVER_MESH']};}
function schedule(p){return [`# ${p.displayCode} — บัญชีประกอบ P36`, '',`[01 แปลนและ3D](01-PLAN-3D.png) · [02 รูปด้าน/ตัด](02-ELEVATIONS-SECTIONS.png) · [03 ชิ้นงาน](03-ASSEMBLY-SCHEDULE.png) · [ข้อมูลโมเดล](model.json)`, '',`กรอบ${p.externalDimensionsMm.join('×')}mm / nominal${p.area.nominalExternalM2}m² / หน้าพื้นคอนกรีต${p.area.concreteFloorTopM2.toFixed(4)}m² ไม่ใช่พื้นที่สุทธิ`, '',`คอนกรีต${p.instances.length}ชิ้น รวม${p.mass.knownConcreteKg.toFixed(3)}kg ที่2400kg/m³ ไม่รวมเหล็ก/อุปกรณ์/โครงรองรับ/ตกแต่ง`, '', '## บัญชีรายชิ้น','', '| ชิ้น | Typical | kg | กรอบต่ำสุด XYZ mm | กรอบสูงสุด XYZ mm |','|---|---|---:|---|---|',...p.instances.map(r=>`| ${r.label} | ${r.typicalId} | ${r.concreteMassKg.toFixed(3)} | ${r.boundsMm.min.map(v=>round(v)).join(', ')} | ${r.boundsMm.max.map(v=>round(v)).join(', ')} |`),'','พิกัดกรอบไม่ใช่local originสำหรับRevit: ใช้facesMm/transformและsource revisionในJSON ไม่บวกoriginซ้ำ','', '## ช่องเปิด — คอนกรีตไม่ใช่ช่องผ่านสุทธิ','','| ID | เจ้าของ | รู | มุมล่างต้น XYZ | มุมล่างปลาย XYZ |','|---|---|---|---|---|',...p.openings.map(o=>`| ${o.id} | ${o.instanceId} | ${o.type} ${o.roughWidthMm}×${o.roughHeightVerticalMm} | ${o.cornersMm[0].map(v=>round(v)).join(', ')} | ${o.cornersMm[1].map(v=>round(v)).join(', ')} |`),'',p.fitout.toiletNote,'','## ข้อจำกัดที่ยังต้องส่งต่อ','','- ผังใช้งานและผนังเบาเป็นข้อเสนอให้ผู้ใช้ตรวจ ไม่ใช่แบบอนุญาตหรือแบบงานระบบ','- D01 ธรณีคอนกรีตสูงกว่าพื้น10mm; ยังไม่กำหนดวงกบ/ธรณี/พื้นสำเร็จ จึงไม่อ้างช่องผ่านสุทธิ','- ความสูงเป้าหมาย3000ไม่รับรองความสูงใช้สอยตามกฎหมายแต่ละกิจกรรม ดู E05','- L/U มีหัวสำรอง200ลึก ใต้หัว2405 = 2230เหนือพื้น175 ก่อนตกแต่ง ไม่ใช่ขนาดคานที่ออกแบบแล้ว','- น้ำหนักอาคารครบ/น้ำหนักยก พิกัดหูยก และกำลังจุดต่อยังnull; LP-Aผนังลงฐานแยกพื้น','- งานกันน้ำ/รางยื่นเหนือกรอบด้าน+Y สูงสุด450ในแนวราบเป็นพื้นที่สำรองP34 ไม่รวมใน18/27/45m²','- ไม่สร้างช่องเจาะท่อ/พื้นใหม่โดยอัตโนมัติ MEPต้องประสานก่อนแบบผลิต','- native RVT/STD ยังไม่สร้างในขั้น3 ต้องทำในขั้น6/7ตามลำดับ','','## จุดตรวจปล่อยงานที่ยังเปิด','',...p.releaseBlocks.map(r=>`- ${r.id}: ${r.issue}`),''].join('\n');}

export async function build(){fs.mkdirSync(out,{recursive:true});const ps=products(),qa=ps.map(auditProduct),prior=priorAudit();if(qa.some(q=>q.errors.length)||prior.errors.length)throw Error(JSON.stringify({errors:qa.filter(q=>q.errors.length),prior:prior.errors}));const req=createRequire(import.meta.url);let sharp;try{sharp=req('sharp');}catch{sharp=req('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');}
 for(const p of ps){const dir=path.join(out,p.displayCode);fs.mkdirSync(dir,{recursive:true});for(const [name,fn] of [['01-PLAN-3D',sheet1],['02-ELEVATIONS-SECTIONS',sheet2],['03-ASSEMBLY-SCHEDULE',sheet3]]){const svg=fn(p);fs.writeFileSync(path.join(dir,name+'.svg'),svg);await sharp(Buffer.from(svg)).png().toFile(path.join(dir,name+'.png'));}fs.writeFileSync(path.join(dir,'model.json'),JSON.stringify(p,null,2));fs.writeFileSync(path.join(dir,'SCHEDULE.md'),schedule(p));console.log('Generated '+p.displayCode);}
 const summary={revision:'P36',stage:3,status:'GENERATED_PENDING_VISUAL_AND_PACKAGE_QA',products:ps.map(p=>({id:p.id,displayCode:p.displayCode,plan:p.plan,family:p.family,use:p.use,revision:p.revision,pieceCount:p.instances.length,knownConcreteKg:p.mass.knownConcreteKg,nominalAreaM2:p.area.nominalExternalM2,concreteFloorTopM2:p.area.concreteFloorTopM2,model:p.displayCode+'/model.json',schedule:p.displayCode+'/SCHEDULE.md',sheets:['01-PLAN-3D','02-ELEVATIONS-SECTIONS','03-ASSEMBLY-SCHEDULE'].map(n=>({png:p.displayCode+'/'+n+'.png',svg:p.displayCode+'/'+n+'.svg'})),revitFile:null,staadFile:null})),engineeringApproved:false,productionReleased:false};fs.writeFileSync(path.join(out,'catalogue.json'),JSON.stringify(summary,null,2));fs.writeFileSync(path.join(out,'audit.json'),JSON.stringify({scope:'48_DEVELOPMENT_DESIGNS',products:qa,sourceNodeAudit:prior,geometryErrors:qa.reduce((s,q)=>s+q.errors.length,0),visualReview:'PENDING',engineeringApproved:false,productionReleased:false},null,2));
 for(const plan of ['I','L','U'])for(const num of ['01-PLAN-3D','02-ELEVATIONS-SECTIONS','03-ASSEMBLY-SCHEDULE']){const pp=ps.filter(p=>p.plan===plan),thumbs=await Promise.all(pp.map(p=>sharp(path.join(out,p.displayCode,num+'.png')).resize(600,425).toBuffer()));await sharp({create:{width:2400,height:1700,channels:3,background:'#fff'}}).composite(thumbs.map((input,i)=>({input,left:i%4*600,top:Math.floor(i/4)*425}))).png().toFile(path.join(out,`CONTACT-${plan}-${num}.png`));}
 fs.writeFileSync(path.join(out,'README.md'),['# ขั้น3/8 — 48แบบมีมิติ P36','','ชุดแบบเพื่อพัฒนาและตรวจ ไม่อนุมัติผลิต/ก่อสร้าง/ยก ภาพจากgeometryอ้างTypical P35 ไม่ใช่RVTหรือผลSTAAD','','แต่ละแบบมี3แผ่นPNGและSVG + model.json + บัญชีรายชิ้น/ช่องเปิด พร้อมตำแหน่งและน้ำหนัก','','| สินค้า | กลุ่ม | ชิ้นคอนกรีต | ตันเฉพาะคอนกรีต | แบบ |','|---|---|---:|---:|---|',...ps.map(p=>`| ${p.displayCode} | ${p.useLabel} | ${p.instances.length} | ${(p.mass.knownConcreteKg/1000).toFixed(3)} | [แปลน/3D](${p.displayCode}/01-PLAN-3D.png) · [รูปด้าน/ตัด](${p.displayCode}/02-ELEVATIONS-SECTIONS.png) · [ประกอบ/บัญชี](${p.displayCode}/03-ASSEMBLY-SCHEDULE.png) · [ข้อมูล](${p.displayCode}/SCHEDULE.md) |`),'','## วิธีอ่าน','','- XYZเป็นmm / +Yคือทิศอ้างอิงแปลน ไม่ใช่ทิศเหนือภูมิศาสตร์ของsite','- พื้นที่nominal18/27/45ไม่ใช่พื้นที่สุทธิ ส่วนคอร์ตไม่นับในพื้นที่อาคาร','- ภาพ01ตัดZ1375ผ่านW01 แสดงสัญลักษณ์ช่องเปิด ไม่ใช่ความหนากระจกที่เลือก','- ภาพ02 B–BตัดX1450 ไม่ใช่กลางรอยต่อสันX1500; กล่องหัวเส้นสีน้ำตาลคือพื้นที่สำรอง','- ภาพ03แยกระดับเพื่อดูชิ้น ไม่ใช่ลำดับประกอบ ยก หรือการค้ำยันที่อนุมัติ','- ผังใช้สอยเป็นข้อเสนอ: I-office/cafeพึ่งห้องน้ำส่วนกลางนอกอาคาร; home/resortและL/Uมีพื้นที่ห้องน้ำ/ผนังเบาเสนอ ยังไม่จัดสุขภัณฑ์ ท่อ และขออนุญาต','- ช่องผ่านจริงและusable areaหลังตกแต่งยังnull ไม่ใช้ค่าศูนย์แทน; พื้นคอนกรีตมีรอยต่อและพื้นที่ที่ต้องรองรับ/ปิดช่องเพิ่ม','- 44Typicalคือtag/revision ไม่ใช่44ชิ้นต่อหลังหรือ44แม่แบบผลิต','- เก็บวัสดุและแรงอัดล่วงหน้ายังไม่เลือก; ผลเดิมไม่โอนเป็นPASSให้48แบบนี้','- ไม่แก้เว็บในขั้น3; packageนี้ใช้ส่งต่อขั้น4เมื่อผู้ใช้สั่ง','','## พื้นที่รองรับและกันน้ำที่ยังต้องพัฒนา','','อ้างP34: WALL_SHARED, หัวกรอบ200ลึกแบบspace-only, ครอบฝั่งโหนด, ราง/ท่อ/น้ำล้นด้าน+Yยื่นนอกกรอบสูงสุด450mm มวลยังไม่ทราบ อย่านับเป็นชิ้นคอนกรีตหรือปิดช่องด้วยวัสดุที่ยังไม่ออกแบบ','','## สถานะตรวจ','','ดู audit.json, stage3-checklist.json, visual-review.json และ manifest.json หลักฐานแยกจากengineering/production approval','',...ps[0].releaseBlocks.map(r=>`- ${r.id}: ${r.issue}`),''].join('\n'));
 fs.writeFileSync(path.join(out,'dependencies.json'),JSON.stringify({revision:'P36',sources:sources.map(p=>({path:p,sha256:hash(path.join(root,p))})),generator:{path:'tools/modular-program/stage3-p36.mjs',sha256:hash(fileURLToPath(import.meta.url))}},null,2));return summary;
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))await build();
