import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {createHash} from 'node:crypto';import {root} from './build-r02.mjs';import {index,audit,checklist} from './stage2-review-p35.mjs';
const out=path.join(root,'output/stage2-review-p35');
test('P35 current44 references remove obsolete NR01 instead of double counting',()=>{const m=index();assert.equal(m.entries.length,44);assert.ok(!m.entries.some(e=>e.id==='TS-N90-NR01-P31'));assert.equal(m.entries.filter(e=>e.id.endsWith('P33')).length,11);assert.equal(new Set(m.entries.map(e=>e.id)).size,44);});
test('P35 actual node solids floors and support spaces have no intersections including mirror',()=>{const a=audit();assert.deepEqual(a.errors,[]);assert.deepEqual(a.nodeConcreteWithSupportSpaceIntersections,[]);assert.deepEqual(a.reflectedNodeIntersections,[]);assert.equal(a.floorNotchAndP2Base0Included,true);assert.ok(a.maxNodeConcreteZ<=3000);});
test('P35 mass includes17 known parts but excludes unresolved members and finishes',()=>{const a=audit();assert.equal(a.concreteMass.nodeKnownPartCount,17);assert.ok(Math.abs(a.concreteMass.nodeKnownPartsKg-13299.03715794205)<1e-6);assert.equal(a.concreteMass.completeNodeMassKg,null);assert.equal(a.productionReleased,false);});
test('P35 all20 development deliverables complete without granting stage3 or production',()=>{const c=checklist();assert.equal(c.items.length,20);assert.ok(c.items.every(i=>i.status==='DONE'));assert.equal(c.percent,100);assert.equal(c.nextStageAuthorized,false);assert.equal(c.stageStatus,'AWAITING_USER_STAGE_REVIEW');assert.ok(audit().releaseBlocks.some(b=>b.id==='E05'));});
test('P35 package contents match all recorded hashes',()=>{const manifest=JSON.parse(fs.readFileSync(path.join(out,'manifest.json')));for(const f of manifest.files){const resolved=path.resolve(out,f.path);assert.ok(resolved.startsWith(path.resolve(out)+path.sep));const h=createHash('sha256').update(fs.readFileSync(resolved)).digest('hex');assert.equal(h,f.sha256,f.path);}});
test('P35 review links resolve within supplied package',()=>{const md=fs.readFileSync(path.join(out,'README.md'),'utf8');for(const m of md.matchAll(/\]\((assets\/[^)]+)\)/g))assert.ok(fs.existsSync(path.join(out,m[1])),m[1]);});
test('P35 saved audit index and checklist reproduce current sources',()=>{for(const [file,obj] of [['typical-index.json',index()],['audit.json',audit()],['stage2-checklist.json',checklist()]])assert.deepEqual(JSON.parse(fs.readFileSync(path.join(out,file))),obj);});
