import fs from 'node:fs';import {test} from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const read=p=>JSON.parse(fs.readFileSync(p));const sha=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const volume=c=>{let a=0;for(let i=0;i<c.poly.length;i++){const p=c.poly[i],q=c.poly[(i+1)%c.poly.length];a+=p[0]*q[1]-q[0]*p[1];}return Math.abs(a/2)*(c.z1-c.z0);};
for(const family of ['NW01','NW02','NR-S','NR-N']){
 const m=read(`output/table-lock-p51/${family}/model.json`),p=read(`output/table-workpack-p51/${family}-parts.json`),d=read(`output/table-demand-p51/${family}.json`),c=read(`output/table-connections-p51/${family}.json`);
 test(`${family}: nominal geometry, movement audit and source hashes`,()=>{assert.deepEqual(m.audit.initialHits,[]);assert.equal(m.audit.steps.length,40);assert.ok(m.audit.steps.every(s=>s.hits.length===0));assert.equal(m.audit.socket.length,12);assert.ok(m.audit.socket.every(s=>s.nominalEnvelopeClear));assert.equal(sha(m.audit.source),m.audit.sourceSha256);assert.equal(sha(p.geometrySource),p.geometrySha256);assert.equal(sha(d.source),d.sourceSha256);assert.equal(sha(c.source),c.sourceSha256);});
 test(`${family}: blank volume and hole origins reconcile`,()=>{let v=0;for(const r of p.rows){const a=r.dimensionsMm;v+=r.quantity*(r.stock==='RHS'?(a[0]*a[1]-(a[0]-2*a[2])*(a[1]-2*a[2]))*a[3]:a[0]*a[1]*a[2]);}v-=12*16*81*Math.sin(Math.PI/16)*(6+12+14);const actual=m.parts.filter(x=>/^M0/.test(x.id)).flatMap(x=>x.cells).reduce((s,c)=>s+volume(c),0);assert.ok(Math.abs(v-actual)<.01);p.holes.forEach(h=>{const l=m.lockSchedule.find(x=>x.id===h.id);assert.deepEqual(h.bedPlateCornerXYmm,[l.x+120,l.y+120]);});});
 test(`${family}: analysis equilibrium and geometry-only status`,()=>{for(const k of d.cases)Object.values(k.equilibrium).forEach(v=>assert.ok(Math.abs(v)<.01));for(const panel of c.panels)for(const k of panel.cases){assert.ok(Math.abs(k.forceResidualN)<1e-6);assert.ok(Math.abs(k.momentResidualNmm)<.001);assert.ok(k.meshReactionDifferenceN<1e-5);}assert.equal(p.productionReleased,false);assert.equal(d.engineeringApproved,false);assert.equal(c.capacityChecked,false);});
}
