import {readFile,realpath} from 'node:fs/promises';import {resolve,relative,isAbsolute,basename} from 'node:path';import {createHash} from 'node:crypto';
import {loadCastingLiftsP91} from './casting-lifts-p91.mjs';
import {loadTableWeldsP93} from './table-weld-p93.mjs';
import {loadTableBackersP96} from './table-seal-backer-p96.mjs';
import {loadTableBasesP97} from './table-lock-base-p97.mjs';
import {loadCoordinatedP99} from './mould-coordinated-p99.mjs';
import {loadTableSealsP95} from './table-seal-p95.mjs';
import {loadTableChannelsP94} from './table-channel-p94.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex');
// The supplement and setup registries reference the same immutable files many
// times. Check each unique path once per request, but reject conflicting pins.
// This does not cache by timestamp or skip fresh byte/hash verification.
export function uniqueIntegrityPins(root,pins){const m=new Map();for(const p of pins){const key=resolve(root,p.path),old=m.get(key);if(old&&old.sha256!==p.sha256)throw Error('Conflicting mould dependency hashes');if(!old)m.set(key,p);}return [...m.values()];}
export async function loadMouldCatalogue(root){
 const base='output/stage5-moulds-p38/',json=async p=>JSON.parse(await readFile(resolve(root,p),'utf8'));
 const [reg,manifest,deps,bundle]=await Promise.all([json(base+'register.json'),json(base+'manifest.json'),json(base+'dependencies.json'),json('data/modular-program/r02/mould-package-p38.json')]);
 const artifacts=new Map(),fileMap=new Map(manifest.files.map(f=>[f.path,f])),output=await realpath(resolve(root,'output'));
 async function safe(p){const full=await realpath(resolve(root,p)),rel=relative(output,full);if(rel.startsWith('..')||isAbsolute(rel)||!rel)throw Error('Outside allowlist');return full;}
 async function add(id,p,hash){const b=await readFile(await safe(p));if(sha(b)!==hash)throw Error('Mould integrity mismatch');const a={id,href:'/api/catalogue/moulds/artifacts/'+id,filename:basename(p),sha256:hash,bytes:b.length,contentType:p.endsWith('.png')?'image/png':p.endsWith('.svg')?'image/svg+xml':p.endsWith('.zip')?'application/zip':p.endsWith('.csv')?'text/csv; charset=utf-8':p.endsWith('.md')?'text/markdown; charset=utf-8':'application/json'};artifacts.set(id,{...a,path:p});return a;}
 const setups=[];
 for(const s of reg.setups){const files=[];for(const n of ['00-TYPICAL.png','00-TYPICAL.svg','01-CAVITY.png','01-CAVITY.svg','03-GEOMETRY-REVIEW.png','03-GEOMETRY-REVIEW.svg','setup.json']){const f=fileMap.get(s.folder+'/'+n);if(!f)throw Error('Missing mould file');files.push(await add(s.id+'-'+n.toUpperCase().replace('.','-'),base+f.path,f.sha256));}setups.push({id:s.id,typicalId:s.typicalId,kind:s.kind,concreteKg:s.concreteKg,dimensionsMm:s.dimensionsMm,usedBy:s.usedBy,files});}
 const archive=await add('PM-STAGE5-P38-ZIP',bundle.objectKey,bundle.sha256);
 const stylePath='output/mould-style-p43/manifest.json';
 const style=await json(stylePath).catch(e=>{if(e.code==='ENOENT')return null;throw e;});
 if(style){if(style.records.length!==44)throw Error('Incomplete presentation set');for(const r of style.records){const s=setups.find(s=>s.id===r.id);if(!s)throw Error('Unknown presentation setup');s.presentation=await add(r.id+'-P43-STYLE',r.path,r.sha256);}}
 const liftPath='output/concrete-lift-p52/register.json',lift=await json(liftPath).catch(e=>{if(e.code==='ENOENT')return null;throw e;});
 if(lift){if(lift.records.length!==44||new Set(lift.records.map(r=>r.id)).size!==44)throw Error('Incomplete lifting set');for(const r of lift.records){const s=setups.find(s=>s.id===r.id);if(!s)throw Error('Unknown lifting setup');s.liftingFiles=[];for(const f of r.files)s.liftingFiles.push(await add(r.id+'-P52-LIFT-'+f.path.split('.').at(-1).toUpperCase(),f.path,f.sha256));}}
 const devPath='output/stage5-library-p53/register.json',dev=await json(devPath).catch(e=>{if(e.code==='ENOENT')return null;throw e;});
 if(dev){if(dev.records.length!==44||new Set(dev.records.map(r=>r.id)).size!==44)throw Error('Incomplete development index');for(const r of dev.records){const s=setups.find(s=>s.id===r.id);if(!s)throw Error('Unknown development setup');s.hardwareStatus=r.hardwareStatus;s.developmentFiles=[];for(const f of r.files)s.developmentFiles.push(await add(r.id+'-'+f.key,f.path,f.sha256));}}
 const latestPath='output/stage5-library-p61/register.json',latest=await json(latestPath).catch(e=>{if(e.code==='ENOENT')return null;throw e;});
 if(latest){if(latest.records.length!==44||new Set(latest.records.map(r=>r.id)).size!==44)throw Error('Incomplete latest development index');for(const r of latest.records){const s=setups.find(s=>s.id===r.id);if(!s)throw Error('Unknown latest development setup');s.historicalDevelopmentFiles=(s.developmentFiles??[]).filter(a=>!r.files.some(f=>a.id===r.id+'-'+f.key));s.developmentFiles=[];s.hardwareStatus=r.hardwareStatus;s.sourceRevision=r.sourceRevision;for(const f of r.files)s.developmentFiles.push(await add(r.id+'-'+f.key,f.path,f.sha256));}}
 let supplement=null,supplementPath='';
 for(const p of ['output/stage5-library-p92/register.json','output/stage5-library-p90/register.json','output/stage5-library-p89/register.json','output/stage5-library-p88/register.json','output/stage5-library-p87/register.json','output/stage5-library-p68/register.json']){const value=await json(p).catch(e=>{if(e.code==='ENOENT')return null;throw e;});if(value){supplement=value;supplementPath=p;break;}}
 if(supplement){if(supplement.records.length!==12||new Set(supplement.records.map(r=>r.id)).size!==12)throw Error('Incomplete mould supplement');for(const r of supplement.records){const s=setups.find(s=>s.id===r.id);if(!s)throw Error('Unknown supplemental setup');s.supplementGroups=[];for(const g of r.groups){const files=[];for(const f of g.files)files.push(await add(r.id+'-'+f.key,f.path,f.sha256));s.supplementGroups.push({revision:g.revision,label:g.label,role:g.role,files});}}}
 const closurePath='output/stage5-closure-p90/register.json',closure=await json(closurePath).catch(e=>{if(e.code==='ENOENT')return null;throw e;});
 if(closure){if(closure.records.length!==44||new Set(closure.records.map(r=>r.id)).size!==44)throw Error('Incomplete closure inventory');for(const r of closure.records){const s=setups.find(s=>s.id===r.id);if(!s)throw Error('Unknown closure setup');const p='output/stage5-closure-p90/'+r.id+'.json';const b=await readFile(resolve(root,p));if(JSON.stringify(JSON.parse(b))!==JSON.stringify(r))throw Error('Closure file/register mismatch');s.closureFile=await add(r.id+'-P90-CLOSURE-JSON',p,sha(b));s.closureReview={revision:'P90',completeP40Design:r.completeP40Design,next:r.workstream.next,liftingCoordinateReview:r.liftingCoordinateReview,openDeliverables:r.requirements.filter(x=>!x.complete).length};}}
 const castingLifts=await loadCastingLiftsP91(root);
 const tableWelds=await loadTableWeldsP93(root);
 if(tableWelds)for(const r of tableWelds.records){const s=setups.find(s=>s.id===r.id);if(!s)throw Error('Unknown P93 table setup');s.tableWeldFiles=[];for(const [i,f] of r.files.entries())s.tableWeldFiles.push(await add(r.id+'-P93-WELD-'+(i+1),f.path,f.sha256));}
 const tableBackers=await loadTableBackersP96(root);
 if(tableBackers)for(const r of tableBackers.records){const s=setups.find(s=>s.id===r.id);if(!s)throw Error('Unknown P96 table setup');s.tableBackerFiles=[];for(const [i,f] of r.files.entries())s.tableBackerFiles.push(await add(r.id+'-P96-BACKER-'+(i+1),f.path,f.sha256));}
 const tableBases=await loadTableBasesP97(root);
 if(tableBases)for(const r of tableBases.records){const s=setups.find(s=>s.id===r.id);if(!s)throw Error('Unknown P97 table setup');s.tableBaseFiles=[];for(const [i,f] of r.files.entries())s.tableBaseFiles.push(await add(r.id+'-P97-BASE-'+(i+1),f.path,f.sha256));}
 const tableSeals=await loadTableSealsP95(root);
 if(tableSeals)for(const r of tableSeals.records){const s=setups.find(s=>s.id===r.id);if(!s)throw Error('Unknown P95 table setup');s.tableSealFiles=[];for(const [i,f] of r.files.entries())s.tableSealFiles.push(await add(r.id+'-P95-SEAL-'+(i+1),f.path,f.sha256));}
 const tableChannels=await loadTableChannelsP94(root);
 if(tableChannels)for(const r of tableChannels.records){const s=setups.find(s=>s.id===r.id);if(!s)throw Error('Unknown P94 table setup');s.tableChannelFiles=[];for(const [i,f] of r.files.entries())s.tableChannelFiles.push(await add(r.id+'-P94-CHANNEL-'+(i+1),f.path,f.sha256));}
 if(castingLifts)for(const r of castingLifts.records){const s=setups.find(s=>s.id===r.id);if(!s||s.sourceRevision!=='P56')throw Error('P91 casting layout without matching P56 mould');s.currentLiftingFiles=[];for(const f of r.files)s.currentLiftingFiles.push(await add(r.id+'-P91-LIFT-'+f.path.split('.').at(-1).toUpperCase(),f.path,f.sha256));}
 const coordinated=await loadCoordinatedP99(root);
 if(coordinated)for(const r of coordinated.records){const s=setups.find(s=>s.id===r.id);if(!s)throw Error('Unknown P99 setup');s.coordinatedFiles=[];for(const [i,f]of r.files.entries())s.coordinatedFiles.push(await add(r.id+'-P99-CURRENT-'+(i+1),f.path,f.sha256));}
 const scopeClosurePath='output/stage5-closure-p100/register.json';
 const scopeClosure=await json(scopeClosurePath).catch(e=>{if(e.code==='ENOENT')return null;throw e;});
 let scopeClosureArtifact=null;
 if(scopeClosure){
  if(scopeClosure.revision!=='P100'||scopeClosure.setupCount!==44||scopeClosure.records?.length!==44||!scopeClosure.stageComplete||scopeClosure.stageCompletionPercent!==100)throw Error('Invalid P100 Stage-5 scope closure');
  if(scopeClosure.engineeringApproved||scopeClosure.productionReleased)throw Error('P100 scope closure cannot release engineering or production');
  scopeClosureArtifact=await add('PM-STAGE5-P100-SCOPE-CLOSURE',scopeClosurePath,sha(await readFile(resolve(root,scopeClosurePath))));
 }
 const mutableStatusPaths=new Set(['knowledge/modular-program-current.json','knowledge/modular-program-r02/README.md']);
 const pins=[...deps.sources,...(castingLifts?.pins??[]),...(tableWelds?.pins??[]),...(tableChannels?.pins??[]),...(tableSeals?.pins??[]),...(tableBackers?.pins??[]),...(tableBases?.pins??[]),...(coordinated?.pins??[])].filter(p=>!scopeClosure||!mutableStatusPaths.has(p.path));for(const p of [base+'register.json',base+'manifest.json',base+'dependencies.json','data/modular-program/r02/mould-package-p38.json'])pins.push({path:p,sha256:sha(await readFile(resolve(root,p)))});
 if(scopeClosure){pins.push({path:scopeClosurePath,sha256:sha(await readFile(resolve(root,scopeClosurePath)))});for(const p of scopeClosure.sources)pins.push(p);}
 if(closure){pins.push({path:closurePath,sha256:sha(await readFile(resolve(root,closurePath)))},...closure.pins);for(const s of setups)pins.push({path:artifacts.get(s.closureFile.id).path,sha256:s.closureFile.sha256});}
 if(supplement){pins.push({path:supplementPath,sha256:sha(await readFile(resolve(root,supplementPath)))},...supplement.pins);for(const r of supplement.records)for(const g of r.groups)for(const f of g.files)pins.push({path:f.path,sha256:f.sha256});}
 if(style){pins.push({path:stylePath,sha256:sha(await readFile(resolve(root,stylePath)))});for(const r of style.records)pins.push({path:r.source,sha256:r.sourceSha256});}
 if(lift){pins.push({path:liftPath,sha256:sha(await readFile(resolve(root,liftPath)))});pins.push({path:'knowledge/modular-program-r02/decision-lifting-p52.json',sha256:lift.decisionSha256},{path:'tools/modular-program/concrete-lift-p52.mjs',sha256:lift.generatorSha256});for(const r of lift.records)pins.push({path:r.source,sha256:r.sourceSha256});}
 if(dev){pins.push({path:devPath,sha256:sha(await readFile(resolve(root,devPath)))});for(const r of dev.records)for(const f of r.files)pins.push({path:f.path,sha256:f.sha256});}
 if(latest){pins.push({path:latestPath,sha256:sha(await readFile(resolve(root,latestPath)))},...latest.pins);for(const r of latest.records)for(const f of r.files)pins.push({path:f.path,sha256:f.sha256});}
 // P100 froze the Stage-5 scope. Later-stage status pointers are mutable,
 // including copies contributed by historical supplements; geometry pins stay intact.
 const integrityPins=uniqueIntegrityPins(root,pins.filter(p=>!scopeClosure||!mutableStatusPaths.has(p.path)));
 async function stale(){try{for(const p of integrityPins)if(sha(await readFile(resolve(root,p.path)))!==p.sha256)return true;return false;}catch{return true;}}
 if(await stale()){const mismatches=[];for(const p of integrityPins){try{if(sha(await readFile(resolve(root,p.path)))!==p.sha256)mismatches.push(p.path);}catch{mismatches.push(p.path);}}throw Error('Mould dependencies stale: '+mismatches.join(', '));}
 const mayRead=(m,a,allow)=>Boolean(a&&m.canReadEngineering&&allow(m,a.id)&&(a.id!=='PM-STAGE5-P38-ZIP'||m.artifactIds==='*'));
 async function view(m,allow){return {revision:'P38-R1',coordinatedRevision:coordinated?.revision??null,scopeClosureRevision:scopeClosure?.revision??null,supplementRevision:supplement?.revision??null,presentationRevision:style?'P43':null,liftingRevision:lift?'P52':null,castingLiftingRevision:castingLifts?.revision??null,tableWeldRevision:tableWelds?.revision??null,tableChannelRevision:tableChannels?.revision??null,tableSealRevision:tableSeals?.revision??null,tableBackerRevision:tableBackers?.revision??null,tableBaseRevision:tableBases?.revision??null,developmentRevision:latest?'P61':dev?'P53':null,stage:5,status:await stale()?'STALE':scopeClosure?.stageComplete?'STAGE5_PLANNING_SCOPE_COMPLETE':'GEOMETRY_REVIEW_HOLD',stageCompletionPercent:scopeClosure?.stageCompletionPercent??null,stageComplete:scopeClosure?.stageComplete??false,stageClosure:mayRead(m,scopeClosureArtifact,allow)?scopeClosureArtifact:null,deferredWorkstreams:scopeClosure?.deferredWorkstreams??[],setups:setups.map(s=>({...s,coordinatedFiles:(s.coordinatedFiles??[]).filter(a=>mayRead(m,a,allow)),tableBaseFiles:(s.tableBaseFiles??[]).filter(a=>mayRead(m,a,allow)),tableBackerFiles:(s.tableBackerFiles??[]).filter(a=>mayRead(m,a,allow)),tableSealFiles:(s.tableSealFiles??[]).filter(a=>mayRead(m,a,allow)),tableChannelFiles:(s.tableChannelFiles??[]).filter(a=>mayRead(m,a,allow)),tableWeldFiles:(s.tableWeldFiles??[]).filter(a=>mayRead(m,a,allow)),currentLiftingFiles:(s.currentLiftingFiles??[]).filter(a=>mayRead(m,a,allow)),closureFile:mayRead(m,s.closureFile,allow)?s.closureFile:null,closureReview:mayRead(m,s.closureFile,allow)?s.closureReview:null,supplementGroups:(s.supplementGroups??[]).map(g=>({...g,files:g.files.filter(a=>mayRead(m,a,allow))})).filter(g=>g.files.length),presentation:mayRead(m,s.presentation,allow)?s.presentation:null,historicalDevelopmentFiles:(s.historicalDevelopmentFiles??[]).filter(a=>mayRead(m,a,allow)),developmentFiles:(s.developmentFiles??[]).filter(a=>mayRead(m,a,allow)),liftingFiles:(s.liftingFiles??[]).filter(a=>mayRead(m,a,allow)),files:s.files.filter(a=>mayRead(m,a,allow))})).filter(s=>s.coordinatedFiles.length||s.tableBaseFiles.length||s.tableBackerFiles.length||s.tableSealFiles.length||s.tableChannelFiles.length||s.tableWeldFiles.length||s.currentLiftingFiles.length||s.closureFile||s.supplementGroups.length||s.files.length||s.liftingFiles.length||s.developmentFiles.length||s.historicalDevelopmentFiles.length||s.presentation),archive:mayRead(m,archive,allow)?archive:null,physicalMouldCount:null,engineeringApproved:false,productionReleased:false};}
 async function bytes(id){const a=artifacts.get(id);if(!a||await stale())return null;try{const b=await readFile(await safe(a.path));return sha(b)===a.sha256?b:null;}catch{return null;}}
 return {artifacts,mayRead,view,bytes};
}
